### PR TITLE
Rename operator and router namespaces

### PR DESCRIPTION
**Pull request by ironcladlou**
Rename the following namespaces:

* openshift-cluster-ingress-operator => openshift-ingress-operator
* openshift-cluster-ingress-router => openshift-ingress

This is necessary to conform to existing upstream expectations for the location
of router instances (e.g. tests and other installer stuff).

Refactor the RBAC stuff to look a little more consistent.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Tested in a 4.0 AWS cluster with a newly published image:

```
$ CLUSTER_NAME=dmace make test-integration
hack/test-integration.sh
=== RUN   TestIntegration
=== RUN   TestIntegration/TestDefaultIngress
time="2018-10-17T13:25:03-04:00" level=info msg="testing in namespace ingress-test-jtdrun"
--- PASS: TestIntegration (84.78s)
    --- PASS: TestIntegration/TestDefaultIngress (84.78s)
        test_ingress.go:71: router service openshift-ingress/router-default has external hostname a71d8c685d23111e8a9760251897841d-842485194.us-east-1.elb.amazonaws.com                                        
PASS
ok      github.com/openshift/cluster-ingress-operator/test/integration  84.825s
```

**Comment by pravisankar** [comment]
@ironcladlou 
config/config.yaml has projectName: cluster-ingress-operator , do we need to rename this? (it says kind: ClusterIngress where is this used?)

**Comment by ironcladlou** [comment]
>@ironcladlou
config/config.yaml has projectName: cluster-ingress-operator , do we need to rename this? (it says kind: ClusterIngress where is this used?) I think this is expected by operator-sdk but not used else where.

This is something related to the operator-sdk, don't remember. I wanted to keep all the go packaging and binary stuff the same.

**Pull request merged**
