### PR TITLE
Bug 2007246: Ingress Controller does not set allowPrivilegeEscalation in the router deployment

### PR DESCRIPTION
**Pull request by brandisher**
This will ensure that the router pod gets selected into the correct SCC to avoid conflicts with custom SCCs.

### CODE REVIEW

**Comment by brandisher** [comment]
/retitle Bug 2007246: Ingress Controller does not set allowPrivilegeEscalation in the router deployment

**Comment by brandisher** [comment]
"could not get build src: builds.build.openshift.io "src" not found"

/retest

**Comment by frobware** [comment]
```console
error: unable to read image registry.build02.ci.openshift.org/ci-op-rm59whc7/stable-initial@sha256:05da12974a584879b0c7c04b0b6b5173173deeb2d621b619f0ea2c007f63f744: received unexpected HTTP status: 504 Gateway Time-out
```

/retest

**Comment by brandisher** [comment]
`cluster bootstrap failed`

/retest

**Comment by brandisher** [comment]
must-gather failed along with some monitoring stack rollout errors.

/retest

**Comment by brandisher** [comment]
`"e2e-aws-operator" pod "e2e-aws-operator-ipi-install-install" failed`

/retest

**Comment by frobware** [comment]
/lgtm

Adding a hold in case @Miciah has any requests/changes/observations. 

/hold

**Comment by Miciah** [comment]
Lovely jubbly!  
/lgtm
/hold cancel

**Pull request merged**
