### PR TITLE
Replace router DaemonSet with Deployment

### PR DESCRIPTION
**Pull request by Miciah**
* `assets/router/deployment.yaml`: Rename from `daemonsets.yaml`.  Change from daemonset to deployment.
* `cmd/cluster-ingress-operator/main.go` (`main`): Watch deployments instead of daemonsets.
* `manifests/00-cluster-role.yaml`: Delete permissions for daemonsets and the extensions API group, and add permission for deployments.
* `manifests/01-role.yaml`: Delete permissions for daemonsets, replicasets, and statefulsets.
* `pkg/manifests/bindata.go`: Regenerate.
* `pkg/manifests/manifests.go` (`RouterDeployment`): Rename from `RouterDaemonset`.
(`RouterDeployment`): Rename from `RouterDaemonset`.  Build and return a Deployment.
(`NewDaemonSet`): Delete.
* `pkg/manifests/manifests_test.go` (`TestManifests`): Replace `RouterDaemonSet` with `RouterDeployment`.
* `pkg/stub/handler.go` (`ensureRouterNamespace`): Replace `RouterDaemonSet` with `RouterDeployment`.  Replace `daemonsetConfigChanged` with `deploymentConfigChanged`.
(`ensureRouterServiceForIngress`): Change parameter from DaemonSet to Deployment.
(`ensureRouterDeleted`): Replace `RouterDaemonSet` with `RouterDeployment`.
(`deploymentConfigChanged`): Rename from `daemonsetConfigChanged`.  Change parameter from DameonSet to Deployment.
* `pkg/stub/status.go` (`syncOperatorStatus`): Replace daemonsets with deployments.
(`getOperatorState`): Change return value from slice of DaemonSets to slice of Deployments.
(`computeStatusConditions`): Change parameter from slice of DaemonSets to slice of Deployments.  Replace `.status.numberAvailable` with `.status.availableReplicas`.
* `pkg/stub/status_test.go` (`TestComputeStatusConditions`):
* `test/e2e/operator_test.go` (`TestClusterIngressUpdate`): Replace DaemonSets with Deployments.

This PR resolves [https://jira.coreos.com/browse/NE-104](NE-104).

---

@ironcladlou

Tested with `make test-e2e` and `openshift-tests run openshift/smoke-4 --dry-run | grep -i -e router | openshift-tests run -f -`.

### CODE REVIEW

**Comment by ironcladlou** [comment]
We'll need some way to deal with scaling... for now, @knobunc and I are proposing adding a field to ClusterIngress:

```
// Replicas is the scale of the deployment. If nil, the value
// is automatically managed. For now, "automatically managed"
// means the value is always 1.
// TODO: Define and document how auto management/scaling will work.
Replicas *int
```

This also means we'll need to react to changes to this field.

**Comment by ironcladlou** [comment]
We can hard-code the replicas to 1 in this PR and address scaling in a followup right after.

**Comment by Miciah** [comment]
Latest push adds a `replicas` field to the ClusterIngress resource and updates the manifests factory and tests accordingly.

**Comment by Miciah** [comment]
Reverted last push.  We want to amend ClusterIngress in a follow-up PR.

**Pull request merged**
