### PR TITLE
Bug 1866299: Forces Tagging Client to us-gov-west-1 Region

### PR DESCRIPTION
**Pull request by danehans**
Route53 for GovCloud is based out of us-gov-west-1, so the tagging client must match this region even with custom endpoints configured. This PR updates the tagging client endpoint configuration to meet this requirement and removes unused constants.

/assign @Miciah @knobunc 
/cc @frobware @sgreene570

### CODE REVIEW

**Comment by danehans** [comment]
```
Unexpected error:
    <*errors.errorString | 0xc001563ea0>: {
        s: "Cluster did not complete upgrade: timed out waiting for the condition: Cluster operator openshift-apiserver is reporting a failure: APIServerDeploymentDegraded: 1 of 3 requested instances are unavailable for apiserver.openshift-apiserver",
    }
    Cluster did not complete upgrade: timed out waiting for the condition: Cluster operator openshift-apiserver is reporting a failure: APIServerDeploymentDegraded: 1 of 3 requested instances are unavailable for apiserver.openshift-apiserver
```

/test e2e-aws-upgrade

**Comment by sgreene570** [comment]
looks good.
/lgtm

**Comment by sgreene570** [comment]
@danehans, https://github.com/openshift/cluster-ingress-operator/pull/463 should unblock this PR

**Comment by frobware** [comment]
/hold

This is failing CI often and quickly; putting on hold until @danehans can investigate.

**Comment by danehans** [comment]
```
hack/verify-deps.sh
go: github.com/openshift/library-go@v0.0.0-20200324092245-db2a8546af81 requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
make: *** [verify] Error 1
```
May be related to https://github.com/openshift/cluster-ingress-operator/pull/463

**Comment by danehans** [comment]
Sam job failure as https://github.com/openshift/cluster-ingress-operator/pull/460#issuecomment-696204115. @sgreene570 can you confirm that https://github.com/openshift/cluster-ingress-operator/pull/463 will fix this issue?

**Comment by sgreene570** [comment]
> Same job failure as [#460 (comment)](https://github.com/openshift/cluster-ingress-operator/pull/460#issuecomment-696204115). @sgreene570 can you confirm that #463 will fix this issue?

Yes, #463 will fix the issue once it merges

**Pull request merged**
