### PR TITLE
[release-4.13] OCPBUGS-12743: bump controller-runtime to fix the multi namespace cache indexing

### PR DESCRIPTION
**Pull request by alebedev87**
Backport of https://github.com/openshift/cluster-ingress-operator/pull/913.

### CODE REVIEW

**Comment by Miciah** [comment]
[e2e-aws-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/921/pull-ci-openshift-cluster-ingress-operator-release-4.13-e2e-aws-operator/1653766786216103936) because `TestClientTLS` failed.  #923 should resolve the test failures for 4.13.

**Comment by Miciah** [comment]
This is a clean cherry-pick that bumps the vendored sigs.k8s.io/controller-runtime package ahead a few commits to pick up a low-risk but important bug fix.  This bump pulls in a few unrelated commits, but they look harmless.  
/approve
/lgtm
/label backport-risk-assessed

**Comment by alebedev87** [comment]
/jira refresh

maybe now?

**Comment by Miciah** [comment]
[e2e-aws-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/921/pull-ci-openshift-cluster-ingress-operator-release-4.13-e2e-aws-operator/1670744780595793920) because must-gather failed.
/test e2e-aws-operator

**Pull request merged**
