### PR TITLE
use GA kubelet OS label

### PR DESCRIPTION
**Pull request by rphillips**
ref: https://jira.coreos.com/browse/POD-114

### CODE REVIEW

**Comment by ironcladlou** [comment]
I see this passed upgrade tests — are the existing node labels getting migrated somehow?

/approve

@Miciah @danehans PTAL

**Comment by Miciah** [comment]
> I see this passed upgrade tests — are the existing node labels getting migrated somehow?

The ingress operator will update the operand's labels:

https://github.com/openshift/cluster-ingress-operator/blob/15d536fc3ca99fbefa40db8af10563e67aebfab9/pkg/operator/controller/controller_router_deployment.go#L283-L301

Will CVO update the operator's?

**Comment by rphillips** [comment]
Old and new labels are sticking around until Kubernetes 1.17.

**Comment by danehans** [comment]
@rphillips can you rebase?

**Comment by rphillips** [comment]
@danehans rebased

**Pull request merged**
