### PR TITLE
Follow-Up fixes for PR 427

### PR DESCRIPTION
**Pull request by danehans**
- `pkg/operator/controller/ingress/load_balancer_service.go`: Checks for the absence of AWS provider parameters.
- `pkg/operator/controller/ingress/load_balancer_service_test.go`: removes load balancer scope from "external classic load balancer without scope" test case.

### CODE REVIEW

**Comment by Miciah** [comment]
/lgtm
Thanks!

**Comment by Miciah** [comment]
Failed to provision (`InternetGatewayLimitExceeded`).
/test e2e-aws-upgrade

**Comment by danehans** [comment]
```
error: some steps failed:
  * could not run steps: step e2e-aws-operator failed: failed to acquire lease: resources not found
time="2020-07-31T19:52:24Z" level=info msg="Reporting job state \"failed\" with reason \"executing_graph:step_failed:utilizing_lease:acquiring_lease:aws-quota-slice\""
```

/test e2e-aws-operator

**Comment by danehans** [comment]
```
error: some steps failed:
  * could not run steps: step e2e-aws-operator failed: failed to acquire lease: Post "https://boskos-ci.apps.ci.l2s4.p1.openshiftapps.com/acquire?dest=leased&owner=ci-op-9q4bp0nx-43abb&request_id=1976235410884491574&state=free&type=aws-quota-slice": net/http: TLS handshake timeout
time="2020-07-31T21:06:36Z" level=info msg="Reporting job state \"failed\" with reason \"executing_graph:step_failed:utilizing_lease:acquiring_lease:aws-quota-slice\""
```

/test e2e-aws-operator

**Pull request merged**
