### PR TITLE
[release-4.12] OCPBUGS-34757: Avoid spurious updates for internalTrafficPolicy

### PR DESCRIPTION
**Pull request by candita**
This is a manual backport of https://github.com/openshift/cluster-ingress-operator/pull/1055  to fix OCPBUGS-33657.

git cherry-pick https://github.com/openshift/cluster-ingress-operator/commit/5579aa1b3573a4d9479a924a1ae78688e2105c5c
go mod vendor
go mod tidy
make generate
make update
git cherry-pick https://github.com/openshift/cluster-ingress-operator/commit/6cd3b6709eff0026ad814921b40c4b02c32fb38c
go mod vendor
go mod tidy
make generate
make update

**Avoid spurious updates for internalTrafficPolicy**

Specify spec.internalTrafficPolicy on NodePort- and ClusterIP-type services that the operator manages. Also, ignore updates to the spec.ipFamilies and spec.ipFamilyPolicy fields.

Before this PR, the update logic for NodePort- and ClusterIP-type services would try to revert the default values that the API set for these fields.

- assets/router/service-cloud.yaml:
- assets/router/service-internal.yaml: Specify internalTrafficPolicy: Cluster.
- pkg/manifests/bindata.go: Regenerate.
- pkg/operator/controller/ingress/internal_service.go (internalServiceChanged): Ignore spec.ipFamilies and spec.ipFamilyPolicy.
- pkg/operator/controller/ingress/internal_service_test.go (Test_desiredInternalIngressControllerService): Verify that spec.internalServiceChanged is set to "Cluster". (Test_internalServiceChanged): Verify that changes to spec.internalTrafficPolicy are detected and that changes to spec.ipFamilies and spec.ipFamilyPolicy are ignored.
- pkg/operator/controller/ingress/nodeport_service.go (desiredNodePortService): Set spec.internalTrafficPolicy to "Cluster". (nodePortServiceChanged): Ignore spec.ipFamilies and spec.ipFamilyPolicy. 
- pkg/operator/controller/ingress/nodeport_service_test.go (TestDesiredNodePortService): Verify that spec.internalTrafficPolicy is set to "Cluster". (TestNodePortServiceChanged): Verify that changes to spec.internalTrafficPolicy are detected and that changes to spec.ipFamilies and spec.ipFamilyPolicy are ignored.

**Ignore updates for null versus empty ennotations**
Ignore updates to annotations when the update is from null to empty or vice versa.

- pkg/operator/controller/ingress/internal_service.go (internalServiceChanged): Use EquateEmpty when comparing annotations.
- pkg/operator/controller/ingress/internal_service_test.go (TestInternalServiceChangedEmptyAnnotations): New test to verify that internalServiceChanged treats empty and null annotations as equal.
- pkg/operator/controller/ingress/load_balancer_service_test.go (TestLoadBalancerServiceChangedEmptyAnnotations): New test to verify that loadBalancerServiceChanged treats empty and null annotations as equal.
- pkg/operator/controller/ingress/nodeport_service.go (nodePortServiceChanged): Use EquateEmpty when comparing annotations.
- pkg/operator/controller/ingress/nodeport_service_test.go (TestNodePortServiceChangedEmptyAnnotations): New test to verify that loadBalancerServiceChanged treats empty and null annotations as equal.

### CODE REVIEW

**Comment by candita** [comment]
images issue:

> {  failed to wait for importing imagestreamtags on ci-op-3i9dbxb0/stable: failed to reimport the tag ci-op-3i9dbxb0/stable:cluster-samples-operator: unable to import tag ci-op-3i9dbxb0/stable:cluster-samples-operator with message Internal error occurred: [you may not have access to the container image "qci-pull-through-cache-us-east-1-ci.apps.ci.l2s4.p1.openshiftapps.com/openshift/ci:ci-op-3i9dbxb0_stable_cluster-samples-operator", dockerimage.image.openshift.io "quay.io/openshift/ci:ci-op-3i9dbxb0_stable_cluster-samples-operator" not found, dockerimage.image.openshift.io "quay-proxy.ci.openshift.org/openshift/ci:ci-op-3i9dbxb0_stable_cluster-samples-operator" not found] on the image stream even after (6) imports: timed out waiting for the condition}

/test images

**Comment by candita** [comment]
I deleted the test namespace, let's see what happens
/test images

**Comment by Miciah** [comment]
This change is low-risk.  The changes in the PR are scoped to the update logic for services, and the changes are to set `internalTrafficPolicy` to its default value and ignore updates to the `ipFamilies` and `ipFamilyPolicy` fields.   The feature gate for `internalTrafficPolicy` has been [enabled by default since OpenShift 4.9](https://github.com/openshift/kubernetes/blob/71d09da80de984c34d81ed71b1f1607ca56088e2/pkg/features/kube_features.go#L899), and the feature gate for `ipFamilies` and `ipFamilyPolicy` has been [enabled by default since OpenShift 4.8](https://github.com/openshift/kubernetes/blob/8b969e704241724b962a28da47f0224d09985959/pkg/features/kube_features.go#L826).  As long as the fields exist, explicitly setting a value that is equal to the default value or ignoring the update by the API server to set the default value should be safe.  
/label backport-risk-assessed

**Comment by melvinjoseph86** [comment]
Verified using pre-image with cluster bot.
melvinjoseph@mjoseph-mac Downloads % oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.ci.test-2024-06-05-052414-ci-ln-7tjs33t-latest   True        False         83m     Cluster version is 4.12.0-0.ci.test-2024-06-05-052414-ci-ln-7tjs33t-latest

After the cluster installation there was no more 'updated internal service' log messages in openshift-ingress-operator logs.
Even after creating a custom nodeport controller and a loadbalncer controller, there was no above log messages. Hence marking as verified.

**Comment by Miciah** [comment]
/retitle [release-4.12] OCPBUGS-34757: Avoid spurious updates for internalTrafficPolicy

**Comment by candita** [comment]
CI images issue should be resolved.

/retest

**Pull request merged**
