### PR TITLE
Bug 1905490: Revert "Support changing ingresscontroller load balancer scope"

### PR DESCRIPTION
**Pull request by Miciah**
This reverts #482.

### CODE REVIEW

**Comment by Miciah** [comment]
/hold
while we discuss.

**Comment by sgreene570** [comment]
LGTM.
Waiting for input from @knobunc, et al., before we merge this.

**Comment by Miciah** [comment]
[sig-arch] Managed cluster should have no crashlooping pods in core namespaces over four minutes [Suite:openshift/conformance/parallel]
    [sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early] [Suite:openshift/conformance/parallel]

/test e2e-aws

**Comment by Miciah** [comment]
e2e-aws-operator tests passed, but must-gather failed.

/test e2e-aws-operator.

**Comment by Miciah** [comment]
/retitle Bug 1905490: Revert "Support changing ingresscontroller load balancer scope"
/hold cancel
We will revert the change in 4.6 with this PR.  In a follow-up, we will add logic to block upgrades from 4.6 to 4.7 if the user has modified the service.  (Modifications to operator-managed objects are unsupported and should never have been allowed.)

**Comment by Miciah** [comment]
e2e-aws-operator tests passed again, and must-gather failed again.  
/test e2e-aws-operator

**Comment by Miciah** [comment]
Lots of other components' pods are failing to start.

    [sig-arch] Managed cluster should have no crashlooping pods in core namespaces over four minutes [Suite:openshift/conformance/parallel]
    [sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early] [Suite:openshift/conformance/parallel]

/test e2e-aws

**Comment by Miciah** [comment]
must-gather failed again.
/test e2e-aws-operator

**Comment by Miciah** [comment]
Failed again on must-gather.  
/test e2e-aws-operator

**Comment by knobunc** [comment]
Approved based on discussions with @eparis (but he was not somewhere where he could hit the button at the time).

**Comment by Miciah** [comment]
At least the last CI run was able to provision the cluster, but it failed on `[sig-arch] Managed cluster should have no crashlooping pods in core namespaces over four minutes` because cluster-monitoring-operator's kube-rbac-proxy sidecar container didn't start.

**Pull request merged**
