### PR TITLE
OCPBUGS-1554: Bump vendored k8s libraries to 1.25

### PR DESCRIPTION
**Pull request by gcs278**
Update k8s.io/api, k8s.io/apimachinery, k8s.io/apiserver, and k8s.io/client-go to v0.25.0 as well as sigs.k8s.io/controller-runtime to v0.13.0 which maps to the overall 1.25 kubernetes release. Also bump github.com/openshift/library-go for its 1.25 support. All other vendor updates were automatically included as a part of these updates.

**pkg/operator/controller/dns/controller.go**: Moved `utilclock` to "k8s.io/utils/clock" and added `utilclocktesting "k8s.io/utils/clock/testing"` as that where `NewFakeClock` moved into.
**pkg/operator/controller/dns/controller.go**: Moved `utilclock` to "k8s.io/utils/clock"
**pkg/operator/controller/ingress/status.go**: Moved `utilclock` to "k8s.io/utils/clock"
**pkg/operator/controller/status/controller.go**: Moved `utilclock` to "k8s.io/utils/clock"

### CODE REVIEW

**Comment by gcs278** [comment]
/hold
E2E build failure I missed regarding `NewFakeClock` missing.

**Comment by gcs278** [comment]
/unhold
`NewFakeClock` moved to k8s.io/utils/clock/testing

**Comment by frobware** [comment]
You have some .idea and .envrc files committed here.

```
A [.envrc](https://github.com/openshift/cluster-ingress-operator/pull/829/files#diff-d33e979799a45c7c51752e9c8d96a3e452015d1a40b1e4b6ec6a98e92c4d8430) (1)
A [.idea/.gitignore](https://github.com/openshift/cluster-ingress-operator/pull/829/files#diff-21610973868a98feff98dd0460438a8a32cca1447bc8701537ec5048e0c5faeb) (8)
A [.idea/cluster-ingress-operator.iml](https://github.com/openshift/cluster-ingress-operator/pull/829/files#diff-3cc7c2f38630ac52dcd6b7a2cd0b31ba4b1ac4050d2827792eb489aee98b69c2) (9)
A [.idea/modules.xml](https://github.com/openshift/cluster-ingress-operator/pull/829/files#diff-0aae258f1732eac2acd4fcdd1af6d0737b4ec8d233136c3ba7c40b6d49aeda50) (8)
A [.idea/vcs.xml](https://github.com/openshift/cluster-ingress-operator/pull/829/files#diff-a6dab70bd0e9ffc91d8419ad52225baff3a3e7c9d8e1724f7ed6d96b661d804a) (6)
```

**Comment by gcs278** [comment]
> You have some .idea and .envrc files committed here.

@frobware I did have .idea and .envrc checked in by accident, but they have since been removed. Are you still seeing them in the commit? I can't find them.

**Comment by gcs278** [comment]
Tons of CI failures, looks like ingress is not working. Will investigate.

**Comment by frobware** [comment]
> > You have some .idea and .envrc files committed here.
> 
> @frobware I did have .idea and .envrc checked in by accident, but they have since been removed. Are you still seeing them in the commit? I can't find them.

I was reading changes via email. Looking again, I don't see them in the commit.

**Comment by gcs278** [comment]
/retest
Maybe this was fluke?

**Comment by frobware** [comment]
/lgtm
/approve
/hold

Feel free to remove the hold once you're satisfied with a CI run (or two).

**Comment by gcs278** [comment]
getting `OVNKubernetesControllerDisconnectedSouthboundDatabase` issues
/retest

**Comment by gcs278** [comment]
I don't think related, others are seeing this issue: `ingress-to-oauth-server-new-connections was unreachable during disruption testing`
/retest

**Comment by gcs278** [comment]
The install failed...
/retest

**Comment by gcs278** [comment]
OVNKubernetesControllerDisconnectedSouthboundDatabase failure again, and now a new `pods should keep the assigned EgressIPs when being rescheduled to another node` connection timeout failure, which I don't believe to be affected by cluster-ingress-operator.
/retest

**Comment by gcs278** [comment]
Both OVN and the `ingress-to-oauth-server-new-connections was unreachable during disruption testing` type testing.
Supposedly the disruption tests are fixed, so:
/retest

**Comment by brandisher** [comment]
ingress-to-XXX issues again
/test e2e-gcp-ovn-serial

**Comment by brandisher** [comment]
etcd and ovn issues
/retest e2e-gcp-ovn-serial

**Comment by gcs278** [comment]
/unhold
I think we've gotten enough CI runs in. It's just stuck on know problems (OVN and disruption).

**Pull request merged**
