### PR TITLE
[release-4.16] OCPBUGS-36184: Add e2e test for connect timeout

### PR DESCRIPTION
**Pull request by alebedev87**
Backport of https://github.com/openshift/cluster-ingress-operator/pull/1084.

### CODE REVIEW

**Comment by gcs278** [comment]
I confirmed this was a clean backport (not sure about your [/cherry-pick error message](https://github.com/openshift/cluster-ingress-operator/pull/1084#issuecomment-2189740495)). Changes have already been reviewed in the master branch, and no changes seem concerning for 4.16, as it's an E2E, and it's also only additive.

/approve
/lgtm

**Comment by candita** [comment]
Backport risk is minimal and acceptable because this is a new CI test that is showing to be working properly.

/label backport-risk-assessed

**Pull request merged**
