### PR TITLE
NE-1276: Expose other DCM controls as unsupportedConfigOverrides in ingresscontroller CR

### PR DESCRIPTION
**Pull request by k-wall**
Signed-off-by: kwall <kwall@apache.org>

### CODE REVIEW

**Comment by candita** [comment]
@k-wall Thanks for your contribution.  I contacted you via slack regarding an alternative way to add this PR.  Please reply when you get a chance.

**Comment by k-wall** [comment]
> @k-wall Thanks for your contribution. I contacted you via slack regarding an alternative way to add this PR. Please reply when you get a chance.

Thank you. I replied to you there.

**Comment by candita** [comment]
/retitle NE-1276: Expose other DCM controls as unsupportedConfigOverrides in ingresscontroller CR

**Pull request closed without merging**
