### PR TITLE
[WIp] Added Power VS platfrom to e2e test suite

### PR DESCRIPTION
**Pull request by Karthik-K-N**
Added Power VS platform to TestInternalLoadBalancer test

### CODE REVIEW

**Comment by Miciah** [comment]
We don't have any CI jobs defined for Power VS in [the Prow configuration for this repository and branch](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml).  Are you running the test suite using some other CI system?

**Comment by Karthik-K-N** [comment]
> We don't have any CI jobs defined for Power VS in [the Prow configuration for this repository and branch](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml). Are you running the test suite using some other CI system?

[Recently](https://github.com/openshift/cluster-ingress-operator/pull/658) I have added the support for Power VS platform in ingress operator, This PR is submitted to track the changes required to add the Power VS platform to e2e test suite. 
Currently we have not running the test suite using any CI system, I am curious to know where all should the respective changes needs to be submitted to include Power VS in ingress operator CI sytem

**Comment by Miciah** [comment]
> > We don't have any CI jobs defined for Power VS in [the Prow configuration for this repository and branch](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml). Are you running the test suite using some other CI system?
> 
> [Recently](https://github.com/openshift/cluster-ingress-operator/pull/658) I have added the support for Power VS platform in ingress operator, This PR is submitted to track the changes required to add the Power VS platform to e2e test suite. Currently we have not running the test suite using any CI system, I am curious to know where all should the respective changes needs to be submitted to include Power VS in ingress operator CI sytem

The Prow configuration that I linked to in my first comment defines the various CI jobs.  For example, https://github.com/openshift/release/pull/15872/commits/4830ab6e0ef9d02d3b9949502dcbab29d8e765ca added the e2e-azure-operator job; I would expect a similar commit for Power VS, if Power VS is going to tested by our CI system.

**Comment by Karthik-K-N** [comment]
> > > We don't have any CI jobs defined for Power VS in [the Prow configuration for this repository and branch](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/cluster-ingress-operator/openshift-cluster-ingress-operator-master-presubmits.yaml). Are you running the test suite using some other CI system?
> > 
> > 
> > [Recently](https://github.com/openshift/cluster-ingress-operator/pull/658) I have added the support for Power VS platform in ingress operator, This PR is submitted to track the changes required to add the Power VS platform to e2e test suite. Currently we have not running the test suite using any CI system, I am curious to know where all should the respective changes needs to be submitted to include Power VS in ingress operator CI sytem
> 
> The Prow configuration that I linked to in my first comment defines the various CI jobs. For example, [openshift/release@4830ab6](https://github.com/openshift/release/commit/4830ab6e0ef9d02d3b9949502dcbab29d8e765ca) added the e2e-azure-operator job; I would expect a similar commit for Power VS, if Power VS is going to tested by our CI system.

Thanks for the information, I will check and update accordingly

**Pull request closed without merging**
