### PR TITLE
Do not use 'operator' name for router cluster role and role bindings

### PR DESCRIPTION
**Pull request by pravisankar**
Otherwise it will create confusion with roles used in cluster-ingress-operator.

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/sig-network-edge PTAL

**Comment by imcsk8** [comment]
LGTM i got confused by this

**Comment by ironcladlou** [comment]
The names like `cluster-ingress-operator:router` were meant to be disambiguating by using the `cluster-ingress-operator:` prefix. For example, when we roll out keepalived deployments, we may want `cluster-ingress-operator:keepalived`.

**Comment by pravisankar** [comment]
@openshift/sig-network-edge Updated, PTAL

Now the actual operator will use 'cluster-ingress-operator' name for its ClusterRole/ClusterRoleBindings and ingress operator driven components like router, keepalived, etc. will use 'cluster-ingress:' prefix (e.g. cluster-ingress:router, cluster-ingress:keepalived) for their cluster roles.

**Comment by ironcladlou** [comment]
I like the way this looks, thanks

/lgtm

**Pull request merged**
