### PR TITLE
Bug 1703943: Make deployment topologies more predictable by prohibiting co-location

### PR DESCRIPTION
**Pull request by ironcladlou**
Before this change, ingresscontrollers published via LoadBalancerService could
be co-located according to a soft anti-affinity policy. This policy resulted in
a high probability of scheduler outcomes whereby 100% of ingresscontroller
processes were co-located on a single node after cluster installation, defeating
HA.

In the absence of the descheduler (for auto-rebalancing), the possibility
of unwanted co-location is too great a risk given admins have no obvious way
to detect the surprise co-location and no good procedure for forcing rebalancing.

After this change, deployment topologies are made more predictable by disabling
co-location for all publishing strategies.

An additional consequence of this change is that 100% availability rollouts when
the number of deployment replicas is equal to the number of nodes are no longer
possible even when using LoadBalancerService. See fb9851a for more details on
the rationale.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703943

### CODE REVIEW

**Comment by Miciah** [comment]
> An additional consequence of this change is that 100% availability rollouts are
> no longer possible even when using LoadBalancerService.

That needs to be qualified:100% availability rollouts _when the number of deployment replicas is equal to the number of nodes_, right?

**Comment by ironcladlou** [comment]
>That needs to be qualified:100% availability rollouts when the number of deployment replicas is equal to the number of nodes, right?

Good point, yes

**Comment by ironcladlou** [comment]
Fixed commit message

**Comment by ironcladlou** [comment]
Added a unit test.

**Comment by danehans** [comment]
`level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"`

/test e2e-aws-upgrade

**Comment by danehans** [comment]
`level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"`

/test e2e-aws

**Comment by ironcladlou** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/222/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator/839


```
=== RUN   TestIngressControllerUpdate
--- FAIL: TestIngressControllerUpdate (12.77s)
	operator_test.go:367: failed to reset IngressController: Operation cannot be fulfilled on ingresscontrollers.operator.openshift.io "default": the object has been modified; please apply your changes to the latest version and try again
	operator_test.go:381: failed to get recreated CA certificate configmap: timed out waiting for the condition
=== RUN   TestIngressControllerScale
--- PASS: TestIngressControllerScale (3.68s)
=== RUN   TestRouterCACertificate
--- FAIL: TestRouterCACertificate (11.59s)
	operator_test.go:595: failed to get CA certificate: timed out waiting for the condition
```

Is this is a flake in our operator's e2e test? Need to investigate this ASAP. @openshift/sig-network-edge 

/retest

**Comment by Miciah** [comment]
Most likely `TestRouterCACertificate` failed because `TestIngressControllerUpdate` left the default certificate with a custom certificate, which would cause the operator not to publish the `router-ca` configmap.  Not sure why `TestIngressControllerUpdate` is failing—it looks like it needs to do a get before it does an update, but I don't know why the test would have passed before but start failing now.

**Comment by Miciah** [comment]
Looks like the operator got restarted roughly around the time of that failure:
```
        {
            "apiVersion": "v1",
            "count": 1,
            "eventTime": null,
            "firstTimestamp": "2019-04-30T22:05:45Z",
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "Pod",
                "name": "router-default-797cd686b5-4vv5t",
                "namespace": "openshift-ingress",
                "resourceVersion": "18788",
                "uid": "143e8f89-6b94-11e9-8bd2-1277d3a978fc"
            },
            "kind": "Event",
            "lastTimestamp": "2019-04-30T22:05:45Z",
            "message": "Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_router-default-797cd686b5-4vv5t_openshift-ingress_143e8f89-6b94-11e9-8bd2-1277d3a978fc_0(72c1ff13062523ef7add98eb289cfaa76d0ed4d692f92ae0f9aacf3aac79344e): Multus: Err adding pod to network \"openshift-sdn\": cannot set \"openshift-sdn\" ifname to \"eth0\": no netns: failed to Statfs \"/proc/15779/ns/net\": no such file or directory",
            "metadata": {
                "creationTimestamp": "2019-04-30T22:05:45Z",
                "name": "router-default-797cd686b5-4vv5t.159a5fcaa73c5da7",
                "namespace": "openshift-ingress",
                "resourceVersion": "18916",
                "selfLink": "/api/v1/namespaces/openshift-ingress/events/router-default-797cd686b5-4vv5t.159a5fcaa73c5da7",
                "uid": "1a4ca1e4-6b94-11e9-8bd2-1277d3a978fc"
            },
            "reason": "FailedCreatePodSandBox",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "kubelet",
                "host": "ip-10-0-143-184.ec2.internal"
            },
            "type": "Warning"
        },
```

**Comment by Miciah** [comment]
level=error msg="\t* module.dns.aws_route53_zone.int: 1 error occurred:"
    level=error msg="\t* aws_route53_zone.int: error waiting for Route53 Hosted Zone (ZS8C4T9Y8Q8Q9) creation: timeout while waiting for state to become 'INSYNC' (last state: 'PENDING', timeout: 15m0s)"

/test e2e-aws-operator

**Pull request merged**
