### PR TITLE
[release-4.12] OCPBUGS-14454, OCPBUGS-14455: Handle mTLS CRLs, and fix accidental CRL duplication

### PR DESCRIPTION
**Pull request by rfredette**
Manual cherry pick & squash of #939 

---

Leave a stub of the CRL controller to clean up any existing configmaps. The stub controller will need to be removed in a future release

Use cluster-wide proxy for CRL downloads when available

Add a test with several test cases to test CRL management, and a test to test CRL updates

### CODE REVIEW

**Comment by frobware** [comment]
```console
=== CONT  TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-own-crl
    client_tls_test.go:987: exec ["cat" "/var/lib/haproxy/mtls/latest/crls.pem"] failed. error: command terminated with exit code 1
        stdout:
        
        stderr:
        cat: /var/lib/haproxy/mtls/latest/crls.pem: No such file or directory
```

This PR (and test) depends on https://github.com/openshift/router/pull/491.

**Comment by frobware** [comment]
/lgtm
/approve
/hold 
https://github.com/openshift/router/pull/491 needs to merge first.

**Comment by lihongan** [comment]
/unhold
since https://github.com/openshift/router/pull/491 get merged

**Comment by frobware** [comment]
"fail [github.com/openshift/origin/test/extended/util/disruption/backend_sampler_tester.go:185]: Jun  7 09:14:02.510: disruption/service-load-balancer-with-pdb connection/new was unreachable during disruption:  for at least 20s of 1h10m14s (maxAllowed=19s)"

/test e2e-aws-ovn-upgrade

**Comment by frobware** [comment]
e2e-aws-operator - Although TestAWSELBConnectionIdleTimeout which is bug https://issues.redhat.com/browse/OCPBUGS-13810, so did the new mTLS tests:

```console
        --- FAIL: TestAll/parallel/TestClientTLS (119.12s)
        --- FAIL: TestAll/parallel/TestCRLUpdate (357.86s)
            --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-own-crl (89.80s)
            --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-signers-crl (89.79s)
            --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-signers-crl-with-workaround (89.26s)
            --- FAIL: TestAll/parallel/TestCRLUpdate/many-CAs-with-signers-crl-workaround (88.98s)
        --- FAIL: TestAll/parallel/TestMTLSWithCRLs (486.06s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-own-crl (98.32s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-signers-crl (93.30s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-signers-crl-with-workaround (94.26s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/large-crl (94.71s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/multiple-intermediate-ca (95.40s)
```

/test e2e-aws-operator

**Comment by frobware** [comment]
e2e-aws-ovn-upgrade job failed after 4m28s.

/test e2e-aws-ovn-upgrade

**Comment by frobware** [comment]
e2e-aws-operator - job failed after 9m18s.

/test e2e-aws-operator

**Comment by frobware** [comment]
--- FAIL: TestAll/parallel/TestClientTLS (123.26s)

/test e2e-aws-operator

**Comment by rfredette** [comment]
```
         --- FAIL: TestAll/parallel/TestAWSELBConnectionIdleTimeout (406.29s) 
...
         --- FAIL: TestAll/parallel/TestClientTLS (117.61s) 
```
`TestAWSELBConnectionIdleTimeout` has passed in earlier runs, so it seems to be the flake from https://issues.redhat.com//browse/OCPBUGS-13810 . Likely `TestClientTLS` is a flake as well (fixed in #904 on the master branch), but since it's actually related to the code in this PR, I don't yet feel confident in that diagnosis.

/retest

**Comment by rfredette** [comment]
I cherry-picked #904 onto these changes and opened #945 to test, and while `e2e-aws-operator` failed must-gather, the actual test suite passed (prow isn't showing the test suite logs, but they are in the artifacts [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/945/pull-ci-openshift-cluster-ingress-operator-release-4.12-e2e-aws-operator/1666525480993427456/artifacts/e2e-aws-operator/test/build-log.txt)). Since the only difference between this and #945 is the `TestClientTLS` fix, I'm confident that the `TestClientTLS` failures are unrelated to the changes in this PR.

**Comment by Miciah** [comment]
[e2e-aws-operator failed again](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/941/pull-ci-openshift-cluster-ingress-operator-release-4.12-e2e-aws-operator/1666539533698600960) on `TestAWSELBConnectionIdleTimeout` and `TestClientTLS`.
/override ci/prow/e2e-aws-operator
based on https://github.com/openshift/cluster-ingress-operator/pull/941#issuecomment-1581520941.

**Pull request merged**
