### PR TITLE
OCPBUGS-23742: Bump controller-runtime to v0.16.3

### PR DESCRIPTION
**Pull request by Miciah**
#### Remove `SourceConfigMapNamespace` const

Remove the `SourceConfigMapNamespace` const in favor of the more descriptively named `GlobalUserSpecifiedConfigNamespace` const, which has the same value.

Follow-up to #588.

* `pkg/operator/controller/names.go` (`SourceConfigMapNamespace`): Delete const.
* `pkg/operator/operator.go` (`New`): Delete `SourceConfigMapNamespace` from the manager options, which already includes `GlobalUserSpecifiedConfigNamespace`.

#### Bump controller-runtime to v0.16.3

Bump the vendored sigs.k8s.io/controller-runtime package to v0.16.3, the latest release, which uses the k8s.io/* v0.28.3 packages.

    go get sigs.k8s.io/controller-runtime@v0.16.3
    go mod tidy
    go mod vendor

* `go.mod`: Bump.
* `go.sum`: Regenerate.
* `pkg/operator/operator.go` (`New`): Update to use the new `DefaultNamespaces` field instead of `Namespaces`, which has been removed from the manager options.
* `pkg/operator/controller/dns/controller_test.go` (`Test_customCABundle`): Update to use `NewClientBuilder` instead of `NewFakeClientWithScheme`, which has been removed from controller-runtime.
* `vendor/*: Regenerate`.

### CODE REVIEW

**Comment by Miciah** [comment]
[e2e-gcp-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/1001/pull-ci-openshift-cluster-ingress-operator-master-e2e-gcp-operator/1729302660399501312) because `TestUnmanagedDNSToManagedDNSInternalIngressController` failed, which is a known issue.  
/override ci/prow/e2e-gcp-operator

**Comment by gcs278** [comment]
Straightforward change. I reviewed the [breaking changes](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.16.0) and nothing particular pops out at me.
/lgtm
/approve

**Comment by gcs278** [comment]
@Miciah looks like your override was ignored or overridden

**Pull request merged**
