### PR TITLE
OCPBUGS-43095: Add alert for RFC 7230 violation in Transfer-Encoding headers

### PR DESCRIPTION
**Pull request by frobware**
This commit introduces the `DuplicateTransferEncodingHeadersDetected` alert, which triggers when a backend server responds with duplicate Transfer-Encoding headers, violating RFC 7230.

Cluster administrators can use this alert to identify affected backends before upgrading to OpenShift 4.14, which includes HAProxy 2.6. In OpenShift 4.14 and later, HAProxy 2.6+ strictly enforces RFC 7230 compliance, resulting in responses being rejected with 502 Bad Gateway errors for affected routes.

Administrators should investigate and address the issue by working with the teams responsible for the affected services to correct the backend behaviour. Once the issue is resolved and the backend no longer violates RFC 7230, the alert can be silenced to confirm the resolution.

For more details on identifying and resolving this issue, refer to Red Hat Solution 7055002: https://access.redhat.com/solutions/7055002

Related PRs:
- https://github.com/openshift/cluster-ingress-operator/pull/1150
- https://github.com/openshift/router/pull/626

### CODE REVIEW

**Comment by frobware** [comment]
Internal slack discussion: https://redhat-internal.slack.com/archives/CCH60A77E/p1729692338637469?thread_ts=1729076992.769909&cid=CCH60A77E

**Comment by frobware** [comment]
To test out the alerts I have used https://github.com/frobware/haproxy-hacks/tree/master/OCPBUGS-40850.

```sh
% oc new-project ocpbugs40850
% ./setup.bash   
% ./check-routes.bash  
```

Once the metrics have been scraped, the alerts fire.

**Comment by Miciah** [comment]
Thanks!
/approve
/lgtm

**Comment by frobware** [comment]
/hold

@Miciah thanks for the labels. Just going to hang fire for @wking's testing/observations/et al.

**Comment by Miciah** [comment]
This is a low-risk change that only adds a Prometheus alerting rule to cluster-ingress-operator's CVO manifests.  The new rule is based on the new `haproxy_backend_duplicate_te_header_total` metric that was added in https://github.com/openshift/router/pull/626.  The new alerting rule only fires if some backend server for some route sends invalid transfer-encoding response headers.  The alert references a KCS article that explains how the cluster-admin can act on the alert or silence it.  

/label backport-risk-assessed

**Comment by wking** [comment]
I tested a `launch [4.13.0-0.ci](http://4.13.0-0.ci/),openshift/cluster-ingress-operator#1161 aws` Cluster Bot cluster via [Andrew's lovely process][1], and here's a screenshot of the bottom part of alert page with the linked run book:

Screenshot 2024-10-24 11 23 04 AM

And here's the alert going away once I removed the namespace and rolled the router pods:

```console
$ oc delete namespace ocpbugs40850
namespace "ocpbugs40850" deleted
$ oc -n openshift-ingress delete -l ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default pods
pod "router-default-5c87985696-bcn8f" deleted
pod "router-default-5c87985696-ndw6h" deleted
```

Screenshot 2024-10-24 11 27 13 AM

Screenshot 2024-10-24 11 29 26 AM

But "has any of the currently-running router containers ever seen one of these?" is a pretty solid guard, so:

/hold cancel

[1]: https://github.com/openshift/cluster-ingress-operator/pull/1161#issuecomment-2435337570

**Pull request merged**
