### PR TITLE
operator: set default publishing strategy to HostNetwork

### PR DESCRIPTION
**Pull request by abhinavdahiya**
Follow up to https://github.com/openshift/api/pull/251

### CODE REVIEW

**Comment by ironcladlou** [comment]
Thanks!

/lgtm
/approve

**Comment by Miciah** [comment]
/lgtm

    level=error msg="\t* module.vpc.aws_route.igw_route: 1 error occurred:"
    level=error msg="\t* aws_route.igw_route: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"

/test e2e-aws-operator

**Comment by Miciah** [comment]
=== RUN   TestClusterIngressControllerCreateDelete
    --- FAIL: TestClusterIngressControllerCreateDelete (43.10s)
    	operator_test.go:174: failed to finalize IngressController openshift-ingress-operator/test: timed out waiting for the condition

Problem is `TestClusterIngressControllerCreateDelete` tried to delete the LB service before it was provisioned, and the finalization logic gets tripped up.  We need to fix the finalization logic.  However, this PR is good to merge if it can get past the test flake.

/test e2e-aws-operator

**Comment by Miciah** [comment]
level=error msg="1 error occurred:"
    level=error msg="\t* module.bootstrap.aws_security_group.bootstrap (destroy): 1 error occurred:"
    level=error msg="\t* aws_security_group.bootstrap: timeout while waiting for state to become 'success' (timeout: 10m0s)"

/test e2e-aws-operator

**Pull request merged**
