### PR TITLE
Bug 2092042: Bump vendored k8s libraries to 1.24

### PR DESCRIPTION
**Pull request by rfredette**
Update `k8s.io/api`, `k8s.io/apimachinery`, `k8s.io/apiserver`, and `k8s.io/client-go` to v0.24.0, which maps to the overall 1.24 kubernetes release. Also bump `github.com/openshift/library-go` for its 1.24 support. All other vendor updates were automatically included as a part of these updates.

### CODE REVIEW

**Comment by rfredette** [comment]
```
        --- FAIL: TestAll/parallel/TestHAProxyTimeoutsRejection (40.23s)
        --- FAIL: TestAll/parallel/TestHAProxyTimeouts (40.20s) 
```
e2e-aws-operator failed on a flake I'm working on fixing separately.

/retest-required

**Comment by frobware** [comment]
Similar to https://github.com/openshift/cluster-dns-operator/pull/328, we should require Go 1.18 in go.mod and CI build image references (Dockerfile, .ci-operator.yaml).

**Comment by frobware** [comment]
It wasn't clear to me what issues you ran into with commits:
- 9b904f39ec0725f22b78425b7d0130d77334e005
- 27696934a879a8b4c47cb1ffe06740d3529d60dd

I attempted to reproduce your steps in https://github.com/openshift/cluster-ingress-operator/pull/791 and didn't see or understand why we had to drop `controller-tools`.

Looking at the diffs between this commit and PR #791 I see:

```console
$ gh pr list | grep 1.24
768	Bug 2092042: Bump vendored k8s libraries to 1.24	rfredette:k8s-1.24	OPEN

$ gh pr checkout -f 768
Switched to branch 'k8s-1.24'

$ git rebase upstream/master 
Successfully rebased and updated refs/heads/k8s-1.24.
```

[ Some of the diffs will be different because my PR also requires Go 1.18. ]

Looking at Go module differences:

```console
$ git diff k8s-1.24 go.mod
@@ -1,6 +1,6 @@
 module github.com/openshift/cluster-ingress-operator
 
-go 1.17
+go 1.18
 
 require (
        github.com/Azure/azure-sdk-for-go v30.0.0+incompatible
@@ -17,7 +17,7 @@ require (
        github.com/google/go-cmp v0.5.6
        github.com/kevinburke/go-bindata v3.11.0+incompatible
        github.com/openshift/api v0.0.0-20220525145417-ee5b62754c68
-       github.com/openshift/library-go v0.0.0-20220525173854-9b950a41acdc
+       github.com/openshift/library-go v0.0.0-20220622115547-84d884f4c9f6
        github.com/pkg/errors v0.9.1
        github.com/prometheus/client_golang v1.12.1
        github.com/spf13/cobra v1.4.0
@@ -35,6 +35,7 @@ require (
        k8s.io/client-go v0.24.0
        k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
        sigs.k8s.io/controller-runtime v0.12.0
+       sigs.k8s.io/controller-tools v0.4.1
 )
 
 require (
@@ -64,6 +65,7 @@ require (
        github.com/go-playground/locales v0.13.0 // indirect
        github.com/go-playground/universal-translator v0.17.0 // indirect
        github.com/go-stack/stack v1.8.0 // indirect
+       github.com/gobuffalo/flect v0.2.0 // indirect
        github.com/gogo/protobuf v1.3.2 // indirect
        github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
        github.com/golang/protobuf v1.5.2 // indirect
@@ -100,12 +102,14 @@ require (
        go.uber.org/atomic v1.7.0 // indirect
        go.uber.org/multierr v1.6.0 // indirect
        golang.org/x/crypto v0.0.0-20220214200702-86341886e292 // indirect
+       golang.org/x/mod v0.6.0-dev.0.20220106191415-9b9b3d81d5e3 // indirect
        golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd // indirect
        golang.org/x/oauth2 v0.0.0-20220411215720-9780585627b5 // indirect
        golang.org/x/sys v0.0.0-20220209214540-3681064d5158 // indirect
        golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 // indirect
        golang.org/x/text v0.3.7 // indirect
        golang.org/x/time v0.0.0-20220210224613-90d013bbcef8 // indirect
+       golang.org/x/tools v0.1.10-0.20220218145154-897bd77cd717 // indirect
        golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
        gomodules.xyz/jsonpatch/v2 v2.2.0 // indirect
        google.golang.org/appengine v1.6.7 // indirect
```


And the full diff:

```console
git diff --stat k8s-1.24
 .ci-operator.yaml                                  |    2 +-
 Dockerfile                                         |    4 +-
 go.mod                                             |    8 +-
 go.sum                                             |   64 +-
 test/e2e/operator_test.go                          |   10 +-
 tools/tools.go                                     |    1 +
 vendor/github.com/gobuffalo/flect/.gitignore       |   29 +
 .../github.com/gobuffalo/flect/.gometalinter.json  |    3 +
 vendor/github.com/gobuffalo/flect/LICENSE          |   21 +
 vendor/github.com/gobuffalo/flect/Makefile         |   61 +
 vendor/github.com/gobuffalo/flect/README.md        |   36 +
 vendor/github.com/gobuffalo/flect/SHOULDERS.md     |   10 +
 vendor/github.com/gobuffalo/flect/acronyms.go      |  152 +++
 .../github.com/gobuffalo/flect/azure-pipelines.yml |   71 +
 vendor/github.com/gobuffalo/flect/azure-tests.yml  |   19 +
 vendor/github.com/gobuffalo/flect/camelize.go      |   48 +
 vendor/github.com/gobuffalo/flect/capitalize.go    |   27 +
 vendor/github.com/gobuffalo/flect/custom_data.go   |   83 ++
 vendor/github.com/gobuffalo/flect/dasherize.go     |   34 +
 vendor/github.com/gobuffalo/flect/flect.go         |   43 +
 vendor/github.com/gobuffalo/flect/humanize.go      |   35 +
 vendor/github.com/gobuffalo/flect/ident.go         |  106 ++
 vendor/github.com/gobuffalo/flect/lower_upper.go   |   13 +
 vendor/github.com/gobuffalo/flect/ordinalize.go    |   43 +
 vendor/github.com/gobuffalo/flect/pascalize.go     |   25 +
 vendor/github.com/gobuffalo/flect/plural_rules.go  |  284 ++++
 vendor/github.com/gobuffalo/flect/pluralize.go     |   49 +
 vendor/github.com/gobuffalo/flect/rule.go          |   10 +
 .../github.com/gobuffalo/flect/singular_rules.go   |   23 +
 vendor/github.com/gobuffalo/flect/singularize.go   |   47 +
 vendor/github.com/gobuffalo/flect/titleize.go      |   30 +
 vendor/github.com/gobuffalo/flect/underscore.go    |   34 +
 vendor/github.com/gobuffalo/flect/version.go       |    4 +
 vendor/golang.org/x/mod/LICENSE                    |   27 +
 vendor/golang.org/x/mod/PATENTS                    |   22 +
 vendor/golang.org/x/mod/semver/semver.go           |  401 ++++++
 vendor/golang.org/x/sys/execabs/execabs.go         |  102 ++
 vendor/golang.org/x/tools/AUTHORS                  |    3 +
 vendor/golang.org/x/tools/CONTRIBUTORS             |    3 +
 vendor/golang.org/x/tools/LICENSE                  |   27 +
 vendor/golang.org/x/tools/PATENTS                  |   22 +
 .../x/tools/go/gcexportdata/gcexportdata.go        |  146 +++
 .../golang.org/x/tools/go/gcexportdata/importer.go |   73 ++
 .../x/tools/go/internal/gcimporter/bexport.go      |  851 ++++++++++++
 .../x/tools/go/internal/gcimporter/bimport.go      | 1053 +++++++++++++++
 .../x/tools/go/internal/gcimporter/exportdata.go   |   99 ++
 .../x/tools/go/internal/gcimporter/gcimporter.go   | 1084 ++++++++++++++++
 .../x/tools/go/internal/gcimporter/iexport.go      | 1007 ++++++++++++++
 .../x/tools/go/internal/gcimporter/iimport.go      |  875 +++++++++++++
 .../tools/go/internal/gcimporter/newInterface10.go |   22 +
 .../tools/go/internal/gcimporter/newInterface11.go |   14 +
 .../tools/go/internal/gcimporter/support_go117.go  |   16 +
 .../tools/go/internal/gcimporter/support_go118.go  |   23 +
 .../x/tools/go/internal/packagesdriver/sizes.go    |   49 +
 vendor/golang.org/x/tools/go/packages/doc.go       |  221 ++++
 vendor/golang.org/x/tools/go/packages/external.go  |  101 ++
 vendor/golang.org/x/tools/go/packages/golist.go    | 1099 ++++++++++++++++
 .../x/tools/go/packages/golist_overlay.go          |  575 ++++++++
 .../x/tools/go/packages/loadmode_string.go         |   57 +
 vendor/golang.org/x/tools/go/packages/packages.go  | 1244 ++++++++++++++++++
 vendor/golang.org/x/tools/go/packages/visit.go     |   59 +
 .../x/tools/internal/event/core/event.go           |   85 ++
 .../x/tools/internal/event/core/export.go          |   70 +
 .../golang.org/x/tools/internal/event/core/fast.go |   77 ++
 vendor/golang.org/x/tools/internal/event/doc.go    |    7 +
 vendor/golang.org/x/tools/internal/event/event.go  |  127 ++
 .../golang.org/x/tools/internal/event/keys/keys.go |  564 ++++++++
 .../x/tools/internal/event/keys/standard.go        |   22 +
 .../x/tools/internal/event/label/label.go          |  215 +++
 .../x/tools/internal/gocommand/invoke.go           |  281 ++++
 .../x/tools/internal/gocommand/vendor.go           |  107 ++
 .../x/tools/internal/gocommand/version.go          |   51 +
 .../x/tools/internal/packagesinternal/packages.go  |   28 +
 .../x/tools/internal/typeparams/common.go          |  180 +++
 .../x/tools/internal/typeparams/enabled_go117.go   |   12 +
 .../x/tools/internal/typeparams/enabled_go118.go   |   15 +
 .../x/tools/internal/typeparams/normalize.go       |  216 ++++
 .../x/tools/internal/typeparams/termlist.go        |  172 +++
 .../tools/internal/typeparams/typeparams_go117.go  |  197 +++
 .../tools/internal/typeparams/typeparams_go118.go  |  151 +++
 .../x/tools/internal/typeparams/typeterm.go        |  170 +++
 .../x/tools/internal/typesinternal/errorcode.go    | 1368 ++++++++++++++++++++
 .../internal/typesinternal/errorcode_string.go     |  153 +++
 .../x/tools/internal/typesinternal/types.go        |   52 +
 .../x/tools/internal/typesinternal/types_118.go    |   19 +
 vendor/modules.txt                                 |   39 +-
 vendor/sigs.k8s.io/controller-tools/LICENSE        |  201 +++
 .../controller-tools/cmd/controller-gen/main.go    |  263 ++++
 .../sigs.k8s.io/controller-tools/pkg/crd/conv.go   |  122 ++
 .../controller-tools/pkg/crd/desc_visitor.go       |   78 ++
 vendor/sigs.k8s.io/controller-tools/pkg/crd/doc.go |   63 +
 .../controller-tools/pkg/crd/flatten.go            |  441 +++++++
 vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go |  351 +++++
 .../controller-tools/pkg/crd/known_types.go        |  128 ++
 .../controller-tools/pkg/crd/markers/crd.go        |  318 +++++
 .../controller-tools/pkg/crd/markers/doc.go        |   46 +
 .../controller-tools/pkg/crd/markers/package.go    |   40 +
 .../controller-tools/pkg/crd/markers/register.go   |   83 ++
 .../controller-tools/pkg/crd/markers/topology.go   |  155 +++
 .../controller-tools/pkg/crd/markers/validation.go |  391 ++++++
 .../pkg/crd/markers/zz_generated.markerhelp.go     |  430 ++++++
 .../sigs.k8s.io/controller-tools/pkg/crd/parser.go |  237 ++++
 .../sigs.k8s.io/controller-tools/pkg/crd/schema.go |  427 ++++++
 .../controller-tools/pkg/crd/schema_visitor.go     |  131 ++
 .../sigs.k8s.io/controller-tools/pkg/crd/spec.go   |  174 +++
 .../pkg/crd/zz_generated.markerhelp.go             |   57 +
 .../controller-tools/pkg/deepcopy/doc.go           |   23 +
 .../controller-tools/pkg/deepcopy/gen.go           |  304 +++++
 .../controller-tools/pkg/deepcopy/traverse.go      |  829 ++++++++++++
 .../pkg/deepcopy/zz_generated.markerhelp.go        |   45 +
 .../sigs.k8s.io/controller-tools/pkg/genall/doc.go |   58 +
 .../controller-tools/pkg/genall/genall.go          |  215 +++
 .../controller-tools/pkg/genall/help/doc.go        |   23 +
 .../controller-tools/pkg/genall/help/pretty/doc.go |   30 +
 .../pkg/genall/help/pretty/help.go                 |  171 +++
 .../pkg/genall/help/pretty/print.go                |  304 +++++
 .../pkg/genall/help/pretty/table.go                |   64 +
 .../controller-tools/pkg/genall/help/sort.go       |  106 ++
 .../controller-tools/pkg/genall/help/types.go      |  215 +++
 .../controller-tools/pkg/genall/input.go           |   37 +
 .../controller-tools/pkg/genall/options.go         |  192 +++
 .../controller-tools/pkg/genall/output.go          |  160 +++
 .../pkg/genall/zz_generated.markerhelp.go          |   89 ++
 .../sigs.k8s.io/controller-tools/pkg/loader/doc.go |   60 +
 .../controller-tools/pkg/loader/errors.go          |   67 +
 .../controller-tools/pkg/loader/loader.go          |  360 ++++++
 .../controller-tools/pkg/loader/paths.go           |   32 +
 .../controller-tools/pkg/loader/refs.go            |  268 ++++
 .../controller-tools/pkg/loader/visit.go           |   81 ++
 .../controller-tools/pkg/markers/collect.go        |  422 ++++++
 .../controller-tools/pkg/markers/doc.go            |  113 ++
 .../controller-tools/pkg/markers/help.go           |   81 ++
 .../controller-tools/pkg/markers/parse.go          |  923 +++++++++++++
 .../controller-tools/pkg/markers/reg.go            |  153 +++
 .../controller-tools/pkg/markers/regutil.go        |   36 +
 .../controller-tools/pkg/markers/zip.go            |  191 +++
 .../controller-tools/pkg/rbac/parser.go            |  267 ++++
 .../pkg/rbac/zz_generated.markerhelp.go            |   77 ++
 .../controller-tools/pkg/schemapatcher/gen.go      |  513 ++++++++
 .../pkg/schemapatcher/internal/yaml/convert.go     |   61 +
 .../pkg/schemapatcher/internal/yaml/nested.go      |   87 ++
 .../pkg/schemapatcher/internal/yaml/set.go         |   80 ++
 .../pkg/schemapatcher/zz_generated.markerhelp.go   |   45 +
 .../controller-tools/pkg/version/version.go        |   49 +
 .../controller-tools/pkg/webhook/conv.go           |   44 +
 .../controller-tools/pkg/webhook/parser.go         |  426 ++++++
 .../pkg/webhook/zz_generated.markerhelp.go         |   96 ++
 147 files changed, 26562 insertions(+), 53 deletions(-)
```

**Comment by frobware** [comment]
I dropped `controller-tools` in https://github.com/openshift/cluster-ingress-operator/pull/791/commits/216d1700837f1632cb39dbd8352eb4574350225f.

The diff looks fine now: 

```console
$ git diff k8s-1.24 go.mod
diff --git a/go.mod b/go.mod
index 2981888b..a5746dad 100644
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,6 @@
 module github.com/openshift/cluster-ingress-operator
 
-go 1.17
+go 1.18
 
 require (
        github.com/Azure/azure-sdk-for-go v30.0.0+incompatible
@@ -17,7 +17,7 @@ require (
        github.com/google/go-cmp v0.5.6
        github.com/kevinburke/go-bindata v3.11.0+incompatible
        github.com/openshift/api v0.0.0-20220525145417-ee5b62754c68
-       github.com/openshift/library-go v0.0.0-20220525173854-9b950a41acdc
+       github.com/openshift/library-go v0.0.0-20220622115547-84d884f4c9f6
        github.com/pkg/errors v0.9.1
        github.com/prometheus/client_golang v1.12.1
        github.com/spf13/cobra v1.4.0
```

**Review by frobware — COMMENTED** [review]
LGTM. I tried your steps in https://github.com/openshift/cluster-ingress-operator/pull/791 and get an expected diff (for using Go 1.18). 

Omitting /lgtm until we conclude whether this PR should bump to Go 1.18 and also update the image references to use `rhel-8-release-golang-1.18-openshift-4.11`? I think it should.

**Pull request merged**
