### PR TITLE
OCPBUGS-43412:  Bump to k8s.io v0.31.1 (and deps)

### PR DESCRIPTION
**Pull request by EmilienM**
Bump the operator's vendored k8s.io/* packages to v0.31.1; bump its
vendored sigs.k8s.io/controller-runtime package to v0.19.0, the latest
release, which uses the k8s.io/* v0.31.1 packages.
This also bumps prometheus/common which needs to be updated to work with
k8s v0.31.1.

    go get k8s.io/api@v0.31.1 k8s.io/apimachinery@v0.31.1 k8s.io/apiextensions-apiserver@v0.31.1 k8s.io/apiserver@v0.31.1 k8s.io/client-go@v0.31.1 sigs.k8s.io/controller-runtime@v0.19.0 github.com/prometheus/common@v0.55.0
    go mod tidy
    go mod vendor

Update calls to route-metrics to adapt to breaking changes in
controller-runtime.  Namely, RateLimiter workqueue now uses
`NewTypedMaxOfRateLimiter` instead of ``NewMaxOfRateLimiter`.

This commit is related to [RFE-6242](https://issues.redhat.com//browse/RFE-6242).

https://issues.redhat.com/browse/RFE-6242

* go.mod: Bump.
* go.sum: Regenerate.
* pkg/operator/controller/route-metrics/controller.go: Update for the
  new controller-runtime.
* vendor/*: Regenerate.

### CODE REVIEW

**Comment by Miciah** [comment]
Thanks!  Would you mind doing the following?

- Squash the commits so that `make test verify` will succeed for every commit in the history.
- Add a reference to https://issues.redhat.com/browse/OCPBUGS-43412 in the commit message, and add `OCPBUGS-43412: ` to the PR title.
- Document the commands that you used in order to do the bump in the commit message.

For an example commit message from another k8s.io/* and controller-runtime vendor bump, see https://github.com/openshift/cluster-dns-operator/commit/dee78adcfe8dd3a6cfc9b35b9ee0791ad93357b1.

**Comment by Miciah** [comment]
I'm guessing that the openshift/api and k8s.io/* bumps cannot be done as separate bumps.  Could you mention that in the commit message, and mention that the openshift/api bump brings in the new `floatingip` field?

**Comment by EmilienM** [comment]
> Would you mind putting the information that you put in the PR description into the commit message? Also, please include the exact commands that you used to do the vendor bump. See [openshift/cluster-dns-operator@dee78ad](https://github.com/openshift/cluster-dns-operator/commit/dee78adcfe8dd3a6cfc9b35b9ee0791ad93357b1) for an example.

done

**Comment by alebedev87** [comment]
LGTM

/approve

**Comment by EmilienM** [comment]
@alebedev87 thanks for your approval. I was asked on Slack by @gcs278 to remove the openshift/api bump which will be done via another PR.

**Comment by EmilienM** [comment]
@gcs278 @Miciah I'll let you LGTM it.

Thanks

**Comment by gcs278** [comment]
/lgtm

Want to let @miciah have a chance since he is the official reviewer
/hold

**Comment by Miciah** [comment]
Still reviewing the vendor changes.  

@EmilienM, could you update the commit message to reference OCPBUGS-43412 rather than RFE-6242?

**Comment by EmilienM** [comment]
@Miciah done

**Comment by Miciah** [comment]
[The ingress-operator logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1156/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-gatewayapi/1853446463451828224/artifacts/e2e-aws-gatewayapi/gather-extra/artifacts/pods/openshift-ingress-operator_ingress-operator-55fd7cf64c-r8knr_ingress-operator.log) from [the e2e-aws-gatewayapi job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1156/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-gatewayapi/1853446463451828224) has a lot of log lines like the following:
```text
2024-11-04T15:29:37.595Z	ERROR	operator.init	controller/controller.go:263	Reconciler error	{"controller": "gatewayclass_controller", "object": {"name":"openshift-default"}, "namespace": "", "name": "openshift-default", "reconcileID": "b3023e1f-031c-4986-9bbe-67f6549a27cb", "error": "failed to get ServiceMeshControlPlane openshift-ingress/openshift-gateway: failed to get restmapping: no matches for kind \"ServiceMeshControlPlane\" in version \"maistra.io/v2\"", "errorCauses": [{"error": "failed to get ServiceMeshControlPlane openshift-ingress/openshift-gateway: failed to get restmapping: no matches for kind \"ServiceMeshControlPlane\" in version \"maistra.io/v2\""}]}
```

However, I see similar log lines in e2e-aws-gatewayapi job runs for other PRs, so I believe that this is an unrelated issue.  

@candita, is this a known issue?  I didn't find anything with a quick search in Jira.  


---

One interesting change in the controller-runtime bump is that controller-runtime now recovers panics from `Reconcile` by default: https://github.com/openshift/cluster-ingress-operator/blob/eb48cc2e9135cc567e5824e35d279194c2628b53/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go#L97-L103

The controller-runtime bump also adds a metric for panics: https://github.com/openshift/cluster-ingress-operator/blob/eb48cc2e9135cc567e5824e35d279194c2628b53/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics/metrics.go#L49-L54

As a follow-up, it would make sense to have an E2E test that verifies that `controller_runtime_reconcile_panics_total` is zero at the end of the test run.

---

The changes look fine.  Thanks for your effort and patience!

/approve
/lgtm

**Pull request merged**
