### PR TITLE
AUTH-133: assets: comply to pod security

### PR DESCRIPTION
**Pull request by s-urbaniak**
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:

```
{
  "objectRef": "openshift-ingress-canary/pods/",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": runAsNonRoot != true (pod or container \"serve-healthcheck-canary\" must set securityContext.runAsNonRoot=true)"
}
{
  "objectRef": "openshift-ingress/pods/",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"router\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"router\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"router\" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container \"router\" must set securityContext.seccompProfile.type to \"RuntimeDefault\" or \"Localhost\")"
}
```

/cc @stlaz

### CODE REVIEW

**Comment by Miciah** [comment]
/approve
/lgtm
/hold
We'll need to add update logic in `pkg/operator/controller/canary/daemonset.go` for clusters that are upgraded from 4.10 to 4.11.  If you want to merge this PR as-is, we can do that, but there is that follow-up work needed.

**Comment by wking** [comment]
Looks like #760 is up with a carry of this PR and looking for review?

**Comment by Miciah** [comment]
> Looks like #760 is up with a carry of this PR and looking for review?

Yup, #760 includes the commit from this PR plus a commit with the needed update logic for 4.10→4.11 upgrades.

**Comment by s-urbaniak** [comment]
in favor of https://github.com/openshift/cluster-ingress-operator/pull/760

**Pull request closed without merging**
