### PR TITLE
NE-1490: update to go v1.20

### PR DESCRIPTION
**Pull request by candita**
Update to go v1.20

### CODE REVIEW

**Comment by candita** [comment]
Interesting new failure:

> === NAME  TestAll/parallel/TestRouteMetricsControllerOnlyRouteSelector
>     route_metrics_test.go:386: failed to update route: Operation cannot be fulfilled on routes.route.openshift.io "route-rs-foo-label": the object has been modified; please apply your changes to the latest version and try again

/test e2e-gcp-operator

**Comment by candita** [comment]
/test e2e-aws-ovn-single-node

> level=info msg=Cluster operator insights SCAAvailable is False with Forbidden: Failed to pull SCA certs from https://api.openshift.com/api/accounts_mgmt/v1/certificates: OCM API https://api.openshift.com/api/accounts_mgmt/v1/certificates returned HTTP 403: {"code":"ACCT-MGMT-11","href":"/api/accounts_mgmt/v1/errors/11","id":"11","kind":"Error","operation_id":"e1d319f7-3766-4d00-91cc-d601a91bb6ab","reason":"Account with ID 2DUeKzzTD9ngfsQ6YgkzdJn1jA4 denied access to perform create on Certificate with HTTP call POST /api/accounts_mgmt/v1/certificates"}
> ...
> level=error msg=Cluster initialization failed because one or more operators are not functioning properly.
> ...
> level=error msg=failed to initialize the cluster: Cluster operator console is not available
>

**Comment by candita** [comment]
> openshift cluster install failed with cluster creation

/test e2e-aws-ovn-single-node

**Comment by candita** [comment]
Timed out after 4 hours:

> [36mINFO[0m[2024-01-04T23:59:11Z] Running step e2e-aws-ovn-single-node-single-node-e2e-test. 
> {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2024-01-05T03:01:22Z"}
> [36mINFO[0m[2024-01-05T03:01:22Z] Received signal.                              [36msignal[0m=interrupt
> 

/test e2e-aws-ovn-single-node

**Comment by Miciah** [comment]
Thanks!  
/approve
/lgtm

I was curious whether/why Go 1.20 was required.  In case anyone else is curious:
```text
% ed Makefile
1625
/GO=
GO=GO111MODULE=on GOFLAGS=-mod=vendor go
s/$/1.19
GO=GO111MODULE=on GOFLAGS=-mod=vendor go1.19
wq
1629
% make test verify
go generate ./pkg/manifests
CGO_ENABLED=1 GO111MODULE=on GOFLAGS=-mod=vendor go1.19 test ./...
# sigs.k8s.io/controller-runtime/pkg/cache
vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go:412:58: fields.Selector does not implement comparable
vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go:442:20: fields.Selector does not implement comparable
note: module requires Go 1.20
```

**Pull request merged**
