### PR TITLE
Delete logic to publish router-ca configmap

### LINKED ISSUE #378: Remove router-ca
Based on https://github.com/openshift/enhancements/blob/master/enhancements/network/default-ingress-cert-configmap.md#upgrade--downgrade-strategy we can now stop publishing the `router-ca` ConfigMap

### PR DESCRIPTION
**Pull request by Miciah**
Delete logic to publish the `router-ca` configmap in the `openshift-config-managed` namespace; the `router-ca` configmap is superseded by the `default-ingress-cert` configmap in the same namespace.

Follow-up to #331.  Fixes #378.

* `pkg/operator/controller/certificate/controller.go` (`New`): Delete initialization of `cache`; only the client is still needed after this commit.
(`reconciler`): Delete `cache` field.
(`Reconcile`): Delete call to `ensureRouterCAConfigMap`.
* `pkg/operator/controller/certificate/publish_ca.go` (`ensureRouterCAConfigMap`, `desiredRouterCAConfigMap`, `shouldPublishRouterCA`): Delete.
* `pkg/operator/controller/certificate/publish_ca_test.go`: Delete file.
(`TestShouldPublishRouterCA`): Delete test.
* `pkg/operator/controller/names.go` (`RouterCAConfigMapName`): Delete function.
* `test/e2e/operator_test.go` (`TestUpdateDefaultIngressController`): Delete checks for the `router-ca` configmap.
(`TestRouterCACertificate`): Rename...
(`TestDefaultIngressCertificate`): ...to this.  Check for the `default-ingress-cert` configmap instead of the `router-ca` configmap.

----

@deads2k, @benjaminapetersen, [the plan](https://github.com/openshift/enhancements/blob/master/enhancements/network/default-ingress-cert-configmap.md#upgrade--downgrade-strategy) was to stop publishing `router-ca` in 4.4.0, so this change is past due; is it safe to do so yet?  Let's see whether CI passes...

### CODE REVIEW

**Comment by Miciah** [comment]
OpenShift Console is failing to get a token from the OAuth issuer endpoint because of an "x509: certificate signed by unknown authority" error.

**Comment by ironcladlou** [comment]
@Miciah 
>OpenShift Console is failing to get a token from the OAuth issuer endpoint because of an "x509: certificate signed by unknown authority" error.

You suspect that's because of this change?

**Comment by Miciah** [comment]
> > OpenShift Console is failing to get a token from the OAuth issuer endpoint because of an "x509: certificate signed by unknown authority" error.
> 
> You suspect that's because of this change?

https://github.com/openshift/console-operator/pull/403 should fix it.

**Comment by stlaz** [comment]
Installer still seems to be adding the router-ca to the kubeconfig - https://github.com/openshift/installer/blob/406e9079e5430950b7c256e0ccf98d0e625f8d9d/cmd/openshift-install/create.go#L196-L243

**Comment by Miciah** [comment]
Thanks!  I made https://github.com/openshift/installer/pull/3380 to update the installer to use `default-ingress-cert`.

**Comment by Miciah** [comment]
/retest
now that https://github.com/openshift/console-operator/pull/403 has merged.

**Comment by danehans** [comment]
`failed to acquire lease: resources not found`
/retest

**Pull request merged**
