### PR TITLE
OCPBUGS-3404: Bump openshift/api for matchExpressions doc fix

### PR DESCRIPTION
**Pull request by Miciah**
Bump to https://github.com/openshift/api/commit/20f563788affca208ac779a0fd2ca031950cee01 to fix the godoc for the `IngressController.spec.nodePlacement.nodeSelector` API field.

Using the `spec.nodePlacement.nodeSelector.matchExpressions` field does not work.  We cannot feasibly fix it at this time, and removing the API field would be a breaking change.  Instead, this PR updates the API field godoc to warn that specifying `matchExpressions` will not work.

* `go.mod`: Bump openshift/api.
* `go.sum`:
* `manifests/00-custom-resource-definition.yaml`:
* `pkg/manifests/bindata.go`:
* `vendor/github.com/openshift/api/*`:
* `vendor/modules.txt`: Regenerate.

### CODE REVIEW

**Comment by candita** [comment]
> Lots of changes in vendor are because there were lots of changes to code gen. https://github.com/openshift/api/commits/master?after=f2fbb1d1cd5e056d4c3342b823c02ee11a161a81+69&branch=master&qualified_name=refs%2Fheads%2Fmaster

/approved

**Comment by candita** [comment]
> {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:254","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 10m0s grace period","severity":"error","time":"2022-11-22T00:48:32Z"}


/retest-required

**Comment by Miciah** [comment]
[e2e-gcp-ovn-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/856/pull-ci-openshift-cluster-ingress-operator-master-e2e-gcp-ovn-serial/1603453426119741440) because the console-operator had too many watch requests:
```
[sig-arch][Late]  operators should not create watch channels very often  [apigroup:config.openshift.io] [Suite:openshift/conformance/parallel]
{  fail [github.com/openshift/origin/test/extended/apiserver/api_requests.go:449]: Expected     <[]string \| len:1, cap:1>: [         "Operator \"console-operator\" produces more watch requests than expected: watchrequestcount=272, upperbound=266, ratio=1.02",     ] to be empty Ginkgo exit error 1: exit with code 1}
```
Also, the `route/oauth-openshift disruption/ingress-to-oauth-server connection/new` and `route/console disruption/ingress-to-console connection/new` disruption tests observed too much disruption.
/test e2e-gcp-ovn-serial

**Pull request merged**
