### PR TITLE
ADd a RHEL7 dockerfile and standardize format

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
@ironcladlou comments?

**Comment by ironcladlou** [comment]
Kicked off newly merged operator test.

/lgtm

**Comment by ironcladlou** [comment]
@smarterclayton 

`ci/prow/e2e-aws-operator` failure is an AWS quota flake.

`ci/prow/rhel-images` looks like some sort of problem with the dynamically injected Dockerfile directives.

**Pull request merged**
