### PR TITLE
OCPBUGS-4759: Do not manage DNS for an ingresscontroller with domain mismatch in GCP

### PR DESCRIPTION
**Pull request by gcs278**
Do not manage DNS for an ingresscontroller with a domain that does not match the baseDomain of the cluster DNS config for GCP.

This had been previously done for AWS (https://github.com/openshift/cluster-ingress-operator/pull/761), now expanding to GCP.

- pkg/operator/controller/ingress/dns.go: Add GCP domain validation to manageDNSForDomain
- pkg/operator/controller/ingress/dns_test.go: Add unit tests for manageDNSForDomain with GCP

### CODE REVIEW

**Comment by gcs278** [comment]
/hold
Waiting for confirmation GCP indeed can't create domains outside of it's cluster domain or does something weird like appending domains (like azure).

**Comment by gcs278** [comment]
/unhold
I confirmed GCP doesn't do wacky things with mismatching DNS domains, like treating it as a subdomain.

**Comment by frobware** [comment]
Looks like the AWS cluster did not get created sucessfully:

```

openshift cluster install failed with other errors
 
level=fatal msg=failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": baseDomain: Invalid value: "origin-ci-int-aws.dev.rhcloud.com": the zone already has record sets for the domain of the cluster: [api.ci-op-di99mig1-52591.origin-ci-int-aws.dev.rhcloud.com
```

/test e2e-aws-ovn-serial

**Pull request merged**
