### PR TITLE
[release-4.12] OCPBUGS-15467: Add missing AWS permission for ListTagsForResources

### PR DESCRIPTION
**Pull request by Miciah**
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/868.  `pkg/manifests/bindata.go` had a conflict and had to be regenerated for the backport.  

---

The defined CredentialsRequest is missing a required permission for the AWS "Provider.lookupZoneIDWithoutResourceTagging" method.

### CODE REVIEW

**Comment by melvinjoseph86** [comment]
Verified using cluster bot
melvinjoseph@mjoseph-mac Downloads % oc -n openshift-cloud-credential-operator get CredentialsRequest openshift-ingress -oyaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2023-07-02T07:28:12Z"
  finalizers:
  - cloudcredential.openshift.io/deprovision
  generation: 1
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-ingress
  namespace: openshift-cloud-credential-operator
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 4392c2c8-dee9-4c0b-8d4c-125ab23be005
  resourceVersion: "1995"
  uid: f38eb63b-eb82-495e-8831-f893644dff00
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - elasticloadbalancing:DescribeLoadBalancers
      - route53:ListHostedZones
      - route53:ListTagsForResources                    <-------------------------
      - route53:ChangeResourceRecordSets
      - tag:GetResources
      effect: Allow
      resource: '*'
  secretRef:
    name: cloud-credentials
    namespace: openshift-ingress-operator
  serviceAccountNames:
  - ingress-operator
status:
  conditions:
  - lastProbeTime: "2023-07-02T07:28:40Z"
    lastTransitionTime: "2023-07-02T07:28:40Z"
    message: successfully granted credentials request
    reason: CredentialsProvisionSuccess
    status: "False"
    type: CredentialsProvisionFailure
  lastSyncCloudCredsSecretResourceVersion: "1894"
  lastSyncGeneration: 1
  lastSyncTimestamp: "2023-07-02T07:28:40Z"
  providerStatus:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderStatus
    policy: ci-ln-lwbrwsb-76ef8--openshift-ingress-7wnw2-policy
    user: ci-ln-lwbrwsb-76ef8--openshift-ingress-7wnw2
  provisioned: true
melvinjoseph@mjoseph-mac Downloads % oc get co                                                                                
oc NAME                                       VERSION                                                   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication                             4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      7m15s   
baremetal                                  4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      25m     
cloud-controller-manager                   4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      28m     
cloud-credential                           4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      29m     
cluster-autoscaler                         4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      25m     
config-operator                            4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      26m     
console                                    4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      11m     
control-plane-machine-set                  4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      24m     
csi-snapshot-controller                    4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      26m     
dns                                        4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      25m     
etcd                                       4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      24m     
image-registry                             4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      20m     
ingress                                    4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      16m     
insights                                   4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      17m     
kube-apiserver                             4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      23m     
kube-controller-manager                    4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      23m     
kube-scheduler                             4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      23m     
kube-storage-version-migrator              4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      26m     
machine-api                                4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      21m     
machine-approver                           4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      25m     
machine-config                             4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      24m     
marketplace                                4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      25m     
monitoring                                 4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      13m     
network                                    4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      28m     
node-tuning                                4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      25m     
openshift-apiserver                        4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      8m13s   
openshift-controller-manager               4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      25m     
openshift-samples                          4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      20m     
operator-lifecycle-manager                 4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      26m     
operator-lifecycle-manager-catalog         4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      26m     
operator-lifecycle-manager-packageserver   4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      21m     
service-ca                                 4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      26m     
storage                                    4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      25m     
melvinjoseph@mjoseph-mac Downloads % oc get co/ingress
NAME      VERSION                                                   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
ingress   4.12.0-0.ci.test-2023-07-02-071721-ci-ln-lwbrwsb-latest   True        False         False      16m     
melvinjoseph@mjoseph-mac Downloads % oc get po -n openshift-ingress  
NAME                              READY   STATUS    RESTARTS   AGE
router-default-59ccd55cf8-grqfp   1/1     Running   0          26m
router-default-59ccd55cf8-s52jc   1/1     Running   0          26m
melvinjoseph@mjoseph-mac Downloads % oc get po -n openshift-ingress-operator 
NAME                               READY   STATUS    RESTARTS      AGE
ingress-operator-99749874b-n8mmz   2/2     Running   3 (19m ago)   30m

**Comment by Miciah** [comment]
This backport is low-risk as it only adds a required permission and has been pre-merge verified.
/label backport-risk-assessed

[e2e-aws-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/954/pull-ci-openshift-cluster-ingress-operator-release-4.12-e2e-aws-operator/1675401301682294784) because `TestAWSELBConnectionIdleTimeout` and `TestRouterCompressionOperation` failed.  These test failures are known issues that should be fixed by #959 and #963, respectively.  

[e2e-gcp-ovn-serial failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/954/pull-ci-openshift-cluster-ingress-operator-release-4.12-e2e-gcp-ovn-serial/1675401301703266304) because `[sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured` failed.
<details>

```
{  "severity": "warning"
        },
        "value": [
          1688285125.514,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "ALERTS",
          "alertname": "KubeAggregatedAPIErrors",
          "alertstate": "firing",
          "name": "v1.project.openshift.io",
          "namespace": "default",
          "prometheus": "openshift-monitoring/k8s",
          "severity": "warning"
        },
        "value": [
          1688285125.514,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "ALERTS",
          "alertname": "KubeAggregatedAPIErrors",
          "alertstate": "firing",
          "name": "v1.quota.openshift.io",
          "namespace": "default",
          "prometheus": "openshift-monitoring/k8s",
          "severity": "warning"
        },
        "value": [
          1688285125.514,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "ALERTS",
          "alertname": "KubeAggregatedAPIErrors",
          "alertstate": "firing",
          "name": "v1.route.openshift.io",
          "namespace": "default",
          "prometheus": "openshift-monitoring/k8s",
          "severity": "warning"
        },
        "value": [
          1688285125.514,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "ALERTS",
          "alertname": "KubeAggregatedAPIErrors",
          "alertstate": "firing",
          "name": "v1.security.openshift.io",
          "namespace": "default",
          "prometheus": "openshift-monitoring/k8s",
          "severity": "warning"
        },
        "value": [
          1688285125.514,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "ALERTS",
          "alertname": "KubeAggregatedAPIErrors",
          "alertstate": "firing",
          "name": "v1.template.openshift.io",
          "namespace": "default",
          "prometheus": "openshift-monitoring/k8s",
          "severity": "warning"
        },
        "value": [
          1688285125.514,
          "1"
        ]
      },
      {
        "metric": {
          "__name__": "ALERTS",
          "alertname": "KubeAggregatedAPIErrors",
          "alertstate": "firing",
          "name": "v1.user.openshift.io",
          "namespace": "default",
          "prometheus": "openshift-monitoring/k8s",
          "severity": "warning"
        },
        "value": [
          1688285125.514,
          "1"
        ]
      }
    ]
occurred
Ginkgo exit error 1: exit with code 1}
```
</details>

Also, `[sig-instrumentation][Late] Alerts shouldn't report any unexpected alerts in firing or pending state` failed.
```
{  fail [github.com/onsi/ginkgo/v2@v2.1.5-0.20220909190140-b488ab12695a/internal/suite.go:612]: Jul  2 09:30:51.894: Unexpected alerts fired or pending after the test run:  alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.apps.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.authorization.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.build.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.image.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.oauth.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.project.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.quota.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.route.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.security.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.template.openshift.io", namespace="default", severity="warning"} alert KubeAggregatedAPIErrors fired for 180 seconds with labels: {name="v1.user.openshift.io", namespace="default", severity="warning"} Ginkgo exit error 1: exit with code 1}
```

Let's see whether the same issue happens again.
/test e2e-gcp-ovn-serial

**Comment by Miciah** [comment]
/hold cancel
/test all
since #963 and #964 have merged.

**Pull request merged**
