### PR TITLE
[release-4.15] OCPBUGS-36466: Allow operator to update Route spec.subdomain

### PR DESCRIPTION
**Pull request by Miciah**
#### Allow operator to update Route `spec.subdomain`

Before this change, cluster-ingress-operator did not have permission to update `spec.host` or `spec.subdomain` on an existing route as the operator's serviceaccount did not have the necessary "routes/custom-host" permission.  #965 added logic to the operator to clear `spec.host` and instead set `spec.subdomain`, but without the required permission, the update would fail with the following error message:

    ERROR   operator.init   controller/controller.go:265    Reconciler error {"controller": "canary_controller", "object": {"name":"default","namespace":"openshift-ingress-operator"}, "namespace": "openshift-ingress-operator", "name": "default", "reconcileID": "463061e3-93a1-4067-802e-03e3f1f8cdd0", "error": "failed to ensure canary route: failed to update canary route openshift-ingress-canary/canary: Route.route.openshift.io \"canary\" is invalid: spec.subdomain: Invalid value: \"canary-openshift-ingress-canary\": field is immutable"}

This PR adds the needed permission to the clusterrole for the operator's serviceaccount so that the update can succeed.

#### Delete and recreate canary route to clear `spec.host`

Fix the update logic for the canary route to handle clearing `spec.host`. Attempts to clear `spec.host` using a simple update may be ignored (see https://github.com/openshift/origin/commit/54c072c122b48c5d7074fe8904d493d0534733e2).  Therefore it is necessary to delete and recreate the route.  

Before this change, the operator would set `spec.subdomain`, but it did not actually clear `spec.host`, and so setting `spec.subdomain` had no effect.

After this change, the operator should clear `spec.host`, and `spec.subdomain` should be in effect.

---

This is manual cherry-pick of #1047 and #1099.

### CODE REVIEW

**Comment by Miciah** [comment]
https://github.com/openshift/cluster-ingress-operator/compare/d19536ff9fb53fc72fb6f362e81567eabf45fb9d..357c1a7942e5a194687febab169cce3624f35ddc adds a missing `fmt` import.

**Comment by melvinjoseph86** [comment]
Verified the fix using clusterbot

    create a build using this PR and upgrade a 4.13 cluster using that build.
    Didn't see any error messages in the ingress operator logs.

hence marking the bug are verified
/label qe-approved

**Comment by candita** [comment]
Dependency on #1099

**Comment by candita** [comment]
Backport is required because the original bug [OCPBUGS-36465](https://issues.redhat.com//browse/OCPBUGS-36465) was found in version 4.14 and disrupts upgrades from 4.13 to 4.14. Any risk introduced by this fix is balanced against the improvement in the success of 4.14 upgrades.

/label backport-risk-assessed

**Pull request merged**
