### PR TITLE
Add edge termination to canary route

### PR DESCRIPTION
**Pull request by jomeier**
This commit adds edge termination to the canary route. If you use an external loadbalancer that redirects all http traffic to https (us in our case) this route will not serve its purpose and the openshift-ingress-operator will be degraded during an upgrade.

Setting it to 'edge' termination should work in all setups.

### CODE REVIEW

**Comment by sgreene570** [comment]
Hey @jomeier ! Thanks for raising this bug and creating this patch. I previously did not think about this issue with custom external load balancers. Let me double check that this is the best approach to resolve this issue.

In the meantime, let's see what CI says:
/ok-to-test

**Comment by sgreene570** [comment]
@jomeier could you run `make generate` and amend the output to this PR? Thanks!

**Comment by sgreene570** [comment]
@jomeier looks like the canary HTTP probe needs to skip certificate verification for these changes to work.

See https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/555/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws/1364607874621247488/artifacts/e2e-aws/gather-extra/artifacts/pods/openshift-ingress-operator_ingress-operator-5787998cb9-bzxk4_ingress-operator.log

If it's easiest, I can open a PR with the necessary changes to do so and cherry-pick your commits from here over.

**Comment by jomeier** [comment]
> @jomeier looks like the canary HTTP probe needs to skip certificate verification for these changes to work.
> 
> See https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/555/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws/1364607874621247488/artifacts/e2e-aws/gather-extra/artifacts/pods/openshift-ingress-operator_ingress-operator-5787998cb9-bzxk4_ingress-operator.log
> 
> If it's easiest, I can open a PR with the necessary changes to do so and cherry-pick your commits from here over.

Sure @sgreene570 . Do what's necessary to solve this problem, please.

**Comment by sgreene570** [comment]
superseded by https://github.com/openshift/cluster-ingress-operator/pull/556

Thanks again @jomeier

**Pull request closed without merging**
