### PR TITLE
Bug 2084433: AUTH-133: assets: comply to pod security

### PR DESCRIPTION
**Pull request by Miciah**
#### canary: Handle updates to the security context

* `pkg/operator/controller/canary/daemonset.go` (`canaryDaemonSetChanged`): Check the pod and container security contexts, and update them if they changed.
* `pkg/operator/controller/canary/daemonset_test.go` (`TestCanaryDaemonsetChanged`): Add test cases to verify that the operator handles updates to the pod and container security contexts.
* `pkg/operator/controller/ingress/namespace.go` (`routerNamespaceChanged`): Add the `pod-security.kubernetes.io/*` labels to the list of managed labels.

---

This PR supersedes #759.

/cc @stlaz
/cc @s-urbaniak

### CODE REVIEW

**Comment by Miciah** [comment]
`TestHostNetworkPortBinding` is failing, and I found events such as the following in the CI artifacts:
```
Error creating: pods "router-host-765dd695c-sssh2" is forbidden: violates PodSecurity "baseline:latest": host namespaces (hostNetwork=true), hostPort (container "router" uses hostPorts 1936, 443, 80)
```

**Comment by Miciah** [comment]
Last push changes the pod-security namespace labels from "baseline" to "privileged".

**Comment by s-urbaniak** [comment]
(lgtm is from the perspective of necessary pod security settings)

**Comment by Miciah** [comment]
```
[sig-arch] events should not repeat pathologically
{  1 events happened too frequently  event happened 38 times, something is wrong: ns/openshift-machine-api pod/machine-api-controllers-6949b47dfc-z4dmn node/ip-10-0-154-91.ec2.internal - reason/ProbeError Readiness probe error: Get "http://10.130.0.10:9442/healthz": dial tcp 10.130.0.10:9442: connect: connection refused body:  }
```
/test e2e-upgrade

**Pull request merged**
