### PR TITLE
router deployment: add NET_BIND_SERVICE capability

### PR DESCRIPTION
**Pull request by stlaz**
Router requires the 80 and 443 ports in order to function properly.
These are reserved ports and so the container needs the NET_BIND_SERVICE
capability in order to work in a drop ALL caps environments.

---

This PR is currently blocking https://github.com/openshift/cluster-kube-apiserver-operator/pull/1338 from succeeding

/cc @s-urbaniak

### CODE REVIEW

**Comment by stlaz** [comment]
Aaaand these PRs are now blocking each other :facepalm:

**Comment by Miciah** [comment]
Is this needed in addition to <https://github.com/openshift/cluster-ingress-operator/pull/718>?

**Comment by Miciah** [comment]
Note that #718 was reverted, and the change is re-added with <https://github.com/openshift/cluster-ingress-operator/pull/743>.

**Comment by deads2k** [comment]
I think enumerating the capabilities is both different and valuable

**Comment by Miciah** [comment]
> I think enumerating the capabilities is both different and valuable

Do they warrant separate Bugzilla reports?  Is there a reason we wouldn't want to backport both changes to 4.10?  (We plan to backport #743.)  Adding the `NET_BIND_SERVICE` capability and adding `allowPrivilegeEscalation: true` still seem similar enough to combine into a single PR (I can ask Chad to cherry-pick the commit from this PR, preserving authorship).  If you prefer to track this separately though, that's fine; we'll just need a separate BZ, and we should merge #743 first since it adds logic to handle updates to the security context.

**Comment by stlaz** [comment]
> I think enumerating the capabilities is both different and valuable
absolutely

I temporarily added the restricted-v2 SCC to unblock this PR.

> Do they warrant separate Bugzilla reports?
No bugzilla needed for this PR

> Is there a reason we wouldn't want to backport both changes to 4.10?
Unfortunately, the way SCCs were previously set up, I think only the `privileged` SCC would match the added capabilities :frowning_face: 

>  Adding the `NET_BIND_SERVICE` capability and adding `allowPrivilegeEscalation: true`
I don't understand, this is only adding NET_BIND_SERVICE. I don't think the container needs `allowPrivilegeEscalation: true`, at least it seemed to work just fine in my testing (see the SCC that's attached now).

**Comment by stlaz** [comment]
Okay, it seems that I was wrong and was checking what happens in an environment where the privilege escalation was still possible.

In that case we can ignore this PR in favour of https://github.com/openshift/cluster-ingress-operator/pull/743

**Comment by Miciah** [comment]
> No bugzilla needed for this PR

I mean, Prow won't let you merge without either a BZ or a Jira issue with required approvals.  

> > Is there a reason we wouldn't want to backport both changes to 4.10?
> 
> Unfortunately, the way SCCs were previously set up, I think only the `privileged` SCC would match the added capabilities frowning_face

I think we used "privileged" when using container networking and "hostnetwork" when using the host network.  Is there a more restrictive SCC that would work for one or both of these types of networking?  

> This is only adding NET_BIND_SERVICE. I don't think the container needs `allowPrivilegeEscalation: true`, at least it seemed to work just fine in my testing (see the SCC that's attached now).

The reason `allowPrivilegeEscalation: true` is needed is that some users add custom SCCs that match the requirements as described in the pod template spec but that don't specify `allowPrivilegeEscalation: true`.  IIRC, privilege escalation is required because the router image uses a filesystem attribute to imbue `/bin/openshift-router` with the capability to bind low-numbered ports.

**Comment by Miciah** [comment]
Ah, the moment I posted my comment, your comment appears.  I should have reloaded before commenting, sorry.

**Pull request closed without merging**
