### PR TITLE
OCPBUGS-368: Fix e2e tests for pod security violations

### PR DESCRIPTION
**Pull request by thejasn**
This fixes the e2e breakage introduced with the recent adjustment of the default security policy.

Signed-off-by: Thejas N <thn@redhat.com>

### CODE REVIEW

**Comment by Miciah** [comment]
/retitle OCPBUGS-368: Fix e2e tests for pod security violations
/approve

**Comment by brandisher** [comment]
The changes look pretty straightforward. Pretty much drop everything that would allow advanced privileges since these containers don't need them.

/lgtm

**Pull request merged**
