### PR TITLE
main: support cluster config lookup through platform status

### PR DESCRIPTION
**Pull request by ironcladlou**
Support reading platform config through the platform status embedded in
infrastructure status, which is the default in 4.2. Continue reading AWS
status from the deprecated install config in clusters based on 4.1.

### CODE REVIEW

**Comment by knobunc** [comment]
Seems reasonable to me, thanks Dan.

**Comment by ironcladlou** [comment]
/hold

Looks like we may have to keep relying on installconfig for 4.1 clusters (even post-upgrade) — holding while I sort that out.

**Comment by ironcladlou** [comment]
I redid this to be compatible with AWS clusters based on 4.1 which will not have region info in the new platform status config.

/hold cancel

**Pull request merged**
