### PR TITLE
NE-66: Integrate operator metrics with Prometheus

### PR DESCRIPTION
**Pull request by Miciah**
The operator exposes metrics, but they are not collected.  Configure Prometheus to collect these metrics.

* `manifests/00-namespace.yaml`: Add a label for `openshift-monitoring`.
* `manifests/04-service.yaml`: New file.  Define a metrics service.
* `manifests/0000_90_ingress-operator_00_prometheusrole.yaml`: New file.  Define a role that grants access to services, endpoints, and pods.
* `manifests/0000_90_ingress-operator_01_prometheusrolebinding.yaml`: New file.  Bind the `prometheus-k8s` service account to the new role.
* `manifests/0000_90_ingress-operator_02_servicemonitor.yaml`: New file.  Define a service monitor for the new service.

### CODE REVIEW

**Comment by ironcladlou** [comment]
@brenton was asking about work in this area

**Comment by ironcladlou** [comment]
@Miciah remove hold if you're ready to merge this

/retest
/lgtm
/hold

**Comment by ironcladlou** [comment]
@Miciah looks like bindata needs regenerated

**Comment by Miciah** [comment]
/hold
No need to keep retrying and failing on out-of-date bindata.

**Comment by Miciah** [comment]
/hold cancel
Bindata is regenerated, and the metrics endpoint is now secured using kube-rbac-proxy.

**Comment by Miciah** [comment]
Latest push drops `-v=8` from the kube-rbac-proxy options.

**Comment by Miciah** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/263/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws/1464 failed on provisioning:

   level=error msg="Error: Error waiting for instance (i-0e2980176afdf6dd4) to become ready: Failed to reach target state. Reason: Server.InternalError: Internal error on launch"

/test e2e-aws

**Comment by brenton** [comment]
:clinking_glasses:

**Pull request merged**
