### PR TITLE
[release-4.8] Bug 2000414: Configure router to use "source" for passthrough

### PR DESCRIPTION
**Pull request by Miciah**
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/650.

### CODE REVIEW

**Comment by Miciah** [comment]
Looks like a flake:
```
=== RUN   TestInternalLoadBalancerGlobalAccessGCP
    operator_test.go:873: expected networking.gke.io/internal-load-balancer-allow-global-access=false, found networking.gke.io/internal-load-balancer-allow-global-access=true
    operator_test.go:882: WARNING: cloud resources may have been leaked! failed to delete ingresscontroller test-gcp: timed out waiting for ingresscontroller to be deleted: timed out waiting for the condition
```
/test e2e-gcp-operator

**Comment by Miciah** [comment]
"[sig-auth][Feature:SCC][Early]`` should not have pod creation failures during install" failed.
/test e2e-aws-single-node

**Comment by candita** [comment]
`Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.ci-op-0pj4ji7z-8c3de.origin-ci-int-aws.dev.rhcloud.com.', type='A'] but it already exists]`

Mentioned in https://github.com/openshift/installer/pull/5189

**Comment by quarterpin** [comment]
/lgtm
/label qe-approved

Verified via pre-merge verification workflow, more references related to the test can be found in:
https://bugzilla.redhat.com/show_bug.cgi?id=2000414#c1

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.50

adding cherry-pick approved

**Pull request merged**
