### PR TITLE
Rename workload annotations

### PR DESCRIPTION
**Pull request by imiller0**
As per openshift/enhancements#739, the workload
annotations names are changing.

/hold
Hold until after openshift/kubernetes#632 is merged please

### CODE REVIEW

**Comment by Miciah** [comment]
@imiller0, is there a Bugzilla report that can be associated with this PR?

**Comment by imiller0** [comment]
/unhold
openshift/kubernetes#632 has merged, please consider this PR ready as well.

**Comment by sgreene570** [comment]
> /unhold
> [openshift/kubernetes#632](https://github.com/openshift/kubernetes/pull/632) has merged, please consider this PR ready as well.

@imiller0 is there a BZ report for this bug? We need the valid-bug tag to merge PRs for the moment.

**Pull request merged**
