### PR TITLE
SPLAT-1722: Remove alibaba

### PR DESCRIPTION
**Pull request by jcpowermac**
This PR removes support for the Alibaba cloud
which is being removed from the product.

https://issues.redhat.com/browse/OCPSTRAT-1466
https://issues.redhat.com/browse/SPLAT-1454
https://issues.redhat.com//browse/SPLAT-1722

Additional PRs

- https://github.com/openshift/cluster-image-registry-operator/pull/1077
- https://github.com/openshift/cluster-autoscaler-operator/pull/330
- https://github.com/openshift/cloud-credential-operator/pull/737
- https://github.com/openshift/machine-api-operator/pull/1200
- https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/324
- https://github.com/openshift/installer/pull/7832

### CODE REVIEW

**Comment by alebedev87** [comment]
@jcpowermac : Can you please provide a description of the change and more descriptive commit messages (with Jira ticket references)?

**Comment by jcpowermac** [comment]
> @jcpowermac : Can you please provide a description of the change and more descriptive commit messages (with Jira ticket references)?

Sorry for the slow response... 
Rebased, updated the commit and pr message.

**Comment by jcpowermac** [comment]
@alebedev87 please let me know if there is something more that is needed.

**Comment by gcs278** [comment]
Seems straightforward enough. We still have an [API field](https://github.com/openshift/api/blob/09b63162bb151d7fa27fc063162f2d2b4cf197a0/config/v1/types_infrastructure.go#L332) that has no fields within it, but as far as this PR is concerned, looks good to me.
/approve

@grzpiotrowski Do you want to take a look and LGTM?

**Comment by grzpiotrowski** [comment]
Checked for any potential leftovers and compared with the initial Alibaba PR.
Failed tests look unrelated.

/retest
/lgtm

**Comment by gcs278** [comment]
Pod scheduling timeout
/retest

**Comment by gcs278** [comment]
infra failures
/retest

**Comment by grzpiotrowski** [comment]
```
{  openshift cluster install failed with infrastructure setup }
```
/retest

**Comment by gcs278** [comment]
Looks unrelated
/test e2e-aws-ovn-serial

**Pull request merged**
