### PR TITLE
[release-4.10] Bug 2079034: Add allowPrivilegeEscalation to the router container

### PR DESCRIPTION
**Pull request by brandisher**
The reason for this change is that the pods associated with the default
IngressController don't explicitly request allowPrivilegeEscalation
which allows them to acquire an SCC that's too restrictive.

### CODE REVIEW

**Comment by brandisher** [comment]
Cluster setup failed.

/retest

**Comment by ShudiLi** [comment]
verified with pre-merge test process, see https://bugzilla.redhat.com/show_bug.cgi?id=2079034#c3

**Comment by brandisher** [comment]
Hitting the must-gather timeout.

/test e2e-aws-operator

**Comment by Miciah** [comment]
Let's give the e2e-aws-operator job another try now that https://github.com/openshift/must-gather/pull/323 has merged...
/test e2e-aws-operator

**Pull request merged**
