### PR TITLE
BZ1765044 - Support cluster-wide proxy

### PR DESCRIPTION
**Pull request by cliles**
Shamelessly stolen from cluster-credential-operator

### CODE REVIEW

**Comment by Miciah** [comment]
I believe #334 supersedes this PR.  #334 is more complex because it handles updates to the CA configmap.

**Comment by danehans** [comment]
@cliles I think https://github.com/openshift/cluster-ingress-operator/pull/334#issuecomment-563355629 is barfing b/c this pr references bz 1765044. Can you remove the bz reference from this pr when you have a moment?

**Comment by cliles** [comment]
superseded by #334

**Comment by cliles** [comment]
@danehans - removed and closed.

**Pull request closed without merging**
