### PR TITLE
NE-1071: Default HAProxy maxconn value to 50000 for OCP 4.12)

### PR DESCRIPTION
**Pull request by frobware**
Bump openshift/api for https://github.com/openshift/api/pull/1299.

### CODE REVIEW

**Comment by frobware** [comment]
/hold

Waiting for https://github.com/openshift/api/pull/1299.

**Comment by frobware** [comment]
> /hold
> 
> Waiting for [openshift/api#1299](https://github.com/openshift/api/pull/1299).

Removing the hold as openshift/api#1299 has merged.

/hold cancel

**Comment by candita** [comment]
@frobware The vendoring that included `allowedSourceRanges` looks too early, I think that is for https://github.com/openshift/cluster-ingress-operator/pull/817, which is still open.  You pulled [920c365](https://github.com/openshift/api/commit/920c3651ba3f746229a77afaf55fc42a29e9742a) which included https://github.com/openshift/api/commit/76624ee4fd583292bce8947192039eb5ecaa7163

**Comment by candita** [comment]
Operator unavailable (IngressUnavailable): The "default" ingress controller reports Available=False: IngressControllerUnavailable: One or more status conditions indicate unavailable: DNSReady=False (FailedZones: The record failed to provision in some zones: [{ map[Name:/errorci-op-88f2qcnc-43abb-g469q-int kubernetes.io/cluster/ci-op-88f2qcnc-43abb-g469q:owned]}])  Operator unavailable (IngressUnavailable): The "default" ingress controller reports Available=False: IngressControllerUnavailable: One or more status conditions indicate unavailable: DNSReady=False (FailedZones: The record failed to provision in some zones: [{ map[Name:/errorci-op-88f2qcnc-43abb-g469q-int kubernetes.io/cluster/ci-op-88f2qcnc-43abb-g469q:owned]}])}

/test e2e-aws-operator

**Comment by candita** [comment]
[sig-network-edge] ns/openshift-authentication route/oauth-openshift disruption/ingress-to-oauth-server connection/new should be available throughout the test
[sig-network-edge] ns/openshift-console route/console disruption/ingress-to-console connection/new should be available throughout the test

/test e2e-gcp-ovn-serial

**Comment by frobware** [comment]
> @frobware The vendoring that included `allowedSourceRanges` looks too early, I think that is for #817, which is still open. You pulled [920c365](https://github.com/openshift/api/commit/920c3651ba3f746229a77afaf55fc42a29e9742a) which included [openshift/api@76624ee](https://github.com/openshift/api/commit/76624ee4fd583292bce8947192039eb5ecaa7163)
> 
> However, the PR for `allowedSourceRanges` doesn't change anything, just adds optional fields to the operator, so that might be ok.

I'm not sure I understand the reference to `allowedSourceRanges`. I specifically picked up: 

```sh
[spicy] ~/src/github.com/openshift/api
% git show 920c3651ba3f746229a77afaf55fc42a29e9742a
commit 920c3651ba3f746229a77afaf55fc42a29e9742a
Merge: ec3e4490 5dcef198
Author: OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
Date:   Mon Oct 10 18:43:55 2022 +0200

    Merge pull request #1299 from frobware/ingress-increase-maxconn-to-50000
    
    NE-1071: Default HAProxy maxconn value to 50000 for OCP 4.12
```

My commit message for the vendor bump calls out my steps: 

```sh
$ go get github.com/openshift/api@920c3651ba3f746229a77afaf55fc42a29e9742a
$ go mod vendor
$ go mod tidy
```

And if you look for 50000 in this commit I see: 

```sh
[spicy] ~/src/github.com/openshift/cluster-ingress-operator
% ag -w 50000
manifests/00-custom-resource-definition.yaml
1297:                      will use the default value of 50000, but the default is subject
1304:                      50000. \n Setting a value that is greater than the current operating

vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
1297:                      will use the default value of 50000, but the default is subject
1304:                      50000. \n Setting a value that is greater than the current operating

vendor/github.com/openshift/api/operator/v1/types_ingress.go
1502:	// the default value of 50000, but the default is subject to
1510:	// memory usage compared to the current default of 50000.

vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
849:	"maxConnections":              "maxConnections defines the maximum number of simultaneous connections that can be established per HAProxy process. Increasing this value allows each ingress controller pod to handle more connections but at the cost of additional system resources being consumed.\n\nPermitted values are: empty, 0, -1, and the range 2000-2000000.\n\nIf this field is empty or 0, the IngressController will use the default value of 50000, but the default is subject to change in future releases.\n\nIf the value is -1 then HAProxy will dynamically compute a maximum value based on the available ulimits in the running container. Selecting -1 (i.e., auto) will result in a large value being computed (~520000 on OpenShift >=4.10 clusters) and therefore each HAProxy process will incur significant memory usage compared to the current default of 50000.\n\nSetting a value that is greater than the current operating system limit will prevent the HAProxy process from starting.\n\nIf you choose a discrete value (e.g., 750000) and the router pod is migrated to a new node, there's no guarantee that that new node has identical ulimits configured. In such a scenario the pod would fail to start. If you have nodes with different ulimits configured (e.g., different tuned profiles) and you choose a discrete value then the guidance is to use -1 and let the value be computed dynamically at runtime.\n\nYou can monitor memory usage for router containers with the following metric: 'container_memory_working_set_bytes{container=\"router\",namespace=\"openshift-ingress\"}'.\n\nYou can monitor memory usage of individual HAProxy processes in router containers with the following metric: 'container_memory_working_set_bytes{container=\"router\",namespace=\"openshift-ingress\"}/container_processes{container=\"router\",namespace=\"openshift-ingress\"}'.",
```

**Comment by frobware** [comment]
```
Run multi-stage test e2e-aws-operator - e2e-aws-operator-gather-audit-logs container test expand_less | 0s
-- | --
{  for <unknown>: <unknown> error getting cluster operators: Get "https://api.ci-op-24qfng97-43abb.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 34.235.19.133:6443: connect: connection refused ClusterOperators: 	
clusteroperators are missing
```

/retest

**Comment by candita** [comment]
Numerous e2e issues, seems infra-related, not sure:

=== CONT  TestAll/parallel/TestAWSELBConnectionIdleTimeout
    operator_test.go:2427: lookup idle-timeout-httpd-openshift-ingress.test-idle-timeout.ci-op-4xflwd48-43abb.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host

/retest-required

**Comment by candita** [comment]
Also:

pods/openshift-network-operator_network-operator-7f94bcbdb7-2vxlg_network-operator.log.gz:E1013 20:34:58.316312       1 runtime.go:79] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)

**Comment by candita** [comment]
@frobware you picked up the right commit.  I was concerned that it contained api updates for a [PR](https://github.com/openshift/cluster-ingress-operator/pull/817) that had not yet merged.  However, that PR just merged so it doesn't matter.

**Comment by candita** [comment]
Oct 14 00:52:03.000 I ns/openshift-etcd-operator deployment/etcd-operator reason/OperatorStatusChanged Status for clusteroperator/etcd changed: Degraded message changed from "NodeControllerDegraded: All master nodes are ready\nEtcdMembersDegraded: No unhealthy members found" to "NodeControllerDegraded: The master nodes not ready: node \"ci-op-pr9zz16g-9dec8-fgbp4-master-0-clone\" not ready since 2022-10-14 00:52:03 +0000 UTC because KubeletNotReady ([container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?, failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes \"ci-op-pr9zz16g-9dec8-fgbp4-master-0-clone\" not found])\nEtcdMembersDegraded: No unhealthy members found"

/test e2e-gcp-ovn-serial

**Comment by candita** [comment]
Oct 14 16:54:06.000 I ns/openshift-etcd-operator deployment/etcd-operator reason/OperatorStatusChanged Status for clusteroperator/etcd changed: Degraded message changed from "NodeControllerDegraded: All master nodes are ready\nEtcdMembersDegraded: No unhealthy members found" to "NodeControllerDegraded: The master nodes not ready: node \"ci-op-4q4f9bpc-9dec8-j8b95-master-0-clone\" not ready since 2022-10-14 16:54:06 +0000 UTC because KubeletNotReady ([container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?, failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes \"ci-op-4q4f9bpc-9dec8-j8b95-master-0-clone\" not found])\nEtcdMembersDegraded: No unhealthy members found"

/test e2e-gcp-ovn-serial

**Comment by Miciah** [comment]
#839, #842, and #837 have merged, so all tests need to be rerun.
/test all

I started the e2e-azure-operator and e2e-gcp-operator jobs on #837, but I started them late and they aren't required jobs, so #837 merged before they finished.  I'd like to make sure they are still passing.  
/test e2e-azure-operator
/test e2e-gcp-operator

**Comment by Miciah** [comment]
#843 should fix the nil-pointer deference that caused e2e-gcp-operator to fail.

**Comment by candita** [comment]
level=error msg=Cluster operator authentication Available is False with OAuthServerDeployment_PreconditionNotFulfilled::OAuthServerRouteEndpointAccessibleController_ResourceNotFound::OAuthServerServiceEndpointAccessibleController_EndpointUnavailable::WellKnown_PrereqsNotReady: OAuthServerRouteEndpointAccessibleControllerAvailable: failed to retrieve ingress from cache: ingress.config.openshift.io "cluster" not found

/test e2e-aws-operator

**Comment by candita** [comment]
level=error msg=Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::OAuthServerConfigObservation_Error::OAuthServerServiceEndpointAccessibleController_SyncError::OAuthServerServiceEndpointsEndpointAccessibleController_SyncError::RouterCerts_NoIngressConfig: IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server

/test e2e-aws-ovn

**Comment by candita** [comment]
Asked about this failure in forum-node: 

Oct 17 16:11:59.544 E ns/openshift-console pod/console-786486fd6d-mcmml node/ci-op-n668dcyt-9dec8-k4kv2-master-1 uid/c8afc181-8e1e-4049-9d6b-bf8240072e28 container/console reason/ContainerExit code/255 cause/Error W1017 16:11:59.080096       1 main.go:223] Flag inactivity-timeout is set to less then 300 seconds and will be ignored!\nF1017 16:11:59.080150       1 validate.go:50] Invalid flag: node-architectures, error: list must contain name of node architectures separated by comma\n

Another failure might be infrad-related:

Oct 17 14:49:45.443 E ns/e2e-volumelimits-1646 pod/volume-limits-q67fh node/ci-op-n668dcyt-9dec8-k4kv2-worker-b-65tb9 uid/dec39dc0-41af-40a7-91d1-b0f16a0d733e container/volume-tester container exited with code 137 (Error):

/test e2e-gcp-ovn-serial

**Comment by candita** [comment]
ingress-to-console-new-connections was unreachable during disruption testing for at least 32s of 2h0m10s (maxAllowed=21s):
ingress-to-oauth-server-new-connections was unreachable during disruption testing for at least 30s of 2h0m10s (maxAllowed=17s):

/test e2e-gcp-ovn-serial

**Comment by candita** [comment]
Infra issues seem to have settled down.
/lgtm

**Comment by candita** [comment]
@frobware Git is saying there's a merge conflict on this now.

**Comment by candita** [comment]
This e2e-gcp-ovn-serial failure is almost the same (different number of seconds) as the previous run.

ingress-to-oauth-server-new-connections was unreachable during disruption testing for at least 37s of 2h0m18s (maxAllowed=17s):
ingress-to-console-new-connections was unreachable during disruption testing for at least 35s of 2h0m18s (maxAllowed=21s):

/test e2e-gcp-ovn-serial

**Comment by candita** [comment]
=== CONT  TestAll/parallel/TestHTTPHeaderBufferSize
    panic.go:482: deleted ingresscontroller header-buffer-size

/test e2e-aws-operator

**Comment by candita** [comment]
Still the disruption testing issue.  I haven't found anything of consequence in the logs, will re-run.

ingress-to-console-new-connections was unreachable during disruption testing for at least 41s of 2h3m39s (maxAllowed=21s):
ingress-to-oauth-server-new-connections was unreachable during disruption testing for at least 44s of 2h3m39s (maxAllowed=17s):

/test e2e-gcp-ovn-serial

**Comment by frobware** [comment]
openshift cluster install failed overall

/test e2e-gcp-ovn-serial

**Comment by frobware** [comment]
NodeInstallerDegraded: I1020 12:56:26.936145       1 cmd.go:422] Waiting for installer revisions to settle for node ip-10-0-198-30.ec2.internal
NodeInstallerDegraded: I1020 12:56:26.942248       1 cmd.go:496] Pod container statuses for node ip-10-0-198-30.ec2.internal are empty, waiting
NodeInstallerDegraded: I1020 12:56:36.949983       1 cmd.go:496] Pod container statuses for node ip-10-0-198-30.ec2.internal are empty, waiting
NodeInstallerDegraded: I1020 12:56:46.949469       1 cmd.go:496] Pod container statuses for node ip-10-0-198-30.ec2.internal are empty, waiting
NodeInstallerDegraded: I1020 12:56:56.950004       1 cmd.go:496] Pod container statuses for node ip-10-0-198-30.ec2.internal are empty, waiting
NodeInstallerDegraded: I1020 12:57:06.949550       1 cmd.go:496] Pod container statuses for node ip-10-0-198-30.ec2.internal are empty, waiting
NodeInstallerDegraded: I1020 12:57:16.949298       1 cmd.go:496] Pod container statuses for node ip-10-0-198-30.ec2.internal are empty, waiting
NodeInstallerDegraded: I1020 12:57:26.951637       1 cmd.go:496] Pod container statuses for node ip-10-0-198-30.ec2.internal are empty, waiting
NodeInstallerDegraded: I1020 12:57:26.959105       1 cmd.go:496] Pod container statuses for node ip-10-0-198-30.ec2.internal are empty, waiting
NodeInstallerDegraded: F1020 12:57:26.959124       1 cmd.go:106] timed out waiting for the condition
NodeInstallerDegraded:

/test e2e-aws-operator

**Comment by candita** [comment]
level=fatal msg=failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": metadata.name: Invalid value: "ci-op-01zy2yzq-9dec8": record api.ci-op-01zy2yzq-9dec8.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX. already exists in DNS Zone (XXXXXXXXXXXXXXXXXXXXXX/origin-ci-int-gce) and might be in use by another cluster, please remove it to continue

I've asked forum-testplatform if there's anything they can do to fix this: https://coreos.slack.com/archives/CBN38N3MW/p1666286734500309

Otherwise, I think it will continue until the cluster expires.

**Comment by candita** [comment]
Discussion in https://coreos.slack.com/archives/CBWMXQJKD/p1666306309631759 and https://coreos.slack.com/archives/CCH60A77E/p1666291967766679 about ongoing e2e-aws-operator failures.

**Comment by candita** [comment]
[sig-node] should not encounter ErrImagePull in non-openshift namespace pods
[sig-node] should not encounter ErrImagePull in openshift namespace pods

seen in e2e-gcp-ovn-serial failures

**Comment by candita** [comment]
Also, discussion regarding the 'ExtremelyHighIndividualControlPlaneCPU' alert in
https://coreos.slack.com/archives/C01CQA76KMX/p1665427374304029

**Comment by Miciah** [comment]
[e2e-aws-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/836/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator/1583590661112729600) because the kube-apiserver, kube-controller-manager, and network clusteroperators reported problems rolling out pods.

/test all
because #834 merged.

**Comment by frobware** [comment]
ingress-to-oauth-server-new-connections was unreachable during disruption testing for at least 41s of 2h2m25s (maxAllowed=17s):

/test e2e-gcp-ovn-serial

Not sure we're getting anywhere with e2e-gcp-ovn-serial as the disruption tests have been failing for a while in other cluster-ingress-operator PRs.

**Pull request merged**
