### PR TITLE
OCPBUGS-36044: Bump IBM/go-sdk-core to v5.17.4

### PR DESCRIPTION
**Pull request by grzpiotrowski**
Bump IBM/go-sdk-core to [v5.17.4](https://github.com/IBM/go-sdk-core/releases/tag/v5.17.4) which uses go-retryablehttp v0.7.7 avoiding a vulnerability.

```
go get github.com/IBM/go-sdk-core/v5@v5.17.4
go mod tidy
go mod vendor
```

### CODE REVIEW

**Comment by grzpiotrowski** [comment]
Same tests failed again. Seems like an issue in other runs as well when looking at the job history
```
        --- FAIL: TestAll/parallel/TestUnmanagedAWSEIPAllocations
        --- FAIL: TestAll/parallel/TestAWSEIPAllocationsForNLB
```

/test e2e-aws-operator

**Comment by rfredette** [comment]
@grzpiotrowski OCPBUGS-37373 is intended to be the bug for backporting to 4.16. Can you change this to refer to https://issues.redhat.com/browse/OCPBUGS-36044 instead? It should be the 4.17 bug for the same issue.

**Comment by grzpiotrowski** [comment]
> @grzpiotrowski OCPBUGS-37373 is intended to be the bug for backporting to 4.16. Can you change this to refer to https://issues.redhat.com/browse/OCPBUGS-36044 instead? It should be the 4.17 bug for the same issue.

Thank you. Changed the PR to point at https://issues.redhat.com/browse/OCPBUGS-36044 instead as suggested.

Rebased on top of master.

**Comment by grzpiotrowski** [comment]
CI issues.

/retest

**Comment by ShudiLi** [comment]
tested it with 4.17.0-0.ci.test-2024-08-09-011640-ci-ln-pz2g65b-latest
```
1.
% oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.17.0-0.ci.test-2024-08-09-011640-ci-ln-pz2g65b-latest   True        False         69m     Cluster version is 4.17.0-0.ci.test-2024-08-09-011640-ci-ln-pz2g65b-latest

2.
% oc -n openshift-ingress-operator -c ingress-operator rsync ingress-operator-7f76967b5f-p4pj2:/usr/bin/ingress-operator .
receiving file list ... done
ingress-operator

3.
% go version -m ingress-operator | grep github.com/IBM/go-sdk-core
	dep	github.com/IBM/go-sdk-core/v5	v5.17.4	

4.
% go version -m ingress-operator | grep github.com/asaskevich/govalidator
	dep	github.com/asaskevich/govalidator	v0.0.0-20230301143203-a9d515a09cc2
% go version -m ingress-operator | grep github.com/fatih/color           
	dep	github.com/fatih/color	v1.16.0	
% go version -m ingress-operator | grep github.com/gabriel-vasile/mimetype 
	dep	github.com/gabriel-vasile/mimetype	v1.4.3	
 % go version -m ingress-operator | grep github.com/go-openapi/errors       
	dep	github.com/go-openapi/errors	v0.21.0	
% go version -m ingress-operator | grep github.com/go-openapi/strfmt  
	dep	github.com/go-openapi/strfmt	v0.22.1	
% go version -m ingress-operator | grep github.com/go-playground/locales
	dep	github.com/go-playground/locales	v0.14.1	
% go version -m ingress-operator | grep github.com/go-playground/universal-translator
	dep	github.com/go-playground/universal-translator	v0.18.1	
% go version -m ingress-operator | grep github.com/go-playground/validator/v10       
	dep	github.com/go-playground/validator/v10	v10.19.0
% go version -m ingress-operator | grep github.com/google/uuid                
	dep	github.com/google/uuid	v1.6.0	
% go version -m ingress-operator | grep github.com/hashicorp/go-retryablehttp
	dep	github.com/hashicorp/go-retryablehttp	v0.7.7
% go version -m ingress-operator | grep github.com/leodido/go-urn            
	dep	github.com/leodido/go-urn	v1.4.0
% go version -m ingress-operator | grep github.com/mattn/go-colorable
	dep	github.com/mattn/go-colorable	v0.1.13	
 % go version -m ingress-operator | grep github.com/mattn/go-isatty   
	dep	github.com/mattn/go-isatty	v0.0.20	
 % go version -m ingress-operator | grep github.com/mitchellh/mapstructure
	dep	github.com/mitchellh/mapstructure	v1.5.0
% go version -m ingress-operator | grep go.mongodb.org/mongo-driver      
	dep	go.mongodb.org/mongo-driver	v1.14.0	
% go version -m ingress-operator | grep golang.org/x/sys            
	dep	golang.org/x/sys	v0.20.0	
```

**Comment by rfredette** [comment]
/approve
/lgtm

thanks!

**Pull request merged**
