### PR TITLE
Add service account names to credentials request manifest

### PR DESCRIPTION
**Pull request by akhil-rane**
For a new way of managing OpenShift credentials on AWS to work, using Security
Token Service, we need external tooling to know the service account names from
the Credentials Request manifest so that it can create IAM Roles that can be
assumed only by those specific service accounts.

Managing credentials using STS ref: https://github.com/openshift/cloud-credential-operator/blob/master/docs/sts.md
Tooling design ref: https://issues.redhat.com/browse/CCO-60

/cc @joelddiaz

### CODE REVIEW

**Comment by akhil-rane** [comment]
/unhold

Added service accounts to new CredentialsRequest field `serviceAccountNames`

**Review by joelddiaz — COMMENTED** [review]
:+1:

**Comment by akhil-rane** [comment]
@Miciah This is ready for review. PTAL :)

**Comment by akhil-rane** [comment]
@sgreene570 Resolved merge conflict. This needs lgtm again :)

**Pull request merged**
