### PR TITLE
Bug 1906560: Revert "Support changing ingresscontroller load balancer scope"

### PR DESCRIPTION
**Pull request by Miciah**
This reverts #472.

----

This is the backup plan if https://github.com/openshift/api/pull/822 / https://github.com/openshift/cluster-ingress-operator/pull/510 cannot be merged in 4.7.

### CODE REVIEW

**Comment by Miciah** [comment]
e2e-aws-operator won't pass (see #517), but e2e-aws should...
/retest

**Comment by knobunc** [comment]
/override ci/prow/e2e-aws-operator

This failure is expected until we get a cyclic dependency resolved.

**Comment by knobunc** [comment]
LGTM (but waiting for other reviewers)

**Comment by sgreene570** [comment]
Thanks Ben
/lgtm

**Pull request merged**
