### PR TITLE
OCPBUGS-16762: Revert "OCPBUGS-16762: Bump openshift/api for container.maxLength fix"

### PR DESCRIPTION
**Pull request by Miciah**
Reverts openshift/cluster-ingress-operator#979

---

The 4.15.0 fix didn't get verified in time to backport it to 4.14.0, so I am reverting the changes in 4.15.0 and will close the 4.14.0 bug report as "Can't Fix".

### CODE REVIEW

**Comment by rfredette** [comment]
`git diff` shows no difference between prior to #979 's merge and after this revert.
/approve
/lgtm

**Comment by Miciah** [comment]
Rebased for #985.

**Comment by frobware** [comment]
I looked at two things:

- Changes excluding vendor: `git diff 35f202fb395fc188a38396e48febb0b5c4ef37ad~1 ':(exclude)vendor/'`
- And specifically the changes to `go.mod` after the rebase in https://github.com/openshift/cluster-ingress-operator/pull/982#issuecomment-1778518112.

/lgtm

Leaving approval for @rfredette.

**Pull request merged**
