### PR TITLE
[release-4.14] OCPBUGS-36555: Implement connect timeout tuning option

### PR DESCRIPTION
**Pull request by alebedev87**
Backport of https://github.com/openshift/cluster-ingress-operator/pull/1097.

### CODE REVIEW

**Comment by lihongan** [comment]
/label qe-approved
/label cherry-pick-approved
verified by pre-merge testing
```
$ oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.14.0-0.ci.test-2024-07-12-013316-ci-ln-9by3v3k-latest   True        False         2m2s    Cluster version is 4.14.0-0.ci.test-2024-07-12-013316-ci-ln-9by3v3k-latest

$ oc explain ingresscontroller.spec.tuningOptions.connectTimeout
GROUP:      operator.openshift.io
KIND:       IngressController
VERSION:    v1

FIELD: connectTimeout <string>

DESCRIPTION:
    ConnectTimeout defines the maximum time to wait for a connection attempt to
    a server/backend to succeed. 
     This field expects an unsigned duration string of decimal numbers, each
    with optional fraction and a unit suffix, e.g. "300ms", "1.5h" or "2h45m".
    Valid time units are "ns", "us" (or "µs" U+00B5 or "μs" U+03BC), "ms",
    "s", "m", "h". 
     When omitted, this means the user has no opinion and the platform is left
    to choose a reasonable default. This default is subject to change over time.
    The current default is 5s.
    
$ oc -n openshift-ingress rsh router-default-6c6b5cf95b-b27nd
sh-4.4$ grep "timeout connect" haproxy.config
  timeout connect 5s

$ oc -n openshift-ingress-operator patch ingresscontroller/default -p '{"spec":{"tuningOptions":{"connectTimeout":"30s"}}}' --type=merge
ingresscontroller.operator.openshift.io/default patched

$ oc -n openshift-ingress get deployment/router-default -oyaml | grep TIMEOUT -A1
        - name: ROUTER_DEFAULT_CONNECT_TIMEOUT
          value: 30s

$ oc -n openshift-ingress rsh router-default-c55b5c64f-b96gh
sh-4.4$ env | grep TIMEOUT 
ROUTER_DEFAULT_CONNECT_TIMEOUT=30s
sh-4.4$ grep "timeout connect" haproxy.config
  timeout connect 30s
```

**Comment by knobunc** [comment]
/hold

Pending @gcs278 's review

**Comment by gcs278** [comment]
I did some sanity checks by recreating the backport, reviewing merge conflicts, and everything looks reasonable.

/unhold
/lgtm

**Pull request merged**
