### PR TITLE
[DNM][WIP] Temporarily removing local-with-fallback annotation for testing

### PR DESCRIPTION
**Pull request by ricky-rav**

### CODE REVIEW

**Comment by ricky-rav** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-sdn-upgrade 5

**Comment by ricky-rav** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.13-upgrade-from-stable-4.12-e2e-gcp-sdn-upgrade

**Comment by candita** [comment]
/title WIP Temporarily removing local-with-fallback annotation for testing

**Pull request closed without merging**
