### PR TITLE
Bug 1740441: manifests: make credentialsrequest names consistent

### PR DESCRIPTION
**Pull request by ironcladlou**
Use consistent naming for credentialsrequests.

### CODE REVIEW

**Comment by ironcladlou** [comment]
@csrwng @dgoodwin any upgrade implications here? Looks like the implication could be that in upgraded clusters we would have new and old request resources co-existing and targeting the same secret. Would the new resources simply remain unfulfilled as they conflict? If so that would still be fine from our operators' perspectives as we only consume the resulting secret, not the CSR itself.

**Comment by dgoodwin** [comment]
If the CVO doesn't reconcile deletions and remove the old cred requests, and both versions target the same destination secret, you're probably in line for trouble here. It would depend on the cloud actuator but for AWS, I believe both will get minted, and written to the same target secret, and you could easily be looking at a hotloop. Would need to be tested, should be pretty simple to do in any cluster just create a dupe request pointing to same target and see what happens.

**Comment by ironcladlou** [comment]
@dgoodwin Given that, and since our operator doesn't actually manage these resources, is there any path forward to renaming them? cc @abhinavdahiya

**Comment by dgoodwin** [comment]
You could write to a new target secret and have your operator use that, as well as cleanup the old cred requests.

**Comment by ironcladlou** [comment]
I'm going to leave AWS as-is because it at least has the right prefixing and doesn't seem worth migrating. Renaming Azure and GCP now should be okay since we haven't released 4.2 yet. Agree?

/hold cancel

**Comment by dgoodwin** [comment]
+1

**Comment by ironcladlou** [comment]
@Miciah PTAL

**Pull request merged**
