### PR TITLE
Update dns controller with Power VS platform

### PR DESCRIPTION
**Pull request by Karthik-K-N**
Related to Enhancement: https://github.com/openshift/enhancements/pull/736
Earlier ingress-operator PR: https://github.com/openshift/cluster-ingress-operator/pull/658

### CODE REVIEW

**Comment by Miciah** [comment]
`TestConfigurableRouteNoConsumingUserNoRBAC` and `TestHTTPCookieCapture` failed, but those may be flaking out.  Let's try again.
/test e2e-aws-operator
<details>

```
 === RUN   TestConfigurableRouteNoConsumingUserNoRBAC
    configurable_route_test.go:304: failed to restore cluster ingress resource to original state: Operation cannot be fulfilled on ingresses.config.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again
--- FAIL: TestConfigurableRouteNoConsumingUserNoRBAC (0.98s) 
```

```
 === RUN   TestHTTPCookieCapture
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1767: failed to read logs from pod router-cookiecapture-6b57846b4-44sct: pods "router-cookiecapture-6b57846b4-44sct" not found
    operator_test.go:1788: failed to observe the expected log message: timed out waiting for the condition
    panic.go:613: deleted ingresscontroller cookiecapture
--- FAIL: TestHTTPCookieCapture (96.58s) 
```
</details>

**Comment by Miciah** [comment]
Must-gather failed.  

/test e2e-aws-operator

**Comment by Karthik-K-N** [comment]
Thanks @Miciah and @candita, All the CI jobs are passed now

**Comment by Miciah** [comment]
Thanks!
/lgtm
/approve

**Comment by Miciah** [comment]
Hm, let's try that again.  
/lgtm
/approve

**Pull request merged**
