### PR TITLE
Removes replace of controller-runtime in go.mod

### PR DESCRIPTION
**Pull request by danehans**
Replacing `sigs.k8s.io/controller-runtime` with `github.com/munnerz/controller-runtime` is no longer required. Bumps controller-runtime to be compatible with k8s 1.16.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Awesome, thanks. We'll need this in dns-operator too.

/lgtm
/approve

**Comment by danehans** [comment]
@ironcladlou https://github.com/openshift/cluster-dns-operator/pull/137 is the same bump for the dns-operator.

**Pull request merged**
