### PR TITLE
Bug 1699488: Fixes Ingress ClusterOperator Initial Status

### PR DESCRIPTION
**Pull request by danehans**
Previously, `clusteroperator/ingress` was being created without `status`. Even though the resource was being created with status fields properly constructed and included in the `client.create` call, the resource is initially created without `status`. `clusteroperator/ingress` must be created first, then have the status updated.

### CODE REVIEW

**Comment by Miciah** [comment]
/lgtm
Same problem exists in cluster-dns-operator; would you like to fix it, or shall I?

**Comment by danehans** [comment]
@Miciah I'll fix in the dns operator too.

**Comment by danehans** [comment]
https://github.com/openshift/cluster-ingress-operator/pull/204 fixes this bug in cluster-dns-operator.

**Pull request merged**
