### PR TITLE
OCPBUGS-42004: Set the MI client ID for the ARO HCP override

### PR DESCRIPTION
**Pull request by bryan-cox**
Set the managed identity client ID for the ARO HCP override to use managed identity.

### CODE REVIEW

**Comment by bryan-cox** [comment]
I think we may need to set the client ID after all. Opening this as draft for now until I confirm that.

**Comment by Miciah** [comment]
Would you mind adding a reference to https://issues.redhat.com//browse/OCPBUGS-42004 to the commit message?

**Comment by bryan-cox** [comment]
> Would you mind adding a reference to https://issues.redhat.com//browse/OCPBUGS-42004 to the commit message?

@Miciah yeah no problem, it's been added.

**Pull request merged**
