### PR TITLE
[release-4.13] NE-1341: Add support for AWS shared VPC in another account 

### PR DESCRIPTION
**Pull request by gcs278**
Add support for configuring DNS records in AWS Route 53 using a separate account for the private hosted zone.

This PR cherry-picks https://github.com/openshift/cluster-ingress-operator/pull/928/commits/7251aaa9a30f3759c2731d061207d2f63cd945de (from https://github.com/openshift/cluster-ingress-operator/pull/928, the original implementation) and https://github.com/openshift/cluster-ingress-operator/pull/951/commits/047bd986587a923029586a2497ec99d0a5a242a0 (from https://github.com/openshift/cluster-ingress-operator/pull/951, a bug fix for https://issues.redhat.com/browse/OCPBUGS-14998).

**How I generated this backport:**
1. `git cherry-pick 7251aaa9a30f3759c2731d061207d2f63cd945de` (https://github.com/openshift/cluster-ingress-operator/pull/928/commits/7251aaa9a30f3759c2731d061207d2f63cd945de)
2. Resolved merge conflicts:
    - `pkg/manifests/bindata.go`: Regenerated
    - `pkg/operator/controller/dns/controller.go`:  Removed [`PrivateHostedZoneAWSEnabled`](https://github.com/openshift/cluster-ingress-operator/blob/b4b5f424e49a31840fd133561e01178a5d123e19/pkg/operator/controller/dns/controller.go#L118) from config structure for the dns controller. Removed associated check for [`r.config.PrivateHostedZoneAWSEnabled`](https://github.com/openshift/cluster-ingress-operator/blob/b4b5f424e49a31840fd133561e01178a5d123e19/pkg/operator/controller/dns/controller.go#L675C3-L675C61)
    - `pkg/operator/operator.go`:  https://github.com/openshift/cluster-ingress-operator/pull/928/commits/7251aaa9a30f3759c2731d061207d2f63cd945de had feature gate logic. We are not backporting the feature gate so I did not integrate any feature gate logic in the merge.
3. Completed cherry-pick with add, `git cherry-pick --continue`, etc...
4. Created a new commit to vendor openshift/api backport https://github.com/openshift/api/pull/1529
    - Modified `go.mod` to use `github.com/openshift/api v0.0.0-20230803134339-2d9b46419536`
    - `go mod tidy`
    - `go mod vendor`
5. `git cherry-pick 047bd986587a923029586a2497ec99d0a5a242a0` (https://github.com/openshift/cluster-ingress-operator/pull/951/commits/047bd986587a923029586a2497ec99d0a5a242a0)
    - No merge conflicts

### CODE REVIEW

**Comment by gcs278** [comment]
> The order of the commits looks funny

@Miciah Good catch, that makes sense so the implementation commit isn't broken.

https://github.com/openshift/cluster-ingress-operator/compare/ee6dccea564293606159ff6854cb084072d1d199..a0e58466f0ed23fee3e3334a15559133a21eb98b reorders the commits.

**Comment by Miciah** [comment]
Looks good; we just need the API backport to merge now so that the bump commit can have a proper ref.

**Comment by Miciah** [comment]
https://github.com/openshift/cluster-ingress-operator/compare/a0e58466f0ed23fee3e3334a15559133a21eb98b..1c6bac83c205164bb7e18d9715359f7c6818742e bumps to https://github.com/openshift/api/commit/2d9b4641953634dd191455e2399189b57a099a08 since https://github.com/openshift/api/pull/1529 merged.
/hold cancel
/test all

**Comment by patrickdillon** [comment]
>@patrickdillon may be recreating this PR with the official API merge depending on timing.

> https://github.com/openshift/cluster-ingress-operator/compare/a0e58466f0ed23fee3e3334a15559133a21eb98b..1c6bac83c205164bb7e18d9715359f7c6818742e bumps to [openshift/api@2d9b464](https://github.com/openshift/api/commit/2d9b4641953634dd191455e2399189b57a099a08) since [openshift/api#1529](https://github.com/openshift/api/pull/1529) merged. /hold cancel /test all

Looks like miciah was able to push directly to your remote and keep the original PR. Nice! Thanks!

**Comment by Miciah** [comment]
/lgtm

This change adds `sts:AssumeRole` to the CredentialsRequest and otherwise does not change the operator's behavior unless the new `spec.platform.aws.privateZoneIAMRole` option in the cluster DNS config is specified.
/label backport-risk-assessed

[e2e-aws-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/966/pull-ci-openshift-cluster-ingress-operator-release-4.13-e2e-aws-operator/1687138627471020032) because must-gather failed.
/test e2e-aws-operator

**Pull request merged**
