### PR TITLE
OCPBUGS-17733: [release-4.13] remove shared VPC cred request

### PR DESCRIPTION
**Pull request by patrickdillon**
Backporting credential requests has the potential of breaking upgrades, specifically if clusters are running in mint mode and have removed the root credentials during z-stream upgrades.

This commit removes the 4.13 bump to the cred request for the AWS shared VPC feature. The rest of the feature remains intact so that it can be utilized by managed services which does not depend on credential requests.

### CODE REVIEW

**Comment by patrickdillon** [comment]
/retitle OCPBUGS-17733: [release-4.13] remove shared VPC cred request

**Comment by patrickdillon** [comment]
> This pull request references [Jira Issue OCPBUGS-17733](https://issues.redhat.com//browse/OCPBUGS-17733), which is invalid:

 >   expected [Jira Issue OCPBUGS-17733](https://issues.redhat.com//browse/OCPBUGS-17733) to depend on a bug targeting a version in 4.14.0 and in one of the following states: VERIFIED, RELEASE PENDING, CLOSED (ERRATA), CLOSED (CURRENT RELEASE), CLOSED (DONE), but no dependents were found

We will need to override this, as this bug is directly applicable to 4.13. There is no 4.14 bug.

**Comment by gcs278** [comment]
`Pod pending timeout.` - Something unexpected happened with CI infra.
/retest

**Comment by Miciah** [comment]
#966 added the `sts:AssumeRole` permission to the CredentialsRequest, and #966 is in the 4.13.9 release.  #966 is expected to cause problems on clusters that run cloud-credential-operator in mint mode where the root secret has been removed.  For this reason, upgrades to 4.13.9 will be conditionally blocked for potentially impacted clusters.  #972 removes the permission and is intended to ship in the next z-stream release to avoid causing these problems.  
/label backport-risk-assessed

**Comment by Miciah** [comment]
[e2e-aws-ovn failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/972/pull-ci-openshift-cluster-ingress-operator-release-4.13-e2e-aws-ovn/1691478455708815360), but the error is unrelated to the changes in this PR.  
/override ci/prow/e2e-aws-ovn

**Pull request merged**
