### PR TITLE
BUG 1707477: label the openshift-ingress namespace with its name

### PR DESCRIPTION
**Pull request by squeed**
This will let us select for it with network policies.

### CODE REVIEW

**Comment by ironcladlou** [comment]
Thanks!
/lgtm

**Comment by danwinship** [comment]
/hold
Would it be better to use a label that more explicitly indicates that this is for selecting via NetworkPolicy?
If not there should at least be a comment there indicating that that label is effectively API

**Comment by squeed** [comment]
This is the way we've done it in 3.x, but, you're right - now's a reasonable chance to change that.

@ironcladlou - thoughts? How does this match with the expected pattern of ingress deployment? Will users be able to deploy the ingress controller in to other namespaces, and, if so, how would that impact this change?

Alternatively, just calling it `SOMETHING.openshift.io/has-router` would be good too.

**Comment by ironcladlou** [comment]
>Would it be better to use a label that more explicitly indicates that this is for selecting via NetworkPolicy?
If not there should at least be a comment there indicating that that label is effectively API

cc @smarterclayton @derekwaynecarr 

>@ironcladlou - thoughts? How does this match with the expected pattern of ingress deployment? Will users be able to deploy the ingress controller in to other namespaces, and, if so, how would that impact this change?

We have no concrete plans to allow ingress controllers in other namespaces, but we've been trying to leave that door open.

>Alternatively, just calling it SOMETHING.openshift.io/has-router would be good too.

Another option... `ingress.openshift.io/has-ingress-controller`

**Comment by Miciah** [comment]
> Another option... `ingress.openshift.io/has-ingress-controller`

We have no `ingress.openshift.io` API group, but rather put this operator's resource kinds in the `operator.openshift.io` API group, so `operator.openshift.io/has-ingress-controller` would make more sense.

**Comment by danwinship** [comment]
That seems kind of indirect.
I don't think there's any rule that says that label names should only use actual existing API groups.
But anyway, since the label exists for networking purposes, it could be `network.openshift.io/policy-group: ingress` or something

**Comment by squeed** [comment]
Policy-group seems reasonable. Or `network.openshift.io/role`.

Are there any other namespaces that would qualify? `role: apiserver`?

**Comment by danwinship** [comment]
anyway, we should commit *something* before freeze...

**Comment by squeed** [comment]
Oh crap, good point. I like policy-group.

**Comment by squeed** [comment]
Updated with `policy-group. I kept name as well, since users may wish to select by it.

**Comment by ironcladlou** [comment]
/lgtm
@squeed @danwinship feel free to remove the hold when you're satisfied with the name

**Comment by squeed** [comment]
aws timeout
/retest

**Comment by smarterclayton** [comment]
Title needed to be “Bug XXXX:”, not “BUG XXXX:”

**Pull request merged**
