### PR TITLE
Add client certificate and key to service monitor

### PR DESCRIPTION
**Pull request by xueqzhan**
Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md

### CODE REVIEW

**Comment by candita** [comment]
@xueqzhan can you create and add a Jira bug link for this?

**Comment by candita** [comment]
@xueqzhan it failed to pass verify test, putting on hold.
/hold

**Comment by xueqzhan** [comment]
> @xueqzhan if this is still a requirement, can you please link the jira issue?

Yes, this is still a requirement: [TRT-534](https://issues.redhat.com/browse/TRT-534). But it is pending an upstream fix. We can leave it on hold for now. Thanks

**Pull request closed without merging**
