### PR TITLE
OCPBUGS-33990: Avoid spurious updates for internalTrafficPolicy [Backport to 4.13]

### PR DESCRIPTION
**Pull request by candita**
This is a manual backport of #927  to fix OCPBUGS-33657.

 git cherry-pick 5579aa1b3573a4d9479a924a1ae78688e2105c5c
 go mod vendor
 go mod tidy
 make generate
 make update
 git cherry-pick 6cd3b6709eff0026ad814921b40c4b02c32fb38c
 go mod vendor
 go mod tidy
 make generate
 make update
    
 **Avoid spurious updates for internalTrafficPolicy**
    
 Specify spec.internalTrafficPolicy on NodePort- and ClusterIP-type services that the operator manages. Also, ignore updates to the spec.ipFamilies and spec.ipFamilyPolicy fields.
    
    Before this PR, the update logic for NodePort- and ClusterIP-type services would try to revert the default values that the API set for these fields.
    
    - assets/router/service-cloud.yaml:
    - assets/router/service-internal.yaml: Specify internalTrafficPolicy: Cluster.
    - pkg/manifests/bindata.go: Regenerate.
    - pkg/operator/controller/ingress/internal_service.go (internalServiceChanged): Ignore spec.ipFamilies and spec.ipFamilyPolicy.
    - pkg/operator/controller/ingress/internal_service_test.go (Test_desiredInternalIngressControllerService): Verify that spec.internalServiceChanged is set to "Cluster".
    (Test_internalServiceChanged): Verify that changes to spec.internalTrafficPolicy are detected and that changes to spec.ipFamilies and spec.ipFamilyPolicy are ignored.
    - pkg/operator/controller/ingress/nodeport_service.go (desiredNodePortService): Set spec.internalTrafficPolicy to "Cluster".
    (nodePortServiceChanged): Ignore spec.ipFamilies and spec.ipFamilyPolicy.
    pkg/operator/controller/ingress/nodeport_service_test.go (TestDesiredNodePortService): Verify that spec.internalTrafficPolicy is set to "Cluster".
    (TestNodePortServiceChanged): Verify that changes to spec.internalTrafficPolicy are detected and that changes to spec.ipFamilies and spec.ipFamilyPolicy are ignored.
    
**Ignore updates for null versus empty ennotations**
    Ignore updates to annotations when the update is from null to empty or vice versa.
    
    - pkg/operator/controller/ingress/internal_service.go (internalServiceChanged): Use EquateEmpty when comparing annotations.
    - pkg/operator/controller/ingress/internal_service_test.go (TestInternalServiceChangedEmptyAnnotations): New test to verify that internalServiceChanged treats empty and null annotations as equal.
    - pkg/operator/controller/ingress/load_balancer_service_test.go (TestLoadBalancerServiceChangedEmptyAnnotations): New test to verify that loadBalancerServiceChanged treats empty and null annotations as equal.
    - pkg/operator/controller/ingress/nodeport_service.go (nodePortServiceChanged): Use EquateEmpty when comparing annotations.
    - pkg/operator/controller/ingress/nodeport_service_test.go (TestNodePortServiceChangedEmptyAnnotations): New test to verify that loadBalancerServiceChanged treats empty and null annotations as equal.

### CODE REVIEW

**Comment by candita** [comment]
Test timed out after 1h?  

> === CONT  TestAll/serial/TestHostNetworkPortBinding
> panic: test timed out after 1h0m0s
> 
> goroutine 26147 [running]:
> testing.(*M).startAlarm.func1()
> 	/usr/lib/golang/src/testing/testing.go:2036 +0x8e
> created by time.goFunc
> 	/usr/lib/golang/src/time/sleep.go:176 +0x32
> 
> goroutine 1 [chan receive, 60 minutes]:
> testing.(*T).Run(0xc0000e96c0, {0x1c7e535?, 0x525725?}, 0x1db2978)
> 	/usr/lib/golang/src/testing/testing.go:1494 +0x37a
> testing.runTests.func1(0xc0009b1a40?)
> 	/usr/lib/golang/src/testing/testing.go:1846 +0x6e
> testing.tRunner(0xc0000e96c0, 0xc0009c5bd0)
> 	/usr/lib/golang/src/testing/testing.go:1446 +0x10b
> testing.runTests(0xc00063fd60?, {0x2f32a80, 0x56, 0x56}, {0x0?, 0x0?, 0x2fce1e0?})
> 	/usr/lib/golang/src/testing/testing.go:1844 +0x456
> testing.(*M).Run(0xc00063fd60)
> 	/usr/lib/golang/src/testing/testing.go:1726 +0x5d9
> github.com/openshift/cluster-ingress-operator/test/e2e.TestMain(0xffffffffffffffff?)
> 	/go/src/github.com/openshift/cluster-ingress-operator/test/e2e/operator_test.go:147 +0x2cf
> main.main()
> 	_testmain.go:219 +0x1d3
> 
> goroutine 24728 [chan receive, 1 minutes]:
> testing.tRunner.func1()
> 	/usr/lib/golang/src/testing/testing.go:1412 +0x4a5
> testing.tRunner(0xc000776000, 0x1db2960)
> 	/usr/lib/golang/src/testing/testing.go:1452 +0x144
> created by testing.(*T).Run
> 	/usr/lib/golang/src/testing/testing.go:1493 +0x35f

**Comment by candita** [comment]
I'm seeing issues with cluster-dns-operator degraded and machine pools not upgradeable for two (in a row) failures of e2e-aws-operator.  One more try.

/test e2e-aws-operator

**Comment by candita** [comment]
Test timed out after 1 hour again.  This time, failures seen show these tests are taking 65 minutes:

>         --- FAIL: TestAll/parallel/TestMTLSWithCRLs (1657.77s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-own-crl (329.79s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-signers-crl (331.54s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-signers-crl-with-workaround (331.82s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/large-crl (330.75s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/multiple-intermediate-ca (332.73s)
>         --- FAIL: TestAll/parallel/TestCRLUpdate (2273.04s)
>             --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-own-crl (568.22s)
>             --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-signers-crl (567.88s)
>             --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-signers-crl-with-workaround (568.29s)
>             --- FAIL: TestAll/parallel/TestCRLUpdate/many-CAs-with-signers-crl-workaround (568.62s)

**Comment by melvinjoseph86** [comment]
Verified using pre-image with cluster bot.
melvinjoseph@mjoseph-mac Downloads % oc get clusterversion
oc get po -n openshift-ingress-operatorNAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.13.0-0.ci.test-2024-05-23-055158-ci-ln-flf0fgk-latest   True        False         18m     Cluster version is 4.13.0-0.ci.test-2024-05-23-055158-ci-ln-flf0fgk-latest

After the cluster installation there was no more 'updated internal service' log messages in openshift-ingress-operator logs.
Even after creating a custom nodeport controller and a loadbalncer controller, there was no above log messages. Hence marking as verified.

**Comment by candita** [comment]
Machine config having some issues still

> - lastTransitionTime: "2024-05-23T08:39:29Z"
>     message: One or more machine config pools are updating, please see `oc get mcp`
>       for further details
>     reason: PoolUpdating
>     status: "False"
>     type: Upgradeable
> ...
>   - lastTransitionTime: "2024-05-23T07:27:39Z"
>     message: Cluster has deployed [{operator 4.13.0-0.ci.test-2024-05-23-065902-ci-op-4ksf3cww-latest}]
>     reason: AsExpected
>     status: "True"
>     type: Available
>   extension:
>     master: 2 (ready 2) out of 3 nodes are updating to latest configuration rendered-master-07719b5895f484e1d6fca7ead1748d53
>     worker: all 3 nodes are at latest configuration rendered-worker-469b47da7de2f9a277d7c6cb5a63078e

**Comment by candita** [comment]
Root cause of e2e-aws-operator failures:

> util_test.go:727: 2024-05-22 17:10:21 +0000 UTC {kubelet ip-10-0-140-176.ec2.internal} Pod crl-host Failed Failed to pull image "quay.io/centos7/httpd-24-centos7": rpc error: code = Unknown desc = reading manifest latest in quay.io/centos7/httpd-24-centos7: manifest unknown

Need the fix in https://github.com/openshift/cluster-ingress-operator/pull/1037 to be backported to 4.12.

**Comment by candita** [comment]
The fix in https://github.com/openshift/cluster-ingress-operator/pull/1037 has been backported to 4.12.
/test e2e-aws-operator

**Comment by rfredette** [comment]
/approve
/lgtm 
Looks good 👍

**Pull request merged**
