### PR TITLE
Fix TestHostNetworkEndpointPublishingStrategy

### PR DESCRIPTION
**Pull request by frobware**
The API change in https://github.com/openshift/api/pull/1097 does not mark the set of configurable ports on type `HostNetworkStrategy` as optional. It's not clear whether that was deliberate and/or intended but without specifying these ports the e2e test `TestHostNetworkEndpointPublishingStrategy()` will always fail.

### CODE REVIEW

**Comment by frobware** [comment]
error: error creating buildah builder: initializing source docker://image-registry.openshift-image-registry.svc:5000/ci-op-c2k6zvk7/pipeline@sha256:30ea73ec25783d6c04b6648a2e2ae60022f1c5f71bd296e2c4e84b9de840841a: pinging container registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp: i/o timeout

/retest

**Comment by frobware** [comment]
cc @arjunrn

**Comment by arjunrn** [comment]
@frobware I'm not sure I understand the cause of the failures. This repo does not contain the changes I made in openshift/api. So the CRD being created in the test cluster will not have the new fields. Secondly the ports are optional implicitly IIUC. Only fields which are listed in `required` are actually required.

cc @alebedev87

**Comment by frobware** [comment]
> Anyway, there is some defaulting for the values for the controller when it's not present(due to version upgrades) in my PR #694. If that's the cause of the issue then the defaulting should help.

Without `+optional` and `,omitempty` we don't get any defaults.

**Comment by frobware** [comment]
> @frobware I'm not sure I understand the cause of the failures. This repo does not contain the changes I made in openshift/api.

This is a good point. I currently have stacked API changes. I was trying to understand why my PR #735 was failing in CI. I have bumped to include my changes, but that will pick up yours too.

**Comment by Miciah** [comment]
`spec.endpointPublishingStrategy.hostNetwork` is an optional pointer-type field, so I wouldn't expect omitting the field entirely to be a problem.  Do you have an error message from a CI failure with a `Create` or `Update` call that fails because of the missing values?

**Comment by Miciah** [comment]
`TestHostNetworkEndpointPublishingStrategy` did **not** fail in [the last e2e-aws-operator run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/738/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator/1513836041046331392).

/test e2e-aws-operator

**Comment by frobware** [comment]
```console
2022-04-12T16:46:23.561+0100	INFO	operator.ingress_controller	controller/controller.go:114	reconciling	{"request": "openshift-ingress-operator/host"}
2022-04-12T16:46:24.259+0100	ERROR	operator.init.controller.ingress_controller	controller/controller.go:266	Reconciler error	{"name": "host", "namespace": "openshift-ingress-operator", "error": "failed to admit ingresscontroller: failed to update status: IngressController.operator.openshift.io \"host\" is invalid: [status.endpointPublishingStrategy.hostNetwork.httpsPort: Invalid value: 0: status.endpointPublishingStrategy.hostNetwork.httpsPort in body should be greater than or equal to 1, status.endpointPublishingStrategy.hostNetwork.statsPort: Invalid value: 0: status.endpointPublishingStrategy.hostNetwork.statsPort in body should be greater than or equal to 1, status.endpointPublishingStrategy.hostNetwork.httpPort: Invalid value: 0: status.endpointPublishingStrategy.hostNetwork.httpPort in body should be greater than or equal to 1]"}
```

This is the error I see when creating the following:

```yaml
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: "2022-04-12T15:14:20Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 1
  name: host
  namespace: openshift-ingress-operator
  resourceVersion: "105051"
  uid: 93e19982-6366-4345-a1fe-d3cadbd8d712
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  domain: foo.host.amcdermo-2022-04-12-1246.devcluster.openshift.com
  endpointPublishingStrategy:
    type: HostNetwork
    hostNetwork:
```

which is, as I understand things, the reason why the test fails because we don't currently specify any values for the 3 ports.

**Comment by frobware** [comment]
Obsoleted by https://github.com/openshift/api/pull/1175.

**Pull request closed without merging**
