### PR TITLE
OCPBUGS-24531: Revert " OCPBUGS-24531 Skip CI for scope change until OCPBUGS-24044 is resolved"

### PR DESCRIPTION
**Pull request by candita**
This reverts commit fe6809626569beeec32c561c9a5fe6a1f249b65d.

### CODE REVIEW

**Comment by candita** [comment]
/remove-do-not-merge/work-in-progress

**Comment by candita** [comment]
e2e-gcp-operator has new failures.  We may need to continue skipping the tests.  Will try again.

> TestAll/parallel/TestInternalLoadBalancerGlobalAccessGCP
>     operator_test.go:1196: Expected conditions: map[Admitted:True Available:True DNSManaged:True DNSReady:True LoadBalancerManaged:True LoadBalancerReady:True]
>          Current conditions: map[Admitted:True Available:False DNSManaged:True DNSReady:False Degraded:True DeploymentAvailable:True DeploymentReplicasAllAvailable:True DeploymentReplicasMinAvailable:True DeploymentRollingOut:False EvaluationConditionsDetected:False LoadBalancerManaged:True LoadBalancerProgressing:False LoadBalancerReady:False Progressing:False Upgradeable:True]
>     operator_test.go:1196: Ingress Controller openshift-ingress-operator/test-gcp status: {
> 
>     "message": "One or more status conditions indicate unavailable: LoadBalancerReady=False (LoadBalancerPending: The LoadBalancer service is pending)"
>             },
> ...
>               "message": "One or more other status conditions indicate a degraded state: LoadBalancerReady=False (LoadBalancerPending: The LoadBalancer service is pending)"
>   
and same for 

>  NAME  TestAll/parallel/TestScopeChange
>     operator_test.go:1466: Expected conditions: map[Admitted:True Available:True DNSManaged:True DNSReady:True LoadBalancerManaged:True LoadBalancerReady:True]
>          Current conditions: map[Admitted:True Available:False DNSManaged:True DNSReady:False Degraded:True DeploymentAvailable:True DeploymentReplicasAllAvailable:True DeploymentReplicasMinAvailable:True DeploymentRollingOut:False EvaluationConditionsDetected:False LoadBalancerManaged:True LoadBalancerProgressing:False LoadBalancerReady:False Progressing:False Upgradeable:True]
>     operator_test.go:1466: Ingress Controller openshift-ingress-operator/scope status: {

/test e2e-gcp-operator

**Comment by candita** [comment]
e2e-azure-operator had different failures, in a test that was formerly skipped.  Can try again to get a sense of permanence.

> NAME  TestAll/parallel/TestManagedDNSToUnmanagedDNSIngressController
>     unmanaged_dns_test.go:177: verifying conditions on DNSRecord zone {ID:/subscriptions/d38f1e38-4bed-438e-b227-833f997adf6a/resourceGroups/ci-op-6b4r66k2-04a70-txmtk-rg/providers/Microsoft.Network/privateDnsZones/ci-op-6b4r66k2-04a70.ci.azure.devcluster.openshift.com Tags:map[]}
>     unmanaged_dns_test.go:177: DNSRecord zone expected to have status=Unknown but got status=True

/test e2e-azure-operator

**Comment by candita** [comment]
GCP retest succeeded!  Azure retest was an installation failure, will retest once more.

/test e2e-azure-operator

**Comment by Miciah** [comment]
https://github.com/openshift/cluster-ingress-operator/compare/9a872878deb0421105da88c9fe25b1079aa2f2ea..92b6a524a8c4fcdb20d4c43032b4172ccc8597b5 is empty, so this PR effectively reverts all the changes in #1008 and #1007, getting us back to the tree we had once #995 merged.  
/approve
/lgtm

**Pull request merged**
