### PR TITLE
OCPBUGS-28673: implement connect timeout tuning option

### PR DESCRIPTION
**Pull request by alebedev87**
This PR implements the connect timeout tuning option. The corresponding API PR: https://github.com/openshift/api/pull/1829.

Also, the way the CRDs are copied from the vendored API has changed. The IngressController and DNSRecord CRDs were moved to dedicated packages following the introduction of a new method for generating CRDs in the OpenShift API (https://github.com/openshift/api/pull/1803). This PR adds these new packages as tool imports to make use of the go.mod versioning and to be able to `go get` them before copying into manifests directory.

### CODE REVIEW

**Comment by alebedev87** [comment]
/hold

Let's hold this PR until https://github.com/openshift/cluster-ingress-operator/pull/1045 is merged. This way the update generated CRD problem will be addressed separately from the connect timeout bug.

**Comment by rfredette** [comment]
/approve
/lgtm
Thanks!

**Pull request merged**
