### PR TITLE
Remove unused method in manifests

### PR DESCRIPTION
**Pull request by pravisankar**
- Remove 'k8s.io/apiextensions-apiserver' pkg dependency
- Retry in case of caching issues

### CODE REVIEW

**Comment by pravisankar** [comment]
@openshift/sig-network-edge PTAL

**Comment by ironcladlou** [comment]
Thanks! For future ref, I wonder if these could have been two PRs

/lgtm

**Comment by pravisankar** [comment]
```
level=error msg="2 errors occurred:"
level=error msg="\t* module.vpc.aws_route_table_association.route_net[3]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.route_net.3: timeout while waiting for state to become 'success' (timeout: 5m0s)"
```
/retest

**Pull request merged**
