### PR TITLE
OCPBUGS-38079: Bump controller-runtime to v0.18.4

### PR DESCRIPTION
**Pull request by Miciah**
Bump the vendored sigs.k8s.io/controller-runtime package to [v0.18.4](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.18.4), the latest release, which uses the k8s.io/* v0.30.1 packages.

Bump the vendored k8s.io/client-go package to v0.30.2.  A previous commit bumped the other k8s.io/* packages to v0.30.2 but left k8s.io/client-go at v0.29.0.  However, controller-runtime v0.18.4 requires k8s.io/client-go v0.30.0 or newer [because of a breaking change](https://github.com/kubernetes-sigs/controller-runtime/issues/2788) in the client-go leaderelection package.

    go get sigs.k8s.io/controller-runtime@v0.18.4
    go mod edit -replace=k8s.io/client-go=k8s.io/client-go@v0.30.2
    go mod tidy
    go mod vendor

Update calls to `controller.Watch` to adapt to [breaking changes in controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/pull/2783).  Namely, the handler and predicate arguments have been removed from `Watch` and are now specified as options on the source. Additionally, the `source.Kind` type now has a type parameter, so it is necessary to specify a `client.Object` type argument.

Follow-up to #1046, which bumped the other k8s.io/* packages to v0.30.2.

### CODE REVIEW

**Comment by frobware** [comment]
I believe there's a missing @ in the description; what worked for me and yields no diffs to your `go.mod` is:

```sh
go mod edit -replace=k8s.io/client-go=k8s.io/client-go@v0.30.2
```

/lgtm
/approve

**Comment by Miciah** [comment]
> I believe there's a missing @ in the description; what worked for me and yields no diffs to your `go.mod` is:
> 
> ```shell
> go mod edit -replace=k8s.io/client-go=k8s.io/client-go@v0.30.2
> ```

Thanks!  You're right; I think I typed the wrong command, then correct it, but pasted the wrong one in the commit message and PR description.  Fixed in https://github.com/openshift/cluster-ingress-operator/compare/63f3f9cf1ea0720b9a63f2085f063b3a60f963eb..202d8870a2af3ea2a621695757b642bbf0f826b6.

**Comment by Miciah** [comment]
https://github.com/openshift/cluster-ingress-operator/compare/202d8870a2af3ea2a621695757b642bbf0f826b6..2639954d5a10378ad4702faadac2f86806e714ad rebases to resolve conflicts from #1118.

**Comment by frobware** [comment]
- could not run steps: step src failed: error occurred handling build src-amd64: build not successful after 5 attempts: [the build src-amd64 failed after 17s with reason FetchImageContentFailed: Failed to extract image content., the build src-amd64 failed after 18s with reason FetchImageContentFailed: Failed to extract image content., the build src-amd64 failed after 7m1s with reason FetchImageContentFailed: Failed to extract image content.] 

/test-required

**Pull request merged**
