### PR TITLE
[release-4.11] OCPBUGS-14456, OCPBUGS-14457: Handle mTLS CRLs, and fix accidental CRL duplication

### PR DESCRIPTION
**Pull request by rfredette**
Manual cherry pick & squash of #939 

---

Leave a stub of the CRL controller to clean up any existing configmaps. The stub controller will need to be removed in a future release

Use cluster-wide proxy for CRL downloads when available

Add a test with several test cases to test CRL management, and a test to test CRL updates

### CODE REVIEW

**Comment by frobware** [comment]
/hold

This PR depends on https://github.com/openshift/router/pull/492.

**Comment by frobware** [comment]
e2e-aws-operator - `FAIL: TestAll/parallel/TestAWSELBConnectionIdleTimeout`, which is bug https://issues.redhat.com/browse/OCPBUGS-13810. 

Investigation for 13810 happening in: https://github.com/openshift/cluster-ingress-operator/pull/940.

**Comment by frobware** [comment]
e2e-aws-single-node - "Failed while waiting on imagestream import"

/test e2e-aws-single-node

**Comment by frobware** [comment]
/test e2e-aws-operatoe

I see failures for the mTLS tests: 

```
        --- FAIL: TestAll/parallel/TestCRLUpdate (391.96s)
            --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-own-crl (100.07s)
            --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-signers-crl (101.13s)
            --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-signers-crl-with-workaround (94.11s)
            --- FAIL: TestAll/parallel/TestCRLUpdate/many-CAs-with-signers-crl-workaround (96.51s)
        --- FAIL: TestAll/parallel/TestMTLSWithCRLs (526.73s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-own-crl (102.39s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-signers-crl (101.77s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-signers-crl-with-workaround (102.69s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/large-crl (104.38s)
            --- FAIL: TestAll/parallel/TestMTLSWithCRLs/multiple-intermediate-ca (105.24s)
```

**Comment by frobware** [comment]
> /test e2e-aws-operatoe
> 
> I see failures for the mTLS tests:
> 
> ```
>         --- FAIL: TestAll/parallel/TestCRLUpdate (391.96s)
>             --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-own-crl (100.07s)
>             --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-signers-crl (101.13s)
>             --- FAIL: TestAll/parallel/TestCRLUpdate/certificate-distributes-its-signers-crl-with-workaround (94.11s)
>             --- FAIL: TestAll/parallel/TestCRLUpdate/many-CAs-with-signers-crl-workaround (96.51s)
>         --- FAIL: TestAll/parallel/TestMTLSWithCRLs (526.73s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-own-crl (102.39s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-signers-crl (101.77s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/certificate-distributes-its-signers-crl-with-workaround (102.69s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/large-crl (104.38s)
>             --- FAIL: TestAll/parallel/TestMTLSWithCRLs/multiple-intermediate-ca (105.24s)
> ```

This is not a problem; see https://github.com/openshift/cluster-ingress-operator/pull/942#issuecomment-1574102429.

**Comment by lihongan** [comment]
/unhold
since https://github.com/openshift/router/pull/492 get merged

**Comment by frobware** [comment]
Failed: [sig-arch][Late] operators should not create watch channels very often [Suite:openshift/conformance/parallel] 

/test e2e-aws-single-node

**Comment by frobware** [comment]
> level=fatal msg=failed to fetch Terraform Variables: failed to fetch dependency of "Terraform Variables": failed to generate asset "Platform Provisioning Check": baseDomain: Invalid value: "origin-ci-int-aws.dev.rhcloud.com": the zone already has record sets for the domain of the cluster: [api.ci-op-ih8pi4zj-51128.origin-ci-int-aws.dev.rhcloud.com. (A), \052.apps.ci-op-ih8pi4zj-51128.origin-ci-int-aws.dev.rhcloud.com. (A)] Installer exit with code 1
> 
> /test e2e-aws-operator

See also: https://redhat-internal.slack.com/archives/CEKNRGF25/p1686218879266109

**Comment by frobware** [comment]
> New changes are detected. LGTM label has been removed.

This is a no-edit commit. See: https://redhat-internal.slack.com/archives/CEKNRGF25/p1686220147776379?thread_ts=1686218879.266109&cid=CEKNRGF25

/lgtm
/approve

**Pull request merged**
