### PR TITLE
Bug 1906032: Canary: Set daemonset MaxUnavailable to 10%

### PR DESCRIPTION
**Pull request by sgreene570**
Enable the canary daemonset's rolling updates to scale
linearly with the number of nodes in a cluster by setting
the maxUnavailable value to 10 % instead of the default
absolute value of 1.

assets/canary/daemonset.yaml: Set MaxUnavailable to 10%

pkg/manifests/bindata: regenerate

### CODE REVIEW

**Comment by sgreene570** [comment]
`--- FAIL: TestHTTPCookieCapture (104.30s)`
/retest

**Review by wking — APPROVED** [review]
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/509/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws/1336732532061769728/artifacts/e2e-aws/gather-extra/daemonsets.json | jq -r '.items[] | select(.metadata.namespace == "openshift-ingress-canary").spec.updateStrategy'
{
  "rollingUpdate": {
    "maxUnavailable": "10%"
  },
  "type": "RollingUpdate"
}
```

**Comment by lihongan** [comment]
/lgtm
(see https://bugzilla.redhat.com/show_bug.cgi?id=1906032#c1)

**Pull request merged**
