### PR TITLE
support other Azure cloud environments

### PR DESCRIPTION
**Pull request by staebler**
Use the Azure cloud environment specified by the `status.platformStatus.azure.cloudName` field of the infrastructure.config.openshift.io resource.

See openshift/enhancements#321

### CODE REVIEW

**Comment by staebler** [comment]
/hold

This is currently vendoring an openshift/api fork until openshift/api#650 merges.

**Comment by staebler** [comment]
a79b1ac1...8c401e96
* Bumped to the latest master version of openshift/api to include the changes from openshift/api#650.
* Rebased onto latest master

/hold cancel

**Comment by Miciah** [comment]
@staebler, this PR needs to be rebased for #417, which moved client creation from `start.go` to `pkg/operator/controller/dns/controller.go`.  Do you want to do the rebase, or shall I open a new PR?

**Comment by staebler** [comment]
> @staebler, this PR needs to be rebased for #417, which moved client creation from `start.go` to `pkg/operator/controller/dns/controller.go`. Do you want to do the rebase, or shall I open a new PR?

I have done the rebase.

**Comment by staebler** [comment]
93a8c62b...6e192f83
* Rebased onto master
* Specify the base URI when creating Azure clients.

**Comment by staebler** [comment]
Results for testing this on a cluster installed on Azure Gov Cloud.
```
$ oc get clusteroperator ingress
NAME      VERSION                   AVAILABLE   PROGRESSING   DEGRADED   SINCE
ingress   0.0.1-2020-07-23-130820   True        False         False      12m

$ oc -n openshift-ingress-operator get dnsrecords -o yaml | yq -y '.items[] | (.spec, .status)'
dnsName: '*.apps.mstaeble.groupgmag.azure.devcluster.openshift.com.'
recordTTL: 30
recordType: A
targets:
  - 20.140.191.176
---
observedGeneration: 1
zones:
  - conditions:
      - lastTransitionTime: '2020-07-23T13:58:38Z'
        message: The DNS provider succeeded in ensuring the record
        reason: ProviderSuccess
        status: 'False'
        type: Failed
    dnsZone:
      id: /subscriptions/XXX/resourceGroups/mstaeble-njbbb-rg/providers/Microsoft.Network/privateDnsZones/mstaeble.groupgmag.azure.devcluster.openshift.com
  - conditions:
      - lastTransitionTime: '2020-07-23T13:58:38Z'
        message: The DNS provider succeeded in ensuring the record
        reason: ProviderSuccess
        status: 'False'
        type: Failed
    dnsZone:
      id: /subscriptions/XXX/resourceGroups/os4-common/providers/Microsoft.Network/dnszones/groupgmag.azure.devcluster.openshift.com

$ curl -kIs https://console-openshift-console.apps.mstaeble.groupgmag.azure.devcluster.openshift.com | head -n1
HTTP/1.1 200 OK
```

**Pull request merged**
