### PR TITLE
OCPBUGS-9274: canary: Tolerate infra node NoExecute taint

### PR DESCRIPTION
**Pull request by Miciah**
Configure the canary daemonset to tolerate a "node-role.kubernetes.io/infra" node taint that specifies the `NoExecute` effect (or any other effect).

Before this change, the canary daemonset tolerated the "node-role.kubernetes.io/infra" node taint only if it specified the `NoSchedule` effect.  However, some cluster admins taint infra nodes using both `NoSchedule` as well as `NoExecute`, in which case canary pods would not be scheduled on these nodes.  This inconsistency caused some confusion. With this change, canary pods should be scheduled on infra nodes whether or not they are tainted using the `NoExecute` effect.

* `assets/canary/daemonset.yaml`: Tolerate the "node-role.kubernetes.io/infra" taint irrespective of the specified effect.
* `pkg/manifests/bindata.go`: Regenerate.
* `pkg/operator/controller/canary/daemonset_test.go` (`TestDesiredCanaryDaemonSet`): Expect `Effect` to be unspecified on the toleration.
(`TestCanaryDaemonsetChanged`): Add a test case to verify that `canaryDaemonSetChanged` correctly detects the change and updates the daemonset if the specified effect changes on the toleration.

### CODE REVIEW

**Comment by candita** [comment]
> Hypershift error:
> 2023-05-30T15:22:47Z	INFO	Detected Issuer URL	{"issuer": "https://hypershift-ci-1-oidc.s3.us-east-1.amazonaws.com/1b0ddf9389406da45310-mgmt"}
> 2023-05-30T15:22:47Z	ERROR	Failed to create cluster	{"error": "failed to create iam: LimitExceeded: Cannot exceed quota for OpenIdConnectProvidersPerAccount: 100\n\tstatus 

/retest-required

**Comment by candita** [comment]
Seeing this repeatedly, wonder if it is transient:
> [controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:

/retest-required

**Comment by Miciah** [comment]
[e2e-aws-operator failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/932/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator/1664010276791390208) because kube-apiserver and ovnkube-master failed to roll out some pods.
/test e2e-aws-operator

**Comment by Miciah** [comment]
[e2e-aws-operator](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/932/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-operator/1676990353481142272), [e2e-aws-ovn](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/932/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn/1676990353502113792), [e2e-aws-ovn-serial](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/932/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn-serial/1676990353523085312), [e2e-aws-ovn-single-node](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/932/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn-single-node/1676990353606971392), and [e2e-aws-ovn-upgrade failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/932/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn-upgrade/1676990353640525824) because teh build cluster had no available nodes.
/test e2e-aws-operator

**Pull request merged**
