### PR TITLE
[release-4.15] OCPBUGS-35028: internalServiceChanged: Fix target port logic

### PR DESCRIPTION
**Pull request by candita**
This is a manual cherry-pick of #1072
Replaces #1079 

git cherry-pick 71eead5286597657de281306876b5d94dea7e4ad 5d0939ad56e239919acfd962882ab7c076b4b7d9 14daecdb9ca49a7742afd922a8a9b55acf6935a6 f2060e0c0440d9ac79e0c456b564ef0047709007 0cbd86a4438c45be8c2917b781503b06f52bd55e 826745c3a1db822c0538f3322e98b33bd628ed13 50e8a730070d8f0864694df476da4c9fdf2a168b eb1623e71ca636ab3a3ecf2b39ab59e42209f5b8 87975f7833badbe8cbb9942eaf0a46c3c9481f9a caeca655be660dd93be63d3bc370c8616deb8641 2aed24f184b7f98124547d293a5a316e3eeca535 
go mod tidy (to add module update to 2aed24f1)
go mod vendor
modify pkg/operator/controller/ingress/deployment_test.go 
git add go.*
git add vendor/*
git add pkg/operator/controller/ingress/deployment_test.go 
git commit --amend (to add Modified-by to 2aed24f1)
make update
make verify
make build
make test
git cherry-pick 1f9795b4f6d1c2829c2ed53eb5b08d70e917cafe 77595d00a45865819153d2094b1f15b40e508111
go mod tidy
go mod vendor
make update
make verify
make build
make test

### CODE REVIEW

**Comment by candita** [comment]
I may have missed a commit, unit test fails:

> ok  	github.com/openshift/cluster-ingress-operator/pkg/operator/controller/clientca-configmap	0.085s
> # github.com/openshift/cluster-ingress-operator/pkg/operator/controller/ingress [github.com/openshift/cluster-ingress-operator/pkg/operator/controller/ingress.test]
> pkg/operator/controller/ingress/deployment_test.go:1051:179: too many arguments in call to desiredRouterDeployment
> 	have (*"github.com/openshift/api/operator/v1".IngressController, string, *"github.com/openshift/api/config/v1".Ingress, *"github.com/openshift/api/config/v1".Infrastructure, *"github.com/openshift/api/config/v1".APIServer, *"github.com/openshift/api/config/v1".Network, bool, bool, *"k8s.io/api/core/v1".ConfigMap, *"github.com/openshift/api/config/v1".Proxy, bool)
> 	want (*"github.com/openshift/api/operator/v1".IngressController, string, *"github.com/openshift/api/config/v1".Ingress, *"github.com/openshift/api/config/v1".Infrastructure, *"github.com/openshift/api/config/v1".APIServer, *"github.com/openshift/api/config/v1".Network, bool, bool, *"k8s.io/api/core/v1".ConfigMap, *"github.com/openshift/api/config/v1".Proxy)

**Comment by frobware** [comment]
I noticed that the PR description runs `go mod vendor` before `go mod tidy`. To ensure dependencies are correctly managed, the order should be reversed:

- Running `go mod tidy` first: This cleans up the go.mod and go.sum files by removing any unused dependencies and adding any missing ones.
- Then `go mod vendor`: This generates the vendor directory with the accurate set of dependencies listed in go.mod.

Tidy followed by vendor ensures the `vendor` directory is created with a clean and accurate set of dependencies.

**Comment by frobware** [comment]
> I may have missed a commit, unit test fails:

Maybe https://github.com/openshift/cluster-ingress-operator/commit/4b561335c926bdf189db17528120d3c3dd95a8f2?

**Comment by candita** [comment]
> I noticed that the PR description runs `go mod vendor` before `go mod tidy`. To ensure dependencies are correctly managed, the order should be reversed:
> 
> * Running `go mod tidy` first: This cleans up the go.mod and go.sum files by removing any unused dependencies and adding any missing ones.
> * Then `go mod vendor`: This generates the vendor directory with the accurate set of dependencies listed in go.mod.
> 
> Tidy followed by vendor ensures the `vendor` directory is created with a clean and accurate set of dependencies.

I always run the sequence twice, vendor, tidy, vendor, tidy - that keeps things clean.  I'll try it this way to save a few up-arrows.

**Comment by candita** [comment]
> > I may have missed a commit, unit test fails:
> 
> Maybe [4b56133](https://github.com/openshift/cluster-ingress-operator/commit/4b561335c926bdf189db17528120d3c3dd95a8f2)?

It should just be the 13 commits in https://github.com/openshift/cluster-ingress-operator/pull/1072 plus an additional commit for the module vendoring in this release.  I think 4b56133 is for another feature....

**Comment by ShudiLi** [comment]
/label qe-approved
tested it with 4.15.0-0.ci.test-2024-06-11-070036-ci-ln-35wdcm2-latest 
```
1.
% oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.15.0-0.ci.test-2024-06-11-070036-ci-ln-35wdcm2-latest   True        False         17m     Cluster version is 4.15.0-0.ci.test-2024-06-11-070036-ci-ln-35wdcm2-latest

2.
% oc -n openshift-ingress-operator -c ingress-operator rsync ingress-operator-854d7fd4-gwz6w:/usr/bin/ingress-operator .
receiving file list ... done
ingress-operator

sent 38 bytes  received 95461093 bytes  10048540.11 bytes/sec
total size is 95437696  speedup is 1.00

3.
% go version -m ingress-operator | grep "k8s.io/utils"            
	dep	k8s.io/utils	v0.0.0-20240502163921-fe8a2dddb1d0

4.
% oc create -f ingress-hostnetwork.yaml 
ingresscontroller.operator.openshift.io/int1 created

5.
% oc -n openshift-ingress get pods
NAME                             READY   STATUS    RESTARTS   AGE
router-default-9776dcdc9-9bz8s   1/1     Running   0          27m
router-default-9776dcdc9-k6qc7   1/1     Running   0          27m
router-int1-544c8bcd97-fbml6     1/1     Running   0          71s

6.
% oc -n openshift-ingress get svc router-internal-int1 -o=jsonpath="{.spec.ports}"
[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"},{"name":"https","port":443,"protocol":"TCP","targetPort":"https"},{"name":"metrics","port":1936,"protocol":"TCP","targetPort":"metrics"}]%  

7.
% oc -n openshift-ingress get ep router-internal-int1 -o=jsonpath="{.subsets[0].ports}"
[{"name":"metrics","port":23936,"protocol":"TCP"},{"name":"https","port":23443,"protocol":"TCP"},{"name":"http","port":23080,"protocol":"TCP"}]%

8.
% oc -n openshift-ingress get deployment router-int1 -oyaml | grep -E -A9 "ivenessProbe:|readinessProbe:|startupProbe:"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /healthz
            port: 23936
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          terminationGracePeriodSeconds: 10
--
        readinessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /healthz/ready
            port: 23936
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
--
        startupProbe:
          failureThreshold: 120
          httpGet:
            host: localhost
            path: /healthz/ready
            port: 23936
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1

9.
 % oc -n openshift-ingress get deployment router-int1 -oyaml | grep -A6 " - configMap:"
      - configMap:
          defaultMode: 420
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: service-ca-bundle
          optional: false

10.
% oc -n openshift-ingress get svc router-internal-int1 -o=jsonpath="{.spec.sessionAffinity}" 
None%

11.
% oc create -f ingress-internal.yaml 
ingresscontroller.operator.openshift.io/int2 created

12.
% print $(oc -n openshift-ingress get svc router-int2 -o=jsonpath="{.spec.type}\n{.spec.sessionAffinity}")
LoadBalancer
None

```

**Comment by frobware** [comment]
Any reason to lump the change to deployment_test.go and the go mod updates into one commit? Will the PR be used for as the base to back port into older releases? If so, a discrete commit for the go mod changes and one for the change to deployment_test.go would make things easier.

**Comment by Miciah** [comment]
/approve
/lgtm

/retitle [release-4.15] OCPBUGS-35028: internalServiceChanged: Fix target port logic

Quoting https://github.com/openshift/cluster-ingress-operator/pull/1072#issuecomment-2146609753:

> This PR makes many changes to the update logic for several objects, which poses some risk. However, several factors mitigate the risk: It is a clean cherry-pick from the release-4.17 branch, there has been little drift so far between the release-4.16 and release-4.17 branches, we had intended to merge this in time for the release-4.16 branch cut anyway, and the original PR was reviewed quite thoroughly. I believe it is worth the risk to get these changes in the release-4.16 branch.

The 4.15 backport has some `go mod` changes and a minor test fix on top of the changes in the 4.16 backport, so the risk assessment is the same.  

/label backport-risk-assessed

**Comment by candita** [comment]
> > > I may have missed a commit, unit test fails:
> > 
> > 
> > Maybe [4b56133](https://github.com/openshift/cluster-ingress-operator/commit/4b561335c926bdf189db17528120d3c3dd95a8f2)?
> 
> It should just be the 13 commits in #1072 plus an additional commit for the module vendoring in this release. I think [4b56133](https://github.com/openshift/cluster-ingress-operator/commit/4b561335c926bdf189db17528120d3c3dd95a8f2) is for another feature....looking into what I need to change here.

This required a small, manual change.

**Comment by candita** [comment]
Post steps failed for e2e azure operator:
> ERRO[2024-06-11T20:56:19Z] 
>   * could not run steps: step e2e-azure-operator failed: "e2e-azure-operator" post steps failed: "e2e-azure-operator" pod "e2e-azure-operator-gather-extra" failed: could not watch pod: the pod ci-op-zp7sxq57/e2e-azure-operator-gather-extra failed after 1m45s (failed containers: test): ContainerFailed one or more containers exited

/test e2e-azure-operator

**Pull request merged**
