### PR TITLE
Bug 1928931: Update DNSRecord CRD from v1beta1 to v1

### PR DESCRIPTION
**Pull request by rfredette**
CRD is being removed from v1beta1 in Kubernetes 1.22, so this PR changes DNSRecord to the v1 version of CRD.

The process I followed for this change was:
```bash
go get github.com/openshift/api@f67d7a61e06075e9c84bc731fca470fff2832227
go mod vendor
make generate
```

[openshift/api commit f67d7a61e06075e9c84bc731fca470fff2832227](https://github.com/openshift/api/commit/f67d7a61e06075e9c84bc731fca470fff2832227) is the commit that updates DNSRecord in the openshift/api tree, and as of the creation of this PR, the latest commit in openshift/api's master branch.

### CODE REVIEW

**Comment by sgreene570** [comment]
/hold
```
I0317 18:44:25.367596       1 sync_worker.go:935] Update error 294 of 669: UpdatePayloadResourceInvalid Could not update customresourcedefinition "dnsrecords.ingress.operator.openshift.io" (294 of 669): the object is invalid, possibly due to local cluster configuration (*errors.StatusError: CustomResourceDefinition.apiextensions.k8s.io "dnsrecords.ingress.operator.openshift.io" is invalid: spec.scope: Required value)
```
looks like the DNSRecord CRD needs some more adjustments.

**Comment by Miciah** [comment]
Lovely jubbly!
/lgtm

**Pull request merged**
