### PR TITLE
Add unsupported config override for maxconn

### PR DESCRIPTION
**Pull request by Miciah**
This PR bundles (in logically separate commits) a fix to the reload interval override, a small fix to the E2E tests, and a new unsupported config override for `ROUTER_MAX_CONNECTIONS`.

#### `waitForDeploymentComplete`: Actually use timeout arg

* `test/e2e/operator_test.go` (`waitForDeploymentEnvVar`): Use the provided timeout parameter instead of a hard-coded value of 1 minute.

#### Specify a time unit in `RELOAD_INTERVAL`

Specify a time unit suffix "s" for seconds in the value of the `RELOAD_INTERVAL` environment variable in router deployments.  Omitting the time unit causes the following warning:

    router "msg"="invalid interval, using default"  "default"=5 "interval"="5" "name"="RELOAD_INTERVAL"

* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Add "s" time unit suffix to the reload interval.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`):
* `test/e2e/operator_test.go` (`TestReloadIntervalUnsupportedConfigOverride`): Expect the time unit suffix.

#### Add unsupported config override for `maxconn`

Add an unsupported config override for setting HAProxy's global `maxconn` setting.  If the config override is unspecified, the current default of 20000 is used.  If the config override has the value "-1", the `maxconn` setting is omitted so that HAProxy automatically detects a reasonable value based on the value of `ulimit -n`.

* `pkg/operator/controller/ingress/deployment.go` (`RouterMaxConnectionsEnvName`): New const.
(`desiredRouterDeployment`): Add unsupported config override for `ROUTER_MAX_CONNECTIONS`.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Verify that `desiredRouterDeployment` sets `ROUTER_MAX_CONNECTIONS` as expected.
* `test/e2e/operator_test.go` (`TestMaxConnectionsUnsupportedConfigOverride`): Verify that the operator sets `ROUTER_MAX_CONNECTIONS` to the appropriate value based on the value specified in the unsupported configuration override if an override is specified.

#### `test/e2e`: Get ingresscontroller before update

When updating an ingresscontroller, do a get immediately before doing the update.

This is a cleanup and should have no significant functional effect.

* `test/e2e/operator_test.go` (`TestProxyProtocolAPI`, `TestLoadBalancingAlgorithmUnsupportedConfigOverride`, `TestDynamicConfigManagerUnsupportedConfigOverride`, `TestReloadIntervalUnsupportedConfigOverride`): Get ingresscontroller immediately before updating it.

#### `test/e2e`: Ignore some not-found errors on delete

Ignore not-found errors when deleting client pods.  These pods run and then exit, and it is possible that they get garbage collected before the test code deletes them, in which case it is expected that they be not found.

* `test/e2e/canary_test.go` (`TestCanaryRoute`):
* `test/e2e/client_tls_test.go` (`TestClientTLS`):
* `test/e2e/http_header_buffer_test.go` (`TestHTTPHeaderBufferSize`):
* `test/e2e/http_header_name_case_adjustment_test.go` (`TestHeaderNameCaseAdjustment`):
* `test/e2e/operator_test.go` (`TestHTTPHeaderCapture`, `TestHTTPCookieCapture`, `TestUniqueIdHeader`): Ignore not-found errors when deleting client pods.

---

Setting a config override of `maxConnections: -1` requires https://github.com/openshift/router/pull/304 to work properly.

### CODE REVIEW

**Comment by frobware** [comment]
error getting cluster version: Get "https://api.ci-op-3v7xm0xs-2945d.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusterversions/version": dial tcp 52.200.26.31:6443: i/o timeout
ClusterID: 
ClusterVersion: Installing "" for <unknown>: <unknown>
error getting cluster operators: Get "https://api.ci-op-3v7xm0xs-2945d.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 52.200.26.31:6443: i/o timeout
ClusterOperators:
	clusteroperators are missing

/retest

**Comment by frobware** [comment]
Failure: 

- Operator degraded (APIServerDeployment_UnavailablePod::OAuthServerDeployment_UnavailablePod): APIServerDeploymentDegraded: 1 of 3 requested instances are unavailable for apiserver.openshift-oauth-apiserver (container is not ready in apiserver-86489765cf-jvf27 pod) OAuthServerDeploymentDegraded: 1 of 3 requested instances are unavailable for oauth-openshift.openshift-authentication (container is not ready in oauth-openshift-9b57696b7-4nnkj pod)

/retest

**Comment by frobware** [comment]
Looks like cluster is not stood up: 

- Operator unavailable (null): Cluster not available for 4.9.0-0.ci.test-2021-07-23-101951-ci-op-dqg56vm1-latest

/retest

**Comment by Miciah** [comment]
Working on a fix for this:

    === RUN   TestMaxConnectionsUnsupportedConfigOverride
        operator_test.go:2191: failed to update ingresscontroller: Operation cannot be fulfilled on ingresscontrollers.operator.openshift.io "max-connections": the object has been modified; please apply your changes to the latest version and try again
        panic.go:613: deleted ingresscontroller max-connections
    --- FAIL: TestMaxConnectionsUnsupportedConfigOverride (37.07s)

**Pull request merged**
