### PR TITLE
[release-4.14] OCPBUGS-35399: Internal service changed: fix target port logic

### PR DESCRIPTION
**Pull request by candita**
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/1081

git cherry-pick 71eead5 5d0939a 14daecd f2060e0 0cbd86a 826745c 50e8a73 eb1623e  caeca65 2aed24f
fix merge conflict in deployment_test.go
git add pkg/operator/controller/ingress/deployment_test.go
git cherry-pick --continue
go mod tidy
go mod vendor
make update
make verify
make build
make test
test failed, fix another issue in deployment_test.go
go mod tidy
go mod vendor
make update
make verify
make build
make test
git add go.*
git add vendor/*
git add pkg/operator/controller/ingress/deployment_test.go
git commit --amend
git cherry-pick 1f9795b 77595d0
go mod tidy
go mod vendor
make update
make verify
make build
make test

### CODE REVIEW

**Comment by Miciah** [comment]
https://github.com/openshift/cluster-ingress-operator/pull/1086/commits/894de3f625078b0500470fabcd0eb79f3f5362d1 can be dropped as `Test_deploymentConfigChanged` in this branch doesn't use the `"k8s.io/utils/pointer"` package.

**Comment by candita** [comment]
Alot of these types of failures:
> Name:apiserver-866f7747dd-pcd8r UID:6ee403fc-09e1-447d-9efd-76a23e430dd7 APIVersion:v1 ResourceVersion:52019 FieldPath:spec.containers{oauth-apiserver}} Reason:Unhealthy Message:Readiness probe failed: Get "https://10.129.0.96:8443/readyz": dial tcp 10.129.0.96:8443: connect: connection refused Source:{Component:kubelet Host:ip-10-0-24-30.us-east-2.compute.internal} FirstTimestamp:2024-06-12 19:31:29 +0000 UTC LastTimestamp:2024-06-12 19:32:19 +0000 UTC Count:11 Type:Warning EventTime:0001-01-01 00:00:00 +0000 UTC Series:nil Action: Related:nil ReportingController:kubelet ReportingInstance:ip-10-0-24-30.us-east-2.compute.internal}
> resulting new interval: reason/Unhealthy Readiness probe failed: Get "https://10.129.0.96:8443/readyz": dial tcp 10.129.0.96:8443: connect: connection refused (11 times) from: 2024-06-12 

/test e2e-aws-ovn-upgrade

**Comment by candita** [comment]
Many alerts related to:

> OVNKubernetesResourceRetryFailure was at or above info for at least 57m18s on platformidentification.JobType{Release:"4.14", FromRelease:"", Platform:"aws", Architecture:"amd64", Network:"ovn", Topology:"ha"} (maxAllowed=0s): pending for 0s, firing for 57m18s:

/test e2e-aws-ovn-serial

**Comment by candita** [comment]
> [894de3f](https://github.com/openshift/cluster-ingress-operator/commit/894de3f625078b0500470fabcd0eb79f3f5362d1) can be dropped as `Test_deploymentConfigChanged` in this branch doesn't use the `"k8s.io/utils/pointer"` package.

Done.  Changed from 13 to 12 commits, and results found in https://github.com/openshift/cluster-ingress-operator/compare/dd2c229709deae809365dc5973c7562291180f06..11b9f2594a22da53297ac620b1a63794b871c885

**Comment by lihongan** [comment]
/retitle [release-4.14] OCPBUGS-35399: Internal service changed: fix target port logic

**Comment by ShudiLi** [comment]
to address OCPBUGS-35399

**Comment by Miciah** [comment]
> > [894de3f](https://github.com/openshift/cluster-ingress-operator/commit/894de3f625078b0500470fabcd0eb79f3f5362d1) can be dropped as `Test_deploymentConfigChanged` in this branch doesn't use the `"k8s.io/utils/pointer"` package.
> 
> Done. Changed from 13 to 12 commits, and results found in https://github.com/openshift/cluster-ingress-operator/compare/dd2c229709deae809365dc5973c7562291180f06..11b9f2594a22da53297ac620b1a63794b871c885
> 
> [71cf9ec](https://github.com/openshift/cluster-ingress-operator/commit/71cf9ec1d07b3d8fa1aa45c41af6b8ba67afe320) in this branch does use the "k8s.io/utils/pointer" package.

Thanks!  I think you meant https://github.com/openshift/cluster-ingress-operator/pull/1086/commits/3b16a4c982143329195c03684d270280b5e20238.  Anyway, everything looks as expected now.  

/approve
/lgtm

The 4.14 backport looks the same as the 4.15 backport modulo changes from bumping the vendored `k8s.io/utils` packages and dropping https://github.com/openshift/cluster-ingress-operator/commit/87975f7833badbe8cbb9942eaf0a46c3c9481f9a, both of which changes are low-risk, so the overall risk assessment is the same as for the 4.15 backport.  

/label backport-risk-assessed

**Pull request merged**
