### PR TITLE
Bug 1950270: go.mod: Update openshift/api & go version

### PR DESCRIPTION
**Pull request by sgreene570**
**go.mod: Update openshift/api & go version**

go.*:

Update openshift/api to commit
`c22782737ea0a882ed8d4e2c9bd3b974ee3bfca0` to pull in openshift/api#886.
Update go.mod go version to go 1.16 and run `go mod tidy`.
Move from kube deps `v0.21.0-rc.0` to `v0.21.0` since kubernetes 1.21 has been officially released.

vendor:

Run `go mod vendor`.

**Bindata: Update generated CRD**

manifests/00-custom-resource-definition.yaml:

Run `make update` to update the Ingress Controller CRD.

pkg/manifests/bindata.go:

Commit bindata changes from `make update`.

This commit resolves Bug 1950270, in which
`oc explain ingresscontroller.spec.nodePlacement --api-version=operator.openshift.io/v1`
displays an outdated default node selector for Ingress Controller deployments.

### CODE REVIEW

**Comment by sgreene570** [comment]
rebased. https://github.com/openshift/cluster-ingress-operator/pull/579 has merged.
/hold cancel

**Comment by Miciah** [comment]
Thanks!
/lgtm

**Pull request merged**
