### PR TITLE
OCPBUGS-33792: Bump openshift/library-go to resolve NewPrometheusClient E2E failures

### PR DESCRIPTION
**Pull request by gcs278**
Bump openshift/library-go to get update (https://github.com/openshift/library-go/pull/1697) for NewPrometheusClient function that switches from using a legacy service account API to TokenRequest API. This update resolves issues in our E2E tests that depend on this function.

```
go get github.com/openshift/library-go@f1541d628746a866ef2ffecbb4fd15ec9e64b2a1
go mod tidy
go mod vendor
```

Resolve ca.MakeServerCert hostnames parameter change from deprecated sets.String to generic Set.

This was caused by the work done in https://issues.redhat.com/browse/API-1644, more specifically https://github.com/openshift/openshift-controller-manager/pull/305

[Slack Thread](https://redhat-internal.slack.com/archives/C01CQA76KMX/p1715877704244329)

### CODE REVIEW

**Comment by gcs278** [comment]
Whoops, I needed to resolve a parameter type change in `ca.MakeServerCert`. I've fixed that, and now Github isn't updating my PR with my recent changes...I've forced pushed twice.

**Comment by gcs278** [comment]
Seems like it resolved the permafailing issue, but I did get a:
`    route_metrics_test.go:365: failed to fetch expected metrics: error waiting for route metrics: timed out waiting for the condition
`
in e2e-azure-operator. Not sure if this is a new flake or old flake. Sounds like it's an old flake, but search.CI isn't working well for me to confirm.
/test e2e-azure-operator

**Comment by gcs278** [comment]
Let's try again.
/test e2e-aws-operator
/test e2e-gcp-operator

**Comment by gcs278** [comment]
Definitely looks like this solves the problem. I also followed up in [slack](https://redhat-internal.slack.com/archives/C01CQA76KMX/p1715877704244329) to confirm this is the right solution. It is:

> - As of OCP 4.11, service account API token secrets (now referred to as “legacy”) were no longer generated automatically for each service account.
> - All users were supposed to migrate to using the TokenRequest API.
> - Unfortunately, the integrated image registry was also generating a legacy service account API token for its own use, and some users started to accidentally pick up the token intended for the image registry and missed migrating to the TokenRequest API.
> - Starting in v4.15, if the image registry is not enabled, the tokens will not be generated. The image registry is still enabled by default, so again another missed opportunity to catch people not using the TokenRequest API.
> - Finally, in v4.16 the image registry no longer generates the legacy service account API token at all. I tried to catch all the stragglers out there before merging (took me about 4 months of fixing tests), but alas it seems that you found another one.

**Comment by Miciah** [comment]
> in e2e-azure-operator. Not sure if this is a new flake or old flake. Sounds like it's an old flake, but search.CI isn't working well for me to confirm.

I only see that one failure when I [search for that failure over the past 14 days, filtering by jobs with names containing "cluster-ingress-operator"](https://search.dptools.openshift.org/?search=failed+to+fetch+expected+metrics%3A+error+waiting+for+route+metrics%3A+timed+out+waiting+for+the+condition&maxAge=336h&context=1&type=build-log&name=cluster-ingress-operator&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job).

Anyway, your changes look good.  Thanks!
/approve
/lgtm

**Comment by Miciah** [comment]
I would ask you to link to the OCPBUGS ticket in the commit message, but fixing CI is urgent, and I'd rather not delay merging this fix.

**Comment by Miciah** [comment]
> > Finally, in v4.16 the image registry no longer generates the legacy service account API token at all. I tried to catch all the stragglers out there before merging (took me about 4 months of fixing tests), but alas it seems that you found another one.

Seems to me that it would be a simple matter of reviewing the audit logs for a few different CI runs for various CI jobs (for example, e2e, serial, and techpreview)?  But oh well, that's in the past.

**Comment by Miciah** [comment]
> > > Finally, in v4.16 the image registry no longer generates the legacy service account API token at all. I tried to catch all the stragglers out there before merging (took me about 4 months of fixing tests), but alas it seems that you found another one.
> 
> Seems to me that it would be a simple matter of reviewing the audit logs for a few different CI runs for various CI jobs (for example, e2e, serial, and techpreview)? But oh well, that's in the past.

It would also be prudent to follow up on ["prometheus service account not found" errors in search.ci](https://search.dptools.openshift.org/?search=prometheus+service+account+not+found&maxAge=48h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job).

**Comment by gcs278** [comment]
Thanks @Miciah. I think we are going to have to override `e2e-hypershift` for the same [problem](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1054/pull-ci-openshift-cluster-ingress-operator-master-e2e-hypershift/1791174768548909056): `prometheus service account not found`. Or we wait until https://github.com/openshift/hypershift/pull/4044 has been merrged, which should fix their E2E tests.

Feel comfortable to override @Miciah?

**Comment by Miciah** [comment]
> Thanks @Miciah. I think we are going to have to override `e2e-hypershift` for the same [problem](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1054/pull-ci-openshift-cluster-ingress-operator-master-e2e-hypershift/1791174768548909056): `prometheus service account not found`. Or we wait until [openshift/hypershift#4044](https://github.com/openshift/hypershift/pull/4044) has been merged, which should fix their E2E tests.
> 
> Feel comfortable to override @Miciah?

Not totally confident.  How confident are you that the e2e-hypershift failures are all caused by the same Prometheus issue (or some other flake)?  Do you know whether https://github.com/openshift/hypershift/pull/4044 is likely to be `/lgtm`'d and merged today or whether it will need to wait for tomorrow?  Alternatively, maybe there's a HyperShift engineer around who could check the e2e-hypershift failures on this PR for us.

**Comment by gcs278** [comment]
> > Thanks @Miciah. I think we are going to have to override `e2e-hypershift` for the same [problem](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1054/pull-ci-openshift-cluster-ingress-operator-master-e2e-hypershift/1791174768548909056): `prometheus service account not found`. Or we wait until [openshift/hypershift#4044](https://github.com/openshift/hypershift/pull/4044) has been merged, which should fix their E2E tests.
> > Feel comfortable to override @Miciah?
> 
> Not totally comfortable. How confident are you that the e2e-hypershift failures are all caused by the same Prometheus issue (or some other flake)? Do you know whether [openshift/hypershift#4044](https://github.com/openshift/hypershift/pull/4044) is likely to be `/lgtm`'d and merged today or whether it will need to wait for tomorrow? Alternatively, maybe there's a HyperShift engineer around who could check the e2e-hypershift failures on this PR for us.

[Following up](https://redhat-internal.slack.com/archives/C01CQA76KMX/p1715899474354309?thread_ts=1715877704.244329&cid=C01CQA76KMX) with the hypershift team.

I feel confident that `prometheus service account not found` errors are preventing `e2e-hypershift` from succeeding, but I can't guarantee that there isn't another failure being masked by the prometheus service account failure. The safest is to wait for https://github.com/openshift/hypershift/pull/4044 if we can afford the time.

**Comment by Miciah** [comment]
> I feel confident that `prometheus service account not found` errors are preventing `e2e-hypershift` from succeeding, but I can't guarantee that there isn't another failure being masked by the prometheus service account failure. The safest is to wait for [openshift/hypershift#4044](https://github.com/openshift/hypershift/pull/4044) if we can afford the time.

Can you do a Cluster Bot `test openshift/cluster-ingress-operator#1054,openshift/hypershift#4044 e2e-hypershift`?  I'm not sure about the exact syntax or whether it's possible to run e2e-hypershift using Cluster Bot.

**Comment by candita** [comment]
> I feel confident that `prometheus service account not found` errors are preventing `e2e-hypershift` from succeeding, but I can't guarantee that there isn't another failure being masked by the prometheus service account failure. The safest is to wait for [openshift/hypershift#4044](https://github.com/openshift/hypershift/pull/4044) if we can afford the time.

I've been monitoring another [release oversight slack thread](https://redhat-internal.slack.com/archives/C01CQA76KMX/p1715801813175769) where they suspect that the new DNS Name Resolver functionality is causing them an issue, so it is going to be worth it to check with them.

**Comment by lihongan** [comment]
/label qe-approved
e2e-[aws|gcp|azure]-operator are passed

**Comment by gcs278** [comment]
> > I feel confident that `prometheus service account not found` errors are preventing `e2e-hypershift` from succeeding, but I can't guarantee that there isn't another failure being masked by the prometheus service account failure. The safest is to wait for [openshift/hypershift#4044](https://github.com/openshift/hypershift/pull/4044) if we can afford the time.
> 
> Can you do a Cluster Bot `test openshift/cluster-ingress-operator#1054,openshift/hypershift#4044 e2e-hypershift`? I'm not sure about the exact syntax or whether it's possible to run e2e-hypershift using Cluster Bot.

I don't think the `e2e-hypershift` job is a "supported test suite", they are:
```
e2e, e2e-serial, e2e-all, e2e-disruptive, e2e-disruptive-all, e2e-builds, e2e-image-ecosystem, e2e-image-registry, e2e-network-stress.
```

I assume `e2e` here are openshit/origin tests. I [asked](https://redhat-internal.slack.com/archives/CNHC2DK2M/p1714608944447939?thread_ts=1714576622.239969&cid=CNHC2DK2M) about something similar how to do this in clusterbot in #forum-ocp-crt and they recommended to launch a cluster and they run the test manually. That's pretty painful, but possible I suppose. I can look into it.

**Comment by Miciah** [comment]
With branch-cut imminent, let's go ahead and get this change merged in order to unbreak CI.  
/override ci/prow/e2e-hypershift

**Comment by gcs278** [comment]
Maybe this will work? Vendoring doesn't usually cleanly cherry-pick, but lets see...
/cherry-pick release-4.16

**Pull request merged**
