### PR TITLE
OCPBUGS-14057: Add runbook urls for prometheus alerts.

### PR DESCRIPTION
**Pull request by miheer**
Add runbook urls for prometheus alerts.
Ticket: https://issues.redhat.com/browse/OCPBUGS-14057

### CODE REVIEW

**Comment by ShudiLi** [comment]
tested it with 4.15.0-0.ci.test-2024-03-27-032758-ci-ln-izznskk-latest
1.
% oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.15.0-0.ci.test-2024-03-27-032758-ci-ln-izznskk-latest   True        False         104m    Cluster version is 4.15.0-0.ci.test-2024-03-27-032758-ci-ln-izznskk-latest

2.
% oc -n openshift-ingress-operator get  PrometheusRule ingress-operator -oyaml | grep  -B5  runbook_url
        description: This alert fires when HAProxy fails to reload its configuration,
          which will result in the router not picking up recently created or modified
          routes.
        message: HAProxy reloads are failing on {{ $labels.pod }}. Router is not respecting
          recently created or modified routes
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/HAProxyReloadFail.md
--
    - alert: HAProxyDown
      annotations:
        description: This alert fires when metrics report that HAProxy is down.
        message: HAProxy metrics are reporting that HAProxy is down on pod {{ $labels.namespace
          }} / {{ $labels.pod }}
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/HAProxyDown.md
--
      annotations:
        description: This alert fires when the IngressController status is degraded.
        message: |
          The {{ $labels.namespace }}/{{ $labels.name }} ingresscontroller is
          degraded: {{ $labels.reason }}.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/IngressControllerDegraded.md
--
      annotations:
        description: This alert fires when the IngressController is not available.
        message: |
          The {{ $labels.namespace }}/{{ $labels.name }} ingresscontroller is
          unavailable: {{ $labels.reason }}.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/IngressControllerUnavailable.md
--
      annotations:
        description: This alert fires when there is an Ingress with an unset IngressClassName
          for longer than one day.
        message: Ingress {{ $labels.namespace }}/{{ $labels.name }} is missing the
          IngressClassName for 1 day.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/IngressWithoutClassName.md
--
      annotations:
        description: This alert fires when there is a Route owned by an unmanaged
          Ingress.
        message: Route {{ $labels.namespace }}/{{ $labels.name }} is owned by an unmanaged
          Ingress.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/UnmanagedRoutes.md

**Comment by candita** [comment]
@miheer we only need the runbook url for critical alerts.  It would be better if you could enhance the one you wrote for HAProxyDown and removed the others, which are not needed.

**Pull request closed without merging**
