### PR TITLE
DPP-10860: Update Bugzilla links to "Networking" component

### PR DESCRIPTION
**Pull request by Miciah**
Update Bugzilla links that reference the "Routing" component" to instead use the "Networking" component and "router" subcomponent.

* `.github/ISSUE_TEMPLATE/config.yml`:
* `README.md`: Update Bugzilla links.

### CODE REVIEW

**Comment by frobware** [comment]
Looks like must gather failed:

/test e2e-aws-operator
/skip

**Comment by Miciah** [comment]
We discussed it, and engineering may unilaterally approve PRs that only change README files and GitHub configuration.
/approve
/label docs-approved
/label px-approved

**Pull request merged**
